### ISSUE TITLE
Visibility Change for Stipulated Decisions (SDEC)

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#10045]
As a member of the general public, so that I can read and understand how USTC interprets the law, I need decisions filed on or after 8/1/2023 to be viewable from the docket record to all users.

In an effort to increase transparency into the cases heard by the USTC, the Court is adopting a policy that all post-trial briefs filed by practitioners should be publicly available. This will be done on a prospective basis as of August 1, 2023 following a public notice in advance of this policy change.

Recently the decision was made to include most decision-type documents in this policy as well. As three of the decision documents (OAD/ODD/DEC) are already publicly available due to being Orders, this will affect one event code: Stipulated Decision (SDEC).

Proposed Stipulated Decisions (PSDE) are NOT in scope.

Stipulated Decisions filed prior to 8/1/23 will not be in scope, and cannot be retroactively made visible.

## Pre-Conditions
Blocked until https://github.com/flexion/ef-cms/issues/9866 is completed

## Acceptance Criteria
* Stipulated Decisions (event code SDEC) filed on or after 8/1/2023 are visible to all users when viewing the docket record. This applies **only** to Stipulated Decisions filed on or after 8/1/2023; stipulated decisions filed prior to this date are not affected
* Sealed documents still obey sealing visibility rules, even when meeting the above criteria 
* Stricken decisions are *never* available to the public

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Questions from pre-refinement: Should these be searchable?
