### ISSUE TITLE
AWS v2 -> v3 conversion: S3

### ISSUE THREAD

**Issue by jimlerza** [flexion/ef-cms#10336]
## Pre-Conditions

 - none

## Acceptance Criteria

 - All usages of the AWS v2 S3 SDK have been converted to the AWS v3 S3 SDK.

## Pain Avoided/Frustration Saved

 - AWS v2 SDK has been deprecated

## Breadth/Pervasiveness of Problem

 - Used in app context, so all downstream uses will need to be checked and adjusted if necessary.

## Complexity of Problem (Low, Medium, High) and Why it's Complex

- medium

## Notes

**Comment by jhansen-flexion** [comment]
Blocked: Waiting for Lerza to return, need concensus on a decision.

**Comment by zachrog** [comment]
Affected areas
1. Printing reports
2. Creating a Case
3. Reprint paper service pdf
4. Zipping documents (Docket record/trial session working copy)
5. Stamp preview
6. Entry of appearance
7. Opening/preview document
8. Custom Case report csv.
9. Cold case report csv.
10. Trial session Planning Report.
