### ISSUE TITLE
AWS v2 -> v3 conversion: SQS

### ISSUE THREAD

**Issue by jimlerza** [flexion/ef-cms#10337]
## Pre-Conditions

 - none

## Acceptance Criteria

 - All usages of the AWS v2 SQS SDK have been converted to the AWS v3 SQS SDK.

## Pain Avoided/Frustration Saved

 - AWS v2 SDK has been deprecated

## Breadth/Pervasiveness of Problem

 - Used in app context, so all downstream uses will need to be checked and adjusted if necessary.

## Complexity of Problem (Low, Medium, High) and Why it's Complex

- medium

## Notes

**Comment by ttlenard** [comment]
eService Testing Results:

- [x] Petitioner - Notice of Receipt of Petition
- [x] Petitioner - Create Account - Account verification
- [ ] Docket - Add paper filing - print paper service + eService to other parties
- [ ] Docket - PDF upload
- [ ] Docket - Order
- [ ]
