### ISSUE TITLE
Spike: Investigate Postgres Database

### ISSUE THREAD

**Issue by zachrog** [flexion/ef-cms#10391]
Started as Reduce Time and Cost for Database Migrations however evolved into a Spike to investigate implement Postgres in place of Dynamodb and reducing dependance on OpenSearch.

## Acceptance Criteria
- Implement Messages in Postgres
- Determine Postgres Infrastructure
- The cost of performing a migration is reduced.
- The speed of a migration is increased.
- The stability of the migration process is maintained.

## Pain Avoided/Frustration Saved
- Easier to access and query database
- High $$$ cost of doing a migration
- Complex infrastructure and process for migrations
- Migrations can take a long time depending on the data size.

## Breadth/Pervasiveness of Problem
  Every time a migration occurs we need to spend hundreds of dollars to perform it and it may take ~8 hours to do.

## Complexity of Problem (Low, Medium, High) and Why it's Complex
High complexity as migrations can involve infrastructure, code changes, and deployment strategies
High complexity as literally changes our data access patterns and introduces new technical stack.

**Comment by ttlenard** [comment]
Tested the following on TEST with all court user roles:
- [ ] Create new message and send
- [ ] Reply to a message
- [ ] Forward a message
- [ ] Create Order from Message
- [ ] View existing messages in a case
- [ ] Expand message threads in a case
- [ ] Complete a single message from a message thread
- [ ] Complete a single message from the inbox
- [ ] Complete multiple messages at once from the inbox
- [ ] View messages in Sent
- [ ] View messages in Completed
- [ ] View messages in the inbox
- [ ] View recent messages on Judge/Chambers Dashboard
- [ ] QC process - complete and send message
- [ ] Messages are removed from sent and completed boxes after 7 days

**Comment by pixiwyn** [comment]
- write a script to delete all the messages after the deployment was successful
- automate the glue job to also work with these rds changes
- document and do a walk through about how the expand contract process would work for RDS related migrations
- walk through with tenille and anyone else on the team about how to connect to the postgres database
- give one last opportunity to demo to team and get any last questions about the changes
