### ISSUE TITLE
AWS v2 -> v3 conversion: API Gateway Management API

### ISSUE THREAD

**Issue by jtdevos** [flexion/ef-cms#10415]
## Pre-Conditions

 - none

## Acceptance Criteria

 - All usages of the AWS v2 ApiGatewayManagementApi SDK have been converted to the AWS v3 ApiGatewayManagementApi SDK.

## Pain Avoided/Frustration Saved

 - AWS v2 SDK has been deprecated

## Breadth/Pervasiveness of Problem

 - Used in app context.

## Complexity of Problem (Low, Medium, High) and Why it's Complex

- medium

## Notes

**Comment by ttlenard** [comment]
Tests:
- [ ] Private Practitioner update contact information (address + phone)
- [ ] Private Practitioner file multiple documents across a consolidated group
- [ ] Calendaring
- [ ] Change of Trial Judge
- [ ] Remote to In Person
- [ ] In person to remote
- [ ] 30-day notice of trial
- [ ] Serving a Petition to IRS
- [ ] Submit a Petition
- [ ] External user Upload large documents
- [ ] Download all documents from a large case
- [ ] Download all case documents from a trial session
