### ISSUE TITLE
Move User (Judge/TrialClerk) Case Notes to Postgres

### ISSUE THREAD

**Issue by pixiwyn** [flexion/ef-cms#10492]
branch off: origin/10391-dynamo-migrations-kysely-aurora-rds-tokens (till merged in)

DynamoDB Entities to Replace:

- user-case-note

convert the functions in web-api/src/persistence/dynamo/userCaseNotes to postgres kysely functions.

DynamoDB Functions to Move (unit tests can be removed):
<img width="640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWNBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c2237446dd206d1e06ad339280f96d8200a0cbcf/2024-09-25_10-49-19.png" alt="2024-09-25_10-49-19.png" />

**Comment by ttlenard** [comment]
Things I tested:
- [ ] Judge User can add/edit/delete a Judge Note on the Session Copy page
- [ ] Judge User can add/edit/delete a Judge Note on the Case
- [ ] Chambers User can add/edit/delete a Judge Note on the Session Copy page
- [ ] Chambers User can add/edit/delete a Judge Note on the Case
- [ ] Users outside of the Specific Judge's Chambers cannot view Judge's Notes
- [ ] Sticky note icon displays appropriately when there is a Judge's note (submitted bug #10526 as a result of testing this - issue is unrelated to this story)
- [ ] Judge Notes that existed prior to this story display on Session Copy pages and on Cases
- [ ] Judge/Chambers can still add formatting (spaces, indentations) to their notes and the formatting is retained when viewing in DAWSON
- [ ] Maximum characters of X are still retained.
