### ISSUE TITLE
Petitions Clerk: Send petition package to IRS. (1.4)

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#110]
As a Petitions Clerk, in order notify the IRS of the case filing, I need to send the Petition package to the IRS.

In order for the IRS to know that a case has been filed in the Court, the Petitions clerk transmits/sends the petition package (copy of Petition, Request for place of trial, STIN) to the IRS, who then internally routes the package to the appropriate IRS office and IRS attorney who will be working the case.
	
## Pre-conditions:
* Petition package has been saved in system.
* Petition package is associated with Docket #.
* Petition package is sent to the IRS immediately
* The Petition package is error-free (all 3 documents have been uploaded by Petitioner)

## Acceptance Criteria (Post-conditions):
* Petitions Clerk can transmit the petition package to the IRS successfully once reviewed
* Petitions Clerk can verify the case has been forwarded to the IRS
* Petitions Clerk name, Date and time of service/transmission is captured as metadata in the "Audit Log"
* Date and time of service/transmission is viewable in the "Docket Record"
* Is removed from the Petitions Clerk Work Queue
* Case status is changed to General Docket

## Notes:
* The actual transmission function will be a later story and we may need to be coordinated with IRS IT to figure out how this needs to be accomplished.

## Tasks
- [x] Design how clerk indicates send and success message (Sarah)
- [x] Create mock IRS API (will/cody)
- [x] Persistence layer method to talk to mock IRS API (will/cody)
- [x] Create use case to call the Persistence layer (will/cody)
- [x] Create use case proxy for the front-end to hit (will/cody)
- [x] Create Lambda to call the use case (will/cody)
- [x] Create a sequence that will be called by the UI (will/cody)
- [x] Code the screen and success message (will/cody)
- [x] implement changes in design views  - see below (eric)
- [x] review application view (everyone)
- [x] change case status general to general docket and set font to 14px bold (will)
- [x] change format of served status in success alert to match the docket record (12/11/18 9:50 AM) (will)
- [x] add time to docket status after send (will)
- [x] hide sendtoirs button after sent the first time
- [x] Change font of general docket button so the padding issue goes away. Talk to Natalie if you have questions.
- [x] Ensure anchor back up to top with success message works. 
- [ ] move payment expando above the tabs

 ## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x ] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version

**Comment by sarahridgway** [comment]
Step 1 - Not Validated 

![Send to IRS 1.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/a0d51a84-7fa2-4498-b150-e478d0245076)

* Three check boxes are not checked
* Send to IRS button is disabled

Step 2 - Validated

![Send to IRS 2.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/2488841e-69a6-4d9e-b0e9-772b60e03879)

* All three check boxes are checked (required)
* Send to IRS button is enabled

Step 3 - Sent to IRS

![Send to IRS 3.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/78ab9224-40a5-49b7-bcd1-863624f157e2)

* Send to IRS button has been clicked
* Success message appears: Line 1 = "Successfully sent to IRS" Line 2 = "[date stamp] at [time stamp]"
* Case Status flag has been changed to "General Docket"
* Action Required column and check boxes have been removed
* Status column changes from "New" to "R Served on [date stamp] [time stamp]" where R stands for "Respondent"
* Username of sending user has been recorded with the date and time stamp but is not displayed on UI
* Send to IRS button has been removed

Ping me with questions!

cc @JessicaMarine @sadlerw

**Comment by sarahridgway** [comment]
Updated to removed disabled send button spec - not needed.

**Comment by sarahridgway** [comment]
Updated the spec after talking to Will. (1) in above line items denotes a change. 

Changes:

**All checkboxes are checked**
All available check boxes should be checked before clicking the "Send to IRS" button. If none or only some of the boxes are checked, the system will present a pop up error message consistent with behaviors which have already been implemented. Per Will, USWDS advises against disabling buttons until requirements have been met. Error message wireframe not required.

**Success message: Line 1 = "Successfully sent to IRS" Line 2 = "[date stamp] [time stamp]**
Removed "at" between date stamp and time stamp for ease of coding. Updated wireframe not required.

**Action Required column stays in table but has been cleared**
Action Required column will stay but checkboxes and "validated" text will be removed. Will and I agreed that the column should stay for several reasons 1) it's good practice not to remove things from the screen (the Send to IRS button will be an appropriate exception 2) the column is reusable and 3) it would take time to remove it. Updated wireframe not required.

**Status column changes from "New" to "R Served on [date stamp] [time stamp]"**
Removed "at" between date stamp and time stamp for ease of coding. Updated wireframe not required.


I think that covers it! @sadlerw feel free to note anything I missed!

cc @JessicaMarine

**Comment by dknesek** [comment]
@sarahridgway If the user selects the 3 "validated" checkboxes and immediately clicks "Send to IRS" what happens? Does the record get saved then sent? They don't have to click "save" first, right?

If it gets saved then sent, do we see two messages, first a confirmation that the case was updated followed closely by "Successfully sent to IRS..."?

**Comment by JessicaMarine** [comment]
@sadlerw @uxforgood @klohman  

My comments on #110 are:
1.  The Taxpayer doesn't need to see the case status.  There seems to be a new column on the table on the Taxpayer's dashboard that needs to be removed.
2.  The "Validate" buttons should disappear after the Petitions Clerk successfully sends the documents to the IRS. 
3.  The case status should be "General Docket".  It is only showing as "General".

Thanks!  Jessica

**Comment by sarahridgway** [comment]
@JessicaMarine Do we need to display the time on either the success message or within the docket record table? Right now I think we have date and time.

**Comment by uxforgood** [comment]
@dubharmonic here are the updated designs for the petitions clerk send to IRS. (The send to IRS button will move to another screen, once we build that screen, but for now it's ok)

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/900d3342-0b3f-4477-9199-56bc4656d9a4)

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/4c2a2e32-f046-47dd-9631-7d3c0f1951d5)


And for reference, here's what the "Case info" tab looks like after filing fee is paid (for design reference only - not intrinsic to the function of this user story) 

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/55161c16-a979-4436-9c94-195340cb49c3)

**Comment by kkoskelin** [comment]
![image](https://user-images.githubusercontent.com/2445917/49748773-450dcd00-fc6c-11e8-815f-745c07ad8cb8.png)
Accessibility testing using Safari + VoiceOver (and keyboard) is complete with one caveat above.  Attempting to open PDFs currently will generate a "blocked popup" message in both Chrome and Safari.  It is important to note that the current method of opening PDFs in a new window is going to be changing in the near-future, rendering this issue moot.  However, if it is of great concern, we could discuss possible solutions.  
cc: @JessicaMarine
