### ISSUE TITLE
IRS Attorney: File Answer (1.5)

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#111]
As an IRS Attorney, in order to comply with Court rules and have the case proceed, I need to file an Answer. 

By Court rule, the IRS must file an Answer within 60 days of receiving a Petition.  When the IRS Attorney is ready to file an Answer, they access the system, search for case by Docket #, and then upload the Answer. 

## Pre-conditions:
* IRS Attorney is defined user in the system.
* IRS Attorney can access the system.
* IRS Answer is saved as PDF.
* IRS Attorney knows the docket # of the case.
* IRS Attorney can search for the case by docket #.
	
## Acceptance Criteria (Post-conditions):
* The system knows that the user is an IRS Attorney.
* The IRS Attorney information (all information) assigned to the case can viewed by all parties and internal court users
* Answer is saved in the system.
* Answer is associated with the correct case (Docket #).
* The date of filing the Answer is captured as metadata
* IRS Attorney and Petitioner can view a record (the PDF) of the filing in the system in the correct case.
* Case (docket #) is now associated with that IRS Attorney and appears on the IRS Attorney Dashboard

## Tasks
- [x] Design the Upload Screen, and IRS Attorney Dashboard (design team)
- [x] Create IRS Attorney Dashboard View (Kris, Eric)
- [x] Create IRS Attorney Case Detail / Document Upload View (Eric)
- [x] Create IRS Attorney user (Name and Tax Court Bar Number)
- [x] Add drop-down for answer document
- [x] Create sequence for upload
- [x] create use case and use case proxy (cody/will)
- [x] Create Lambda (will/cody)
- [x] refactor case to use document entities (will)
- [x] add irs attorney (respondent) info to design of views (kristin)
- [x] add irs attorney (respondent) info to database/backend (cody)
- [x] modify view to show petitioner and respondent info per design and integrate with backend (will)
- [x] add new specs (eric)
- [x] design tweaks (eric)
- [x] add bar number on respondent info (will)

 ## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version

**Comment by klohman** [comment]
@JessicaMarine We explored two options for the document type selection. 

The user will start with one dropdown populated with the top level document categories. This includes a type-ahead feature to bring them immediately to a specific category and a scroll. 

![Modal- Progressive Dropdown.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3127244e-f011-410a-9e7b-2a8c2eeabe86)


![Screen Shot 2018-12-05 at 5.05.42 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d4551b07-52d8-485e-b2ca-c1bd6a6f9624)

Based on the input into the first dropdown, a second dropdown displays populated with documents within the selected category. This is also searchable with a type-ahead feature and would include a scroll.  

![Modal- Answer Type.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/99123679-1e94-4f73-8605-d276c1d6bd9f)

Depending on the taxonomy, we can group documents under a second level category (showing the second category in blue here). 

![Screen Shot 2018-12-05 at 5.05.51 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0ddcb7dc-b250-4e94-9ba8-7f8cf87731fb)

**Comment by klohman** [comment]
@JessicaMarine  Another option for the document selection. 

All documents are presented in a single dropdown- organized into a tree structure. 

![Screen Shot 2018-12-05 at 5.09.12 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/920e9b4d-d20e-4832-ac66-cc0fff3330dd)

When a user selects a top level category, the tree expands to show the documents within that category. The dropdown would also have the type-ahead search feature and scroll. 

![Screen Shot 2018-12-05 at 5.09.20 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/83961004-28fd-4c0c-8f81-cf335b050bdc)

**Comment by uxforgood** [comment]
@JessicaMarine @dubharmonic 

Here's what we have for the beginning of the file answer workflow. Basically the case detail page (using the new updated designs) that includes the "File document" button. 

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/875e3fed-6c83-4427-94bb-acb4de2c5f02)

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/2688f4a5-235e-41bc-9328-1c0bb2d52752)

The below link shows you the tabbed view of the case detail page for IRS attorneys. On the right there should be a tab to show you the CSS output of this page, which should help in the UI dev.

https://www.figma.com/file/Z2MXE2BHNyNKK8rILSWkLCAX/USTC-For-devs
 

Here is also a crudely annotated version of our current design to show you what's changing 

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/dae28767-a6d8-4b8e-989b-d2fa5c67b7b9)

**Comment by klohman** [comment]
@JessicaMarine @dubharmonic @uxforgood @sarahridgway 

Forgot to go over this during the design review. Here is a mockup of the IRS Attorney dashboard (after they have answered the case). 

This is the same as the Petitioner Dashboard - the notifications column was something we talked about a couple sprints ago and would include the "Action required" if there were items pending. 

![IRS Attorney- Dashboard.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8c6696cb-8a9b-413d-abe2-cb95d6d11429)

**Comment by JessicaMarine** [comment]
I am fine with this view.  And the cases (as they add more) should show in oldest to newest order.

We can talk about this more at tomorrow’s design meetings, but I think the notifications should be party specific.  For example, if a Taxpayer needs to pay a filing fee, the notification flag on that case should only show on the Taxpayer’s view, not the IRS view.  But that may be too difficult.  Let’s discuss.

**Comment by uxforgood** [comment]
@dubharmonic @JessicaMarine 

https://app.zenhub.com/workspaces/ef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/111#issuecomment-444673635

Has been updated with correct screenshots based on this morning's feedback.

**Comment by uxforgood** [comment]
@dubharmonic @JessicaMarine 

1. To file an answer, the attorney would click the "File answer" button from case detail page and see this: 

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/0f055076-c9ea-4ab4-aae5-95a820069c0a)

2. They select document type (for now only 2 options are "Answer" and "Stipulated decision" and upload doc. 
3. "Cancel" returns them to the case detail page
4. "Upload" uploads the file, returns them to case detail page with success message and new line item showing answered filed in the docket record at the bottom

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/587cfad9-8028-4c4d-be28-3e154e2ea8b2)

**Comment by klohman** [comment]
@JessicaMarine @dubharmonic 

Mockups for public view case detail. 

![Public Case Detail - Default.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4694e67b-a577-463a-8449-458a33daee32)

![Public- Case Detail -Info.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ecf7e61b-adae-4ec5-ba0e-148202d3422e)

**Comment by JessicaMarine** [comment]
Looks good! Thanks.

**Comment by klohman** [comment]
@JessicaMarine @dubharmonic 

Updated IRS Dashboard design and Case Detail - Case Information Tab (IRS Attorney View) 

![IRS Attorney- Dashboard.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/483cf222-f082-4f38-b0eb-5c711f501a06)

![MVP IRS Attorney- Case Detail -Info.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/85d2bd64-dcc7-464a-bb70-9d41ced67e59)

**Comment by klohman** [comment]
@sadlerw @JessicaMarine @dubharmonic @uxforgood 

Updated Case Detail- Case Information tab with IRS data
(We are only showing Petitioner Name right now, so I'm sure the location of the Respondent info may move slightly once we add more metadata visible on this screen.)
![Screen Shot 2018-12-11 at 11.16.13 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c929c4c7-a39f-4022-aa5e-4c6beb92a797)

**Comment by mariahkannenberg** [comment]
Design Decisioni 12/11: Hold off on public view until we have done the metadata work in Scenario #2. Could be the last user story in the scenario. There's nothing that the public WOULD see that the court wouldn't. Essentially, we're just "toggling off" certain data points.

**Comment by JessicaMarine** [comment]
Kristen,

I was thinking that it would display something like:

Respondent
IRSAttorney (TT66554)
123 Main Street
Los Angeles, CA 98089
202-444-8988
Attorney@irs.gov

**Comment by JessicaMarine** [comment]
Looks good!
