### ISSUE TITLE
Petitioner: Submit new case to Court

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#126]
As a Petitioner, in order to officially start my case at the Court, I need to submit my case to the Court.

After Petitioner has uploaded all of the PDFs and entered all required personal information (name, address, phone, TIN, etc.), Petitioner submits/transmits the new case to the Court.  At the time of submission, the system should generate a docket number and case caption for the case.  The system should also generate a case record where all of the case information and filings are accessible.  

## Pre-conditions:
* Petitioner’s personal information (name, address, phone, TIN, etc.) is complete
* Petitioner has uploaded the three PDFs (Petition, Request for Place of Trial, Statement of Taxpayer Identification Number)

## Acceptance Criteria:
* The system generates a docket number.
* The system generates a case caption.
* The system generates a case record.
* Case status is set to "New Case"
* Petitioner can see the docket # associated with the case.
* Petitioner can see the caption created with the case. 
* Petitioner can see a record of the Petition in the system in the correct case. 
* Petitioner can see a record of the Request for Place of Trial in the system in the correct case. 
* Petitioner can see a record of the STIN in the system in the correct case.

## Notes:
* Petitioner's personal information will likely be populated during the account creation phase, so this assumes that this information is already captured by the system.
* The docket # is formatted as 00101-18.  First part goes from 101 to 99999, last 2 digits are year case created.  The docket number includes the next sequential number from the previous. (There may also be a suffix applied after the year due to case type, but that will be in another story)
* Caption should populate as "[First Name] [Last name], Petitioner v. Commissioner of Internal Revenue, Respondent" 

## Tasks
- [x] Design UI for Case Summary view (Kristen)
- [x] Design UI for Case Detail view (Kristen)
- [x] Responsive table (Eric & Kris)
- [x] Code Case Summary view (Eric & Kris)
- [x] Code Case Detail view (Eric & Kris)
- [x] Create endpoint to create a case in dynamo (will/cody)
- [x] define REST API (will)
- [x] Create Lambda to create docket number (cody/will)
- [x] Create front-end service layer to talk to the back end for case detail and case listing by user (kris/eric)
- [x] Create end-to-end tests covering petitioner workflow (kris)
- [x] Add changes for accessibility where appropriate for keyboard/voiceover (kris)
- [x] Create pre-signed URL endpoint for GET document (will/cody)
- [x] Create endpoint to GET cases by user (will/cody)
- [x] Create endpoint to GET case by case ID
- [x] Create endpoint to GET document meta data by case ID (will/cody)

 ## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version

**Comment by JessicaMarine** [comment]
Sample docket record:

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/7261e664-4956-4e0a-bc34-f6e56f6fc710)

**Comment by klohman** [comment]
Dashboard view - showing success message from petition form upload. 
- Docket # is hyperlink to Case Detail page ![Petitioner_Dashboard_VIew Cases.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2fecdf1e-f543-4758-83a0-7f9c6d2533f8)

**Comment by klohman** [comment]
Case Detail page 
- Required actions section - requiring the user to take action- in this case Pay filing fee is only action - action on Pay fee TBD in later story 
- PDF document titles are hyperlinks- on click, opens pdf document 
![Case Detail_View PDFs.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1b2fd3e4-12f1-4436-8445-20f7aad8fc1a)

**Comment by dubharmonic** [comment]
![image.png](https://images.zenhubusercontent.com/583eff35b9dc3c622022bdff/936ecefb-74f3-4087-be5a-350f5695fcb4)

**Comment by sadlerw** [comment]
REST API notes:

/cases POST [{documentId: XX, documentType: XX}] - must be 3 in length  header: Authorization : Bearer <someusername>

/cases GET   header: Authorization : Bearer <someusername>

/cases/<caseid>  header: Authorization : Bearer <someusername>

/documents/policy?type=GET  GET for pre-signed url to GET S3 doc  (this might change)

**Comment by tjcurington** [comment]
https://github.com/flexion/ef-cms/issues/126#issuecomment-436024842
Test Comment

**Comment by klohman** [comment]
https://app.zenhub.com/workspaces/ef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/126#issuecomment-436306331

@dubharmonic For the Dashboard, we want to change the label on the "Date submitted" column to "Date Filed" 

Also, you can remove the "Fee Status" column for now. We will add to this design for #71.

**Comment by kkoskelin** [comment]
![Screen Shot 2018-11-07 at 4.19.32 PM.png](https://images.zenhubusercontent.com/5bbf750502b9b3375461a416/e9f6e728-a79b-484b-a41b-339a6b096dbc)
@klohman

**Comment by JessicaMarine** [comment]
@sadlerw Just initial comments on this story:
1.  There is no status on the case detail page. I believe I discussed a "New" tag with @klohman 
2. The caption is formatted oddly.  Can we use a test case of First Name Last Name so that it populates correctly.
3. Ordering of docket numbers/cases on the Dashboard seems to lack logic.  When I started a new case, it populated somewhere near the middle of the list and it was not obvious is was the newly created case.
4. The naming of the documents in the case detail page has weird upper/lower case text.  It should be "Petition", "Request for Place of Trial", and "Statement of Taxpayer Identification Number"

**Comment by uxforgood** [comment]
@JessicaMarine 

For the ordering, I mentioned this to @dubharmonic a couple days ago. What logic makes the most sense here? Newest case at the top? Bottom? After adding a case, I'd think you'd want to see it added to the top. But coming back to work cases, seeing the oldest first may make sense (for practitioners, etc). 

We can push the logic decision until we get into the practitioner stories, since they are the ones this most pertains to.

**Comment by JessicaMarine** [comment]
I like the proposed approach: A new case would be added to the top. But coming back to work cases, seeing the oldest first may make sense (for practitioners, etc).

**Comment by klohman** [comment]
I noticed some minor design things
- Spacing between the page title- Dashboard- and table label - Cases- should be increased. We may even be able to decrease the space between the header and the page title. 
- Spacing on the Case Detail page for the table label and the table itself should be decreased
- the expanded accordion should have a border- I don't see it on my screen - 

none of these are related to the functionality (other than general readability) so i'm not sure if they are that important to fix at the moment- just noting it down.

**Comment by klohman** [comment]
Updated design - with "Action Required" flag 

![2.1 Petitioner_Dashboard_VIew Cases.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8c4eb089-fbbf-4b82-a4b9-8d0cc341fda7)
