### ISSUE TITLE
Intake Clerk: Search for case by Docket # to associate pay.gov filing fee ID with case

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#127]
As an Intake Clerk, in order to make sure that the pay.gov filing fee ID is associated with the correct, I need to search for case by Docket #.

The Court receives a report from pay.gov each day that lists all of the cases in which a filing fee has been paid through pay.gov (sample of report attached).  The cases are referenced by Docket #.  An Intake Clerk needs to be able to search for the case by Docket # and enter the pay.gov filing fee ID to indicate that the filing fee has been paid.

## Pre-conditions:
* Intake Clerk is logged into the system 
* Petitioner has paid fee through pay.gov 
* Payment has been associated with docket # in pay.gov 
* Intake Clerk has received filing fee report from pay.gov and has filing fee ID with associated docket # 

## Acceptance criteria:
* System knows that the user is an Intake clerk
* Intake Clerk can access case through docket # search 
* Internal Court users can access case through docket # search (non-permission based)
* Intake Clerk can enter pay.gov filing fee ID within the case
* Petitioner can access the system and see that the Court has confirmed the filing fee payment through pay.gov but not change the status (view only not edit)

## Notes: 
* USDS does not have type ahead (Natalie to research)

## Tasks:
- [x] add intake clerk to available users (Eric)
- [x] backend docketnumber find endpoint /cases/XXXXX-XX (will)
- [x] design where docket number search goes in views (Kristen)
- [x] implement design (add docket number search to header on dashboard until design complete) (Eric)
- [x] add search value to cerebral state (Eric & Kris)
- [x] implement updateSearch sequence (Eric & Kris)
- [x] implement submitSearch sequence [getCase, setCase, showCaseDetail] (Eric & Kris)
- [x] implement padding and shortening of docket numbers in HTML (Eric & Kris)
- [x] design view for adding pay.gov filing id to case for internal users (Kristen)
- [x] Design view for viewing pay.gov status for any public users (kristen)
- [x] implement input on case detail for adding pay.gov filing id to case

 ## Definition of Done:
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version

**Comment by sadlerw** [comment]
[Pay.gov report.pdf](https://github.com/flexion/ef-cms/files/2550515/Pay.gov.report.pdf)

**Comment by klohman** [comment]
Mockup design for search bar in header.
At this stage, search is by docket number only.  on click of search, if there is exact match, display the Case Detail page for the matching docket number.  

![Screen Shot 2018-11-21 at 1.55.41 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/87ace0ec-7254-4593-bfdb-a4a566eca645)

**Comment by klohman** [comment]
Re: design view for adding pay.gov filing id to case for internal users

Case Detail includes new "Case Information" section with Petition Fee field. 
Petition Fee field includes radio button (unselected by default) 


![Petition Clerk - Paid Field.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/00057ab6-aca7-452a-b87a-5d81721fa798)

**Comment by klohman** [comment]
On select of Paid by Pay.gov radio button, display Payment ID field. User can enter payment id, and click the "Save" button to apply changes. 

![Petition Clerk - Enter Payment ID.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7a374f97-3cdf-47d3-ba36-b49e869afb01)

**Comment by klohman** [comment]
On save, display success message. Petition Fee field is read-only, displaying the payment method (Paid by Pay.gov) and payment ID fields. 

![Petition Clerk - Enter Payment ID-1.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3e67d356-0268-4e89-9aae-e3001f1589e3)

**Comment by dubharmonic** [comment]
Design review tasks
- [ ] Remove case validation 
- [ ] Remove update to general docket
- [ ] Add row to table with "Filing fee paid"

**Comment by kkoskelin** [comment]
There will be one additional pull request filed by EOD Friday which will provide jsdoc for new js functionality present in this story.
