### ISSUE TITLE
Petitions Clerk: Validate Petition (1.3)

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#128]
As a Petitions Clerk, in order for the case to proceed, I need to validate the Petition.

Pre-conditions:
* A complete petition (3 PDFs) is saved in the system.
* Petitions Clerk is logged into the system.

Acceptance Criteria
*  The system knows that the user is a Petitions Clerk.
* Petitions Clerk can see within the system that the petition is ready to be validated (work queue - keep it simple until we have more user research)	
* Petitions Clerk can view each of the three PDFs in their browser		
* Petitions Clerk validates each individual petition document
* Case status automatically changes to "General Docket" status

## Tasks
- [x] Design the Petitions Section "Work Queue" (kristen)
- [x] Design the validation per document on the "Case Detail" view (kristen)
- [x] Design how to change the case status to "General Docket" (kristen)
- [x] Implement the Petitions Section "Work Queue" view on the front end (eric/cody/will)
- [x] Implement the "Case Detail" view (cody/eric)
  - [x] put pdf into iframe
  - [x] link up the checkboxes as per design (float: right)
- [x] Create end-to-end tests covering petitioner workflow (kris)
- [x] Add changes for accessibility where appropriate for keyboard/voiceover (kris)
- [x] Implement the individual document validation in the view (cody / eric)
- [x] Create endpoint to GET all cases in "New" status (will/cody)
- [x] Create endpoint to PUT the case to "General Docket" status (will/cody)
- [x] Create endpoint to PUT each document as validated (will/cody)

 ## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version

**Comment by sadlerw** [comment]
[Pay.gov report.pdf](https://github.com/flexion/ef-cms/files/2550512/Pay.gov.report.pdf)

**Comment by klohman** [comment]
Petition Section Work Queue mockup here:  
@JessicaMarine @uxforgood @dubharmonic @kkoskelin 

![Petition Section Queue.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/accb6ad4-6f61-496f-8a65-afb7eb2b9643)

**Comment by JessicaMarine** [comment]
This looks good to me so far, but please remember it is Petitions Clerk.  Also, there should be a “status” field somewhere on this case detail page.  It should be “New” before those documents are validated, and then change to “General Docket” after validation.

Jessica

**Comment by JessicaMarine** [comment]
This look okay to me so far.  I think the “Date filed” should just be “Date”…and that date is the date that item made it into this work queue, not necessarily the date of filing something.  It could very well be that for new Petitions those two dates are always the same, but it will not be for other court user’s work queues.

**Comment by klohman** [comment]
Updated Petitions Section Work Queue 
@dubharmonic ![Petition Section Queue.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d7dc6e5f-6df2-447d-8962-5e1c5dab54aa)

**Comment by klohman** [comment]
Updated Petitions Clerk Case Detail view 
![Petition Clerk - Case Detail.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d9202b8c-6826-414e-abcf-d787bf00b9ea)

**Comment by uxforgood** [comment]
@JessicaMarine 

"and that date is the date that item made it into this work queue, not necessarily the date of filing something. "

So are you thinking that for each work queue, the date that appears for that user is the date it was added to the work queue? 

Is there value in showing a consistent date throughout the system to users in these views? I know in some of the interviews, folks pull the "oldest" first. And I could see cases where a newer case might have been sitting in a work queue for longer than an older case because that older case was bounced around a bit between sections etc. 

Let's chat about this at our next design huddle maybe!
