### ISSUE TITLE
High priority indicator for internal messages (manual)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1432]
As a Court user, in order to easily identify items that are high priority and need immediate attention, I need a high priority indicator on certain messages in my work queues. 

There are over 100,000 messages that flow through the Court's work queues/inboxes throughout the year.  As those messages are being created, there needs to be the ability for some of them to be marked as high priority so that the Court employee knows which ones need immediate attention. For internal users, they should have the ability to manually set a message they are sending to another internal user as high priority.  That way, the message appears on the recipient's inbox as high priority. 

We would like a way to flag messages as "high priority", and for messages marked as high priority to indicate as such in Section and User internal message inboxes. Additionally, high priority messages should be automatically displayed at the top of the Section and User internal message inboxes.

## Acceptance Criteria:
* User has the ability to manually set a message they are sending or replying to as high priority
* User has the ability to manually unset a message they are sending or replying to as high priority
* High priority messages should appear at the top of a user or section inbox and should be displayed oldest->newest
* Messages marked as high priority are easily distinguishable as such
* This applies across all user roles/groups

## Notes:
* Message priority has no connection with case priority

## Definition of Done
**Product Owner**
 - [ ] Acceptance criteria have been met

**UX**
  - [ ] Usability has been validated

**Engineering**
  - [ ] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [ ] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [ ] No errors reported in manual a11y testing
  - [ ] All new functionality verified to work with keyboard and osx voiceover
  - [ ] Code refactored for clarity and to remove any known technical debt 
  - [ ] README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [ ] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [ ] Library/module dependencies are up-to-date and are at the latest resolvable version [Note:  5/6/19 - Court granted permission for a 30-day exception for the `tar` library]
  - [ ] Code is deployed to DEV
  - [ ] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [ ] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by sarahridgway** [comment]
*Setting a Message to High Priority*

* User clicks on check box to set a high priority flag on the message

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/ac3f2179-7c48-46c1-93e1-c08070c3e70b)

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/3d7b4e2e-9466-4b5e-8ca6-c24beac5ed7c)

*High Priority Indicator on Message*

* High priority indicators never expire

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/3dc17ad9-086b-47ff-a858-fe0d9cc6e7e1)

**Comment by sarahridgway** [comment]
*High Priority Indicator on Pending Messages List*

* High priority indicator never expires

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/2f12fab5-173c-4607-bce4-11a9320a006c)

**Comment by sarahridgway** [comment]
*High Priority Indicator in Messages Queue*

* High priority indicator never expires
* Unread and read messages set to high priority in all queues (my messages, section messages, and both sent queues) always show high priority indicator

MY MESSAGES

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/5bd65c7c-70c4-4e04-b5e3-15a80d37b30e)

MY MESSAGES - SENT

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/beda584a-94d9-4574-a062-b05caf229784)

SECTION MESSAGES

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/243ab00c-da98-4755-a39f-a1380efe51e9)

SECTION MESSAGES - SENT

*High Priority Indicator in Message Queues - Hover State*

* On hover, set row bg to hover state

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/917bc7bf-7cc3-4184-8fb2-434fdc5d85b6)

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/0d413e78-0fed-42eb-b03e-d23ce431e45d)
