### ISSUE TITLE
Upgrade to USWDS 2.0

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1652]
As a development in order to make sure that all styles are consistent across the app, we need to updates styles wherever they're not consistent. 

## Acceptance Criteria
* All styles are consistent throughout the site. 

## Notes
* These changes are for pre-USWDS changes and to ensure style classes are consistent throught the site before the update takes place; with the exception of the header, which will be updated to 2.0 classes. 

## Tasks
- [x] 1) Update inconsistencies in Start a Case Flow (Joe) 
- [x] 2) Update inconsistencies in File a Document Flow (Rachael)
- [x] 3) Update header w/2.0 classes (Matt)
- [x] 4) Update inconsistencies on Case Detail Page (William)
- [x] 5) Update inconsistencies on Document Detail and in Modals (Kris)
- [x] 6) Update inconsistencies in Dashboards (Eric)
- [x] 7) Review changes with engineering (Kristen)
- [x] 8) Update labels (Eric)
- [x] 9) Request Access to Case (Rachael)
- [x] 10) Add Docket Entry (Joe)

**Comment by klohman** [comment]
@rachaelparris @ericsorenson 

**Case Detail - Docket Record**
- Practitioner role (when not assigned to case) - Sort option should be moved to the right side of table 
- Petition Clerk role - Sort option should be moved to the right side of table 
- Senior Attorney role - Sort option should be moved to the right side of table 
- Petition Clerk role - Should have “Add Docket Entry” button 

**File Document Form**
-  Upload Your Document filed when in read-only mode 
    - Should be 10px spacing between field label and helper text (15px on dev) 

- Upload Your Supporting Document field 
    - Should be 10px spacing between field label and helper text (15px on dev) 

**Work Queue / Dashboard**

Petition Clerk 
- Hover state on work items - blue bar is too wide on Inbox 
- Sent box - Batched for IRS icon is wrong color- should be #FDB81E
- Inbox - Recalled items are not displaying the icon

**Comment by klohman** [comment]
**Petitioner Dashboard**
- Need more vertical space between header and page title H1 - Add to design story

**Before you begin**
- Ellipse in H1 needs to be bottom aligned - fix in 1662
- Text is stretching full width - fix in 1662

**Start a Case**
- Blue containers for each section should stretch to full width (aligning with profile icon on right) - add to 1664
- Upload fields - seems like the entire field, including the label is a hotspot- when I clicked on the field label the file upload window keeps displaying. 
- Field labels  (all)- font-weight appears to be bold - should be semi-bold - fix in 1664
- Party types 
    - Need more padding above the second level questions (i.e. Is the spouse deceased? , etc.)
- Mailing Address - remove Address Line 1 label - fix in 1664
- Email address - alert-hint icon size is different from the other uses (should be 20px) - fix 1664
- Phone Number field label needs padding below 
- Type of Notice/Case field
    - Fix spacing (needs padding above label 
    - Field is stretching full width- should be same width as other fields 
    - Too much space between this field and Date of Notice (should be total of 30px)
- How is a small case different than a regular case - accordion 
    - Icon size is too large - should be 15px 
    - Too much vertical space below the text within the 4 cards 
    - Should be space between the 4 cards 
- Select a Trial Location - fix width on field to align with other fields 

- Errors
    - “Your Petition file size is empty” - this should not be displayed (not sure about the intention of this) 
    - Too much vertical space between field and error message 
    - Error messages are running into the next field labels - need to retain padding 
    - Date of Notice error message is incorrectly placed - displaying to the right of the field
