### ISSUE TITLE
Trial Session: Make case list and session-related notes permission based

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1685]
As a Judge, in order to make sure only the necessary people see the case-related notes and session-related notes that I make, I need them to be viewable by me and anyone in my Chambers.

## Pre-Conditions
* Session-related logistical notes created (#1281 - DONE)
* Case list level notes created (#1280 - DONE)
* All users have been loaded into system (#1948)

## Acceptance Criteria
* Session-related and case list level notes are viewable to anyone in the Judge's chamber

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Discuss with team the technical complexities with making permissions field level vs. page level, group level vs individual, etc.

## Definition of Done (Updated 8-28-19) DOING DOD AS PART OF #1948
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [ ] Automated test scripts have been written
- [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Code refactored for clarity and to remove any known technical debt 
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by mariahkannenberg** [comment]
Being handled in #1948. Closing story.

**Comment by matthopson** [comment]
https://github.com/flexion/ef-cms/pull/3423 Addresses this issue.

**Comment by klohman** [comment]
## Test Scenarios (moved from #1948)

### 40) View cases in trial session assigned to me (STOPPING POINT Friday 10/25) 
* Login as [user] 
* Navigate to trial session 
* View Judge’s Working Copy list of cases
Expected results 
- [x] Petitioner does not see trial sessions in navigation 
- [x] Practitioner does not see  trial sessions in navigation 
- [x] Respondent does not see trial sessions in navigation 
- [x] Clerk of the Court does not see Judge’s Working Copy 
- [x] Petitions clerk does not see Judge’s Working Copy  
- [x] Docket clerk does not see Judge’s Working Copy 
- [x] calendar clerk does not see Judge’s Working Copy  
- [x] ADC does not see Judge’s Working Copy 
- [x] Trial clerk does not see Judge’s Working Copy 
- [x] General user does not see Judge’s Working Copy 
- [x] Judge sees Judge’s Working Copy 
- [ ] Chambers sees Judge’s Working Copy 

#### 41) Add/ edit/ delete note on trial session / View session notes 
* Login as [user]
* Navigate to trial session 
* Navigate to Judge’s Working Copy 
* Add session note 
* Edit Session note
* Delete session note 
Expected results 
- [x] Petitioner does not see trial sessions in navigation 
- [x] Practitioner does not see  trial sessions in navigation 
- [x] Respondent does not see trial sessions in navigation 
- [x] Clerk of the Court does not see Judge’s Working Copy 
- [x] Petitions clerk does not see Judge’s Working Copy  
- [x] Docket clerk does not see Judge’s Working Copy 
- [x] calendar clerk does not see Judge’s Working Copy  
- [x] ADC does not see Judge’s Working Copy 
- [x] Trial clerk does not see Judge’s Working Copy 
- [x] General user does not see Judge’s Working Copy 
- [x] Judge sees “Add Session Note” button 
- [x] Judge sees” Edit Session Note” button 
- [x] Judge views session notes 
- [x] Judge sees “Remove session note” button 
- [ ] Chambers sees “Add Session Note” button 
- [ ] Chambers sees” Edit Session Note” button 
- [ ] Chambers views session notes 
- [ ] Chambers sees “Remove session note” button 

#### 42) Add/ edit/ delete note to a case / View case notes 
* Login as [user]
* Navigate to trial session 
* Navigate to Judge’s Working Copy 
* Add case note 
* Edit case note
* Delete case note 
* Navigate to Case Detail 
* View Case Note 
Expected results 
- [x] Petitioner does not see case notes on Case Detail 
- [x] Practitioner does not see case notes on Case Detail 
- [x] Respondent does not see case notes on Case Detail  
- [x] Clerk of the Court does not  see case notes on Case Detail 
- [x] Petitions clerk does not see case notes on Case Detail  
- [x] Docket clerk does not see case notes on Case Detail  
- [x] calendar clerk does not see case notes on Case Detail  
- [x] ADC does not see case notes on Case Detail  
- [x] Trial clerk does not see case notes on Case Detail  
- [x] General user does not see case notes on Case Detail  
- [x] Judge sees “Add Note” button on Working Copy
- [x] Judge sees” Edit Note” button on Working Copy
- [x] Judge views case notes on Working Copy
- [x] Judge sees “Remove note” button on Working Copy 
- [x] Judge sees “Add Note” button on Case Detail
- [x] Judge sees” Edit Note” button on Case Detail
- [x] Judge views case notes on Case Detail
- [x] Judge sees “Remove note” button on Case Detail 
- [ ] Chambers sees “Add Note” button on Working Copy
- [ ] Chambers sees” Edit Note” button on Working Copy
- [ ] Chambers views case notes on Working Copy
- [ ] Chambers sees “Remove note” button on Working Copy 
- [x] Chambers sees “Add Note” button on Case Detail
- [ ] Chambers sees” Edit Note” button on Case Detail
- [ ] Chambers views case notes on Case Detail
- [ ] Chambers sees “Remove note” button on Case Detail 

#### 43) Download case documents for a trial session 
* Login as [user] 
* Navigate to trial session 
* Navigate to Judge’s Working Copy 
* Click Download All Cases button 
Expected results 
- [x] Petitioner does not see trial sessions in navigation 
- [x] Practitioner does not see  trial sessions in navigation 
- [x] Respondent does not see trial sessions in navigation 
- [x] Clerk of the Court does not see Judge’s Working Copy 
- [x] Petitions clerk does not see Judge’s Working Copy  
- [x] Docket clerk does not see Judge’s Working Copy 
- [x] calendar clerk does not see Judge’s Working Copy  
- [x] ADC does not see Judge’s Working Copy 
- [x] Trial clerk does not see Judge’s Working Copy 
- [x] General user does not see Judge’s Working Copy 
- [x] Judge sees Download All Cases button 
- [ ] Chambers sees Download All Cases button
