### ISSUE TITLE
Petitioner:  Indicate that I want to file a petition (1.1.3)

### ISSUE THREAD

**Issue by tjcurington** [flexion/ef-cms#19]
As a Petitioner, in order to file a Petition online, I want to indicate that I want to file a petition with the court.

## Pre-conditions:
 * Petitioner is logged in.
 * Petitioner is at the location where they can select an option to file a petition.

## Acceptance Criteria (Post-conditions):
* Petitioner is able to start filing a petition.

## Tasks
- [x] Design user interaction for case initiation - UX Design
- [x] Code case initiation user interface

## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version

**Comment by uxforgood** [comment]
Sketch of case initiation, with user's name in upper right corner (logged in state) 

@JessicaMarine would the correct text here be to "Create a case" ? 

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/ba064cd6-4c08-4bdb-ab2b-7a773ce6d673)

**Comment by uxforgood** [comment]
@JessicaMarine I like "Start a case." I'm shying away from talking about petition at this stage, since the petition form is part of this, but not the entirety of it. 

I've updated the design above.

**Comment by waldoj** [comment]
To be clear, Jessica, we're gonna test all of this out to see if people understand it, and iterate on the language as is revealed by UX research. You're not settling on the language that we'll definitely be used, but just helping @uxforgood arrive at a starting point.

**Comment by uxforgood** [comment]
As usual, @Waldo is correct. I'm getting at our best guess for language to then test with users. But I like to consider these things carefully where we can, to get as close to right as our guessing can be.  😉
