### ISSUE TITLE
QC Box Cleanup

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#2019]
As a team, so that the Petitions QC functions properly, we need to clean up various items.

## Acceptance Criteria
* Add Filed by column to docket document qc inbox / processed for my and section (TBD)
* Document Titles in Queues should not be truncated; they should wrap
* To: field in paper petition creation message on document messages tab shows "unassigned" but should be the petition clerk who created the petition. The section document QC table under "assigned to" is correct.
* Incorrect counting in headers - there are obviously no items yet it shows 1. Double check counts on all messages/qc tables  
* Doc QC section showing assigned docs as unassigned (docket)
* Create a null state for messages/qc tables

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/4c3da8a7-cf38-4fd4-b6a7-1327aca2feba)

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by sarahridgway** [comment]
* Add Filed by column to docket document qc inbox / processed for my and section (TBD)
* Add Filed by column to senior atty / other user doc qc (TBD)
* Change "Petitioner Name" column header in petitioner / practitioner / respondent case table to "Case Name" 
* Change "Your Cases" table title for petitioner / practitioner / respondent to "My Cases" to match global nav

**Comment by sarahridgway** [comment]
* Consider changing "Add Message" to "Add Note" because these don't go anywhere other than into the log / thread history

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/3e609444-9497-4b7e-ab8d-d4a3f9473d27)

**Comment by mariahkannenberg** [comment]
Found during sprint review prep on 7/1/19

Document name not concatenating in document queue (individual and section) 

![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/e220edf7-b7e0-4c0d-ac36-ae9fc96ae2ed)

**Comment by uxforgood** [comment]
- [ ] Incorrect counting in headers - there are obviously no items yet it shows 1. Double check counts on all messages/qc tables 

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/4c3da8a7-cf38-4fd4-b6a7-1327aca2feba)

**Comment by klohman** [comment]
Completed / No longer relevant 

~~Change "Petitioner Name" column header in petitioner / practitioner / respondent case table to "Case Name"~~

~~"Add docket entry" form has a random 0 at the end of the form after parties checkboxes~~

~~Petitioner dashboard table and case detail tables don’t match~~
~~Unexpected error when filling out a paper document QC, invoked by clicking out of a field and into a field? Entering data in a field and then deleting?~~

???Add fade under tabs on QC screen to ease transition??

**Comment by matthopson** [comment]
Note regarding two items:
- Incorrect counting in headers - there are obviously no items yet it shows 1. Double check counts on all messages/qc tables
> This was addressed in a previous PR: https://github.com/flexion/ef-cms/pull/2325
- Doc QC section showing assigned docs as unassigned (docket)
> Could not reproduce

**Comment by alsmith1** [comment]
## Test scenarios

#### Scenario 1 - null state for messages/QC tables
1. log in as petitions clerk
2. navigate to My Document QC
3. If there are no messages in inbox null message should display
4. Switch to Section Document QC
5. If there are no messages in inbox null message should display

Expected result
- [ ] if there are no messages in My Document QC "There are no messages" should display
- [ ] if there are no messages in Section Document QC "There are no messages" should display
