### ISSUE TITLE
Petitioner:  Upload my existing PDF documents (1.1.5)

### ISSUE THREAD

**Issue by tjcurington** [flexion/ef-cms#21]
As a Petitioner, in order to file a Petition online, I want to upload my existing PDFs (Petition form, Request for Place of Trial, Statement of Taxpayer Identification Number).

## Pre-conditions:
* Petitioner can see how to begin entering Petition information.
* The Petitioner has the Petition form, Request for Place of Trial, and Statement of Taxpayer Identification Number in PDF format.

## Acceptance Criteria (Post-conditions):
* Petitioner’s PDFs are in the system and the Court can distinguish between the three forms.
* Petitioner gets confirmation of successful upload(s).

## Tasks
- [x] Design interface for upload
- [x] Design success interface
- [x] Create route (Eric/Kris)
- [x] Create document policy action (Eric/Kris)
- [x] Create document id action (Eric/Kris)
- [x] Create S3 bucket upload action (Eric/Kris)
- [x] Upload all 3 files with one click (Eric/Kris)
- [x] Upload all 3 files with one click (Eric/Kris)
- [x] Add success message to home screen (Eric)
- [x] add routing sequence (Eric/Will)
- [x] Show progress indicator (Eric)
- [x] Add checks when files have been chosen (Kris/Cody)
- [x] Create document database (cody/will)
- [x] Create S3 database for documents (cody/will)
- [x] Create migration/serverless configuration for the API (will/cody)
- [x] Create endpoint/Lambda for uploading document and metadata (cody/will)
- [x] Create endpoint for secure upload URL (cody/will)
- [x] Fix custom access logging (will/cody)
- [x] Update "File a Petition" labels (kris)
- [x] keep the green checkmark on the same line with the file name when screen is resized (will/eric)

# Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version

**Comment by tjcurington** [comment]
* There is a separate PDF upload function for each of the Petition form, Request for Place of Trial, Statement of Taxpayer Identification Number.

**Comment by uxforgood** [comment]
Sketch of the upload process

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/f593176e-1b54-4d9f-84eb-9cf125fe8a65)


Success message (in alert / slim / success style) 

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/76e42c0e-6bb5-41f3-be61-8be73c619890)

**Comment by dubharmonic** [comment]
Any feedback, @uxforgood @sarahridgway ?

![image.png](https://images.zenhubusercontent.com/583eff35b9dc3c622022bdff/d5493e5d-b048-434c-b155-14d508059011)

**Comment by uxforgood** [comment]
@dubharmonic 

Great start! A couple notes: 

1. The file label above the browse button needs more weight. Let's pair to suss out the best fix for that (I'm thinking it needs to be a heading style, just not sure which). 

2. Can you add the checkmark in a circle icon after the attached file name to further indicate to the user that it's been attached? 

3. "Petition" in the page title should be lowercase (sentence case, not title case whenever possible!)

**Comment by klohman** [comment]
See attached mockup of progress bar. 

On click of Upload button, button remains in active state. Progress bar is shown below with associated text displaying number of uploads remaining. 

![Screen Shot 2018-10-31 at 4.05.46 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f464d307-e6af-40be-8566-05b6ffd1b7f8)
