### ISSUE TITLE
Court User: Ability to track pending motions and other items

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#2156]
As a Court User, in order to know what items are outstanding on a case, I need the ability to quickly and easily see specific pending items.

The Court does not track all documents that are filed/issued in a case.  However, the Court does track specific items -- all motions filed by parties, any Order to Show Case issued by the Court, all Proposed Stipulated Decisions, and any item that Docket/Judge thinks is important enough to track.  As a result, the system should automatically track any motion, Proposed Stipulated Decision, and OSC, and it should allow a Docket Clerk to manually mark something for tracking.  Those items should show up as "pending" within the relevant case, and should also be aggregated in a report.  That report should be able to be filtered by Judge.

## Acceptance Criteria ##
* Any motion filed should automatically be tracked
* Any Order to Show Cause (Code = OSC) should automatically be tracked
* Any Application should be automatically tracked
* Any Proposed Stipulated Decision should be automatically tracked
* Docket should have the ability to manually mark any other filing for tracking
* All "tracked" items should display within the relevant case, as well as be viewable on an aggregated "Pending" report
* The "Pending" report should be able to be filtered by Judge
* Items on the report should display in order by date, oldest to newest
* Pending Report (unfiltered) should be printable
* Pending Report (filtered by Judge) should be printable
* Pending items within a case should be printable
* Docket clerk should have the ability to remove something as pending

## Notes: ##
* This story does not address how to *remove* something from "Pending" -- that will be handled in a different story
* For the Print PDF a few things...
1. From the main report Title should read "Pending Report Unfiltered", when not filtered by judge
2. From the main report Title should read "Pending Report Judge (Enter Name Here) ", when filtered by judge
3. From the Pending report Tab in Docket Title should read Pending Report for Docket (Docket Number)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by alsmith1** [comment]
![Screen Shot 2019-10-30 at 3.17.08 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/69f99891-3be4-401b-a97b-251b91c6ccac)

**Comment by alsmith1** [comment]
## Test scenarios
#### Scenario 1 - Navigation from Reports menu to Pending report
1. Log-in as any internal Court user 
2. Go to the Reports Menu 
3. Select Pending Report
4. Verify columns in the pending report table include: Docket No., Date Filed, Case Name, Document Name, Case status, Judge (associated with case).

Expected result
- [ ] Pending Report displays
- [ ] Verify columns in the pending report table include: Docket No., Date Filed, Case Name, Document Name, Case status, Judge (associated with case).

#### Scenario 2 - All "tracked" items should display within the relevant case
1. Navigate to the docket number of your selected case
2. Click on the pending reports tab next to Deadlines
3. Verify columns in the pending report table include: Docket Entry No., Date Filed, Document Name, Filed by and remove.

Expected result
- [ ] Items in the selected case display on the pending report tab
- [ ] Docket Entry No., Date Filed, Document Name, Filed by and remove columns display on table

#### Scenario 3 - All Order to Show Cause, Proposed Stipulated Decision, and any items Docket clerk may add to track items should display on an aggregated "Pending" report
1. From the Reports Menu Select Pending Report
2. Verify the table includes motions, Order to Show Cause, Proposed Stipulated Decision, and any items Docket clerk may add to track progress on

Expected result
- [ ] Pending Report displays
- [ ] Report displays a list of all Motions, Orders to Show Cause, Proposed Stipulated Decisions,  in all cases system-wide and any items a Docket clerk has manually checked to track progress on

#### Scenario 4 - Items on the report should display in order by filed date, oldest to newest
1. Go to the Reports Menu 
2. Select Pending Report
3. Verify items in table display by filed date oldest to newest

Expected result
- [ ] Pending Report displays
- [ ] Items display oldest to newest by filed date in table

#### Scenario 5 - The "Pending" report should be able to be filtered by Judge
1. Go to the Reports Menu 
2. Select Pending Report
3. Click on the Filter by Judge dropdown and select Judge Buch

Expected result
- [ ] Pending Report displays
- [ ] Only pending items assigned to judge Buch display

#### Scenario 6 - Pending Report should be printable (filtered) 
1. Go to the Reports Menu 
2. Select Pending Report
3. Click on the filter by judge dropdown and select a judge.
4. Click on print report link

Expected result
- [ ] Pending Report displays
- [ ] Printable PDF displays
- [ ] Title of report should display Pending Report - Judge (Judge's Name)
- [ ] Report should display only cases for selected judge
- [ ] PDF can be printed

#### Scenario 7 - Pending Report should be printable (unfiltered)
1. Go to the Reports Menu 
2. Select Pending Report
3. Click on print report link

Expected result
- [ ] Pending Report displays
- [ ] Printable PDF displays
- [ ] Title of report should display Pending Report - All Judges
- [ ] PDF can be printed

#### Scenario 8 - Pending Report from docket page should be printable 
1. Navigate to the docket of your selected case
2. Click on the pending reports tab next to Deadlines
3. Click on print report link

Expected result
- [ ] Pending Report displays
- [ ] Printable PDF displays
- [ ] Title of report should display Pending Report for Docket (Docket Number)
- [ ] PDF can be printed

#### Scenario 9 - Docket Clerk should have the ability to manually mark any other filing for tracking (document edit view) 
1. Navigate to the docket of your selected case
2. Click on the pending reports tab next to Deadlines
3. Click on the checkbox to track document

Expected result
- [ ] User sees the check box and can select it
- [ ] Item is shown on the report table

#### Scenario 10 - Docket should have the ability to remove pending items (docket pending report tab)
1. Log in as a Docket Clerk
2. Navigate to a case's docket and click on Pending Report tab
3.  Click on the remove link from one of the items in the report

Expected result
- [ ] Item selected should be removed from pending report

**Comment by JessicaMarine** [comment]
PO Review 11/18/19:
* The first column of the table `No.` within the Pending Report tab within a particular case.  That No. should match the docket index entry number of the filing, not be a new numbering.  For example, in 103-19, I filed an Entry of Appearance that is Docket Index Entry No. 11, but it shows up on the Pending Report table as No. 1
