### ISSUE TITLE
Court User: Ability to modify case caption/docket number on DAWSON generated orders/notices in Lead Case

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#2379]
As a court user, so that I can accurately reflect the scope of an order or notice, I need to be able to modify the case caption and docket numbers on the header of a generated order or notice in a Lead Case.

When a document is filed in a case that is part of a consolidated group (CG), it is necessary to have that document reflected on the docket record for some or all of the other cases part of that group. Currently, when creating orders for cases in a CG, users must create them outside of DAWSON and then upload them via PDF, in large part because currently the system currently generates captions for the immediate case only.

We would like the Court to have the ability to modify the case caption when generating orders/notices in consolidated Lead Cases to add ", et al." to the Petitioners portion of the caption and add any other cases in the CG to the Docket No. portion of the caption.

See screenshot of attached order w/ caption for consolidated case example.

## Pre-Conditions
#3569

## Acceptance Criteria
* When creating or editing a document on the Lead Case in a consolidated group, on the Create/Edit screen for the document, the user can indicate that the document caption should be modified
* The user can select which case numbers from the consolidated group should be added to the caption
  - The default for this should be to add _all_ cases from the consolidated group
* When the caption is modified, the Lead Case petitioner's name in the caption should be appended with ", ET AL.," (see screenshot)
* When the caption is modified, the Lead Case docket number in the caption should be followed by the comma-separated values of all other cases in the group selected by the user (see screenshot)
* The Preview tab should show the modified case caption (if modified)
* User can choose to de-select the option to modify the caption
* This applies to user-generated Court orders and notices; auto-generated orders and notices are not in scope for this story.

## Notes
Example of caption on consolidated case order: ![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/c563d71a-8cef-4e29-af07-897e3207ab59)

## Test Cases
* User generates a document in the Lead case of a consolidated group; chooses to modify the caption contents of the document; all other cases in the CG are marked for inclusion; user writes the document; document preview displays modified caption contents for petitioner and docket numbers displaying all other cases in the CG; saves document; document appears as Draft with modified caption
* User generates a document in the Lead case of a consolidated group; chooses to modify the caption contents of the document; some (not all) of the other cases in the CG are marked for inclusion; user writes the document; document preview displays modified caption contents for petitioner and docket numbers displaying only those cases marked for inclusion; saves document; document appears as Draft with modified caption
* User generates a document in the Lead case of a consolidated group; does not choose to modify the caption; user writes the document; document preview displays normal caption contents for petitioner and docket number; saves document; document appears as Draft with normal caption
* User generates a document in a member case of a consolidated group; is not presented w/ option to modify caption; document preview displays normal caption contents for petitioner and docket number; saves document; document appears as Draft with normal caption
* User generates a document in a case that is not part of a consolidated group; is not presented w/ option to modify caption; document preview displays normal caption contents for petitioner and docket number; saves document; document appears as Draft with normal caption

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to the Court's `test` environment for PO Review

**Comment by swongCO** [comment]
![Create Order.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/07e8a98e-e445-4996-aff9-6d79e8a711c9)
- For lead cases, display icon link beneath Generate tab
–––––
![Create Order -modal.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/8fcd1e59-dae4-4324-8351-30defbb52928)
When Save is clicked, display modal with the following text changes:
1. Title: Add Docket Numbers
2. Body: Select cases that you want to add to the header of the cover sheet. Petitioner’s name will be automatically appended with “ET AL.”.
3. Primary CTA: Add Docket Numbers
4. If only one case is selected, do not append petitioner's name with ET AL
–––––
- Same icon link and modal display for the Edit Order flow

**Comment by ttlenard** [comment]
## Test Cases

#### 1) User generates a document in the Lead case of a consolidated group; chooses to modify the caption contents of the document; all other cases in the CG are marked for inclusion; user writes the document; document preview displays modified caption contents for petitioner and docket numbers displaying all other cases in the CG; saves document; document appears as Draft with modified caption



#### 2) User generates a document in the Lead case of a consolidated group; chooses to modify the caption contents of the document; some (not all) of the other cases in the CG are marked for inclusion; user writes the document; document preview displays modified caption contents for petitioner and docket numbers displaying only those cases marked for inclusion; saves document; document appears as Draft with modified caption



#### 3) User generates a document in the Lead case of a consolidated group; does not choose to modify the caption; user writes the document; document preview displays normal caption contents for petitioner and docket number; saves document; document appears as Draft with normal caption



#### 4) User generates a document in a member case of a consolidated group; is not presented w/ option to modify caption; document preview displays normal caption contents for petitioner and docket number; saves document; document appears as Draft with normal caption



#### 5) User generates a document in a case that is not part of a consolidated group; is not presented w/ option to modify caption; document preview displays normal caption contents for petitioner and docket number; saves document; document appears as Draft with normal caption

**Comment by codyseibert** [comment]
From a discussion, some additional changes we plan to do include:

Edit Model
  - show this when only lead case is selected
    - "ET AL." will not be appended to the caption.
  - change button to "Save"
  - change title to "Edit Docket Numbers"
  - change main link to "Edit" instead of Add

**Comment by swongCO** [comment]
UX feedback:
![Screen Shot 2022-09-07 at 2.00.50 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/cc592fb1-7001-419b-81e4-66d377b0cbd5)
There is extra spacing in front of "Docket..." in the docket number section so when it wraps to a second line, they are not left aligned. Please remove the extra spacing.

![Screen Shot 2022-09-07 at 1.59.34 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/18932f1f-30ee-4676-84d5-8f7fd7602867)
When I created a Notice and edited it, the edit modal is not showing all the cases in the group, only the lead case.

**Comment by liadmccabe** [comment]
@codyseibert UX recommendation: Wrap second sentence so that it continues from the first. (i.e. next sentence should start immediately after the word 'caption' rather than start in the next line).  ![Screen Shot 2022-09-13 at 2.00.23 PM.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/e0464180-8c9a-452c-b971-7230808b627b)

**Comment by ttlenard** [comment]
Note: In test case 8, the link to add docket numbers to the caption WAS present for decision type of orders.  I did some additional testing, and Docket is still not able to docket across cases in a consolidated group for decision types of documents, so @cholly75 indicated that it will be fine.  Court users that are creating Orders should know that they are not supposed to file these types of orders across multiple docket numbers.  

I left the original test case in the Test cases section, but put a strikethrough in it.
