### ISSUE TITLE
Request Case Access/Add Docket Entry Clean-up

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#2397]
As a team, so that exhibits are not part of requesting case access, we need to remove the option to add them. 

## Acceptance Criteria
* Exhibits is removed as an option for document inclusions on the Request Case Access form for practitioners  
* Exhibits is removed as an option for document inclusions on the Request Case Access form for respondents
* Exhibits is removed as an option for document inclusions on the Add Docket Entry form 
* Exhibits does not appear as part of the concatenated docket entry 
* Make sure any changes applied to File a Doc re-work (#1508) is applied to:
   * Request Case Access form
   * Add Docket Entry form

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Users may still file "Exhibits" as a separate document filing

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment (Jojo #3188)

**Comment by mariahkannenberg** [comment]
Awaiting punch list of items that need to be done from #1508.

**Comment by uxforgood** [comment]
### Punch list (IN PROGRESS)

- [ ] Move all yellow alert bars above the blue sections
- [ ] Change field labels to sentence case
- [ ]

**Comment by klohman** [comment]
# Punch List 

### Request Access (practitioner user)
#### Default View 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8fbc3029-1d1d-420c-b59f-03493dd3dc1d)


If these document types are selected, no changes to default screen:
Entry of Appearance
Substitution of Counsel 

* Update text (see text changes in red) 
* Move yellow helper text 
* Replace current COS radio set with new “extra items” field 
* Add “, Petitioner” text for each petitioner 
       - format should be [Contact name], Petitioner 


#### Notices 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/98cbc177-a400-453e-b379-64d0adf86414)

If these document types are selected:
Notice of Intervention
Notice of Election to Participate
Notice of Election to Intervene

* Display “Attachment(s) checkbox in extra items field 

#### Motion to Substitute Parties and Change Caption
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c60bf554-fd93-4a99-a5d0-b1e06ca22d0f)

If Motion to Substitute Parties and Change Caption is selected:

* Display “Attachment(s)” checkbox in extra items field 
* Display Objections radio set 
* Display “Add Supporting Document” button
* On click of “Add Supporting Document” - display Supporting Document 1 section; allow up to 5 supporting documents  

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/dcb01680-442a-4e4c-a585-acbe737eb6b6)


#### Review Screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/397b99f7-f2ea-49f9-9b28-0098cca37884)

* Update to card layout 

### Request Access (respondent) 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f4bbc95f-2774-4a63-8a4d-efb6d212fc03)

#### Default screen 

Document type dropdown ONLY contains: 
Entry of Appearance
Substitution of Counsel 

* Update text (see text changes in red) 
* Move yellow helper text 
* Replace current COS radio set with new “extra items” field 


#### Review Screen (respondent)
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/03040a5d-5797-44a7-b826-1aabfb423d7d)

* Update to card layout

**Comment by klohman** [comment]
## 2397 Request Access Form Changes - Test Scenarios 

#### 1) Practitioner selects Entry of Appearance as doc type 
* Login as practitioner3 
* Navigate to case 144-19
* Click on Request Access button 
* Select Entry of Appearance as doc type 
Expected results 
- [ ] Attachments checkbox is displayed on form 
- [ ] Certificate of Service checkbox is displayed 
- [ ] Exhibits option is removed from form 
- [ ] Parties are displayed as Petitioner Name, Petitioner 

#### 2) Practitioner selects Notice of Intervention as doc type 
* Login as practitioner3 
* Navigate to case 144-19
* Click on Request Access button 
* Select Notice of Intervention as doc type 
Expected results 
- [ ] Attachments checkbox is displayed on form 
- [ ] Certificate of Service checkbox is displayed 
- [ ] Exhibits option is removed from form 
- [ ] Objections radio set is displayed and required
- [ ] Parties are displayed as Petitioner Name, Petitioner 

#### 3) Practitioner selects Notice of Election to Participate as doc type 
* Login as practitioner3 
* Navigate to case 144-19
* Click on Request Access button 
* Select Notice of Election to Participate as doc type 
Expected results 
- [ ] Attachments checkbox is displayed on form 
- [ ] Certificate of Service checkbox is displayed 
- [ ] Exhibits option is removed from form 
- [ ] Objections radio set is displayed and required
- [ ] Parties are displayed as Petitioner Name, Petitioner 

#### 4) Practitioner selects Notice of Election to Intervene as doc type 
* Login as practitioner3 
* Navigate to case 144-19
* Click on Request Access button 
* Select Notice of Election to Intervene as doc type 
Expected results 
- [ ] Attachments checkbox is displayed on form 
- [ ] Certificate of Service checkbox is displayed 
- [ ] Exhibits option is removed from form 
- [ ] Objections radio set is displayed and required
- [ ] Parties are displayed as Petitioner Name, Petitioner 

#### 5) Practitioner selects Substitution of Counsel as doc type 
* Login as practitioner3 
* Navigate to case 144-19
* Click on Request Access button 
* Select Substitution of Counsel as doc type 
Expected results 
- [ ] Attachments checkbox is displayed on form 
- [ ] Certificate of Service checkbox is displayed 
- [ ] Exhibits option is removed from form 
- [ ] Objections radio set is displayed and required
- [ ] Parties are displayed as Petitioner Name, Petitioner 

#### 6) Practitioner selects Motion to Substitute Parties and Change Caption as doc type 
* Login as practitioner3 
* Navigate to case 144-19
* Click on Request Access button 
* Select Motion to Substitute Parties and Change Caption as doc type 
Expected results 
- [ ] Attachments checkbox is displayed on form 
- [ ] Certificate of Service checkbox is displayed 
- [ ] Exhibits option is removed from form 
- [ ] Objections radio set is displayed and required
- [ ] Add Supporting Documents button displays 
- [ ] Parties are displayed as Petitioner Name, Petitioner 

#### 7) Respondent selects Entry of Appearance as doc type 
* Login as respondent3 
* Navigate to case 224-19
* Click on Request Access button 
* Select Entry of Appearance as doc type 
Expected results 
- [ ] Attachments checkbox is displayed on form 
- [ ] Certificate of Service checkbox is displayed 
- [ ] Exhibits option is removed from form 

#### 8) Respondent selects Substitution of Counsel as doc type 
* Login as respondent3 
* Navigate to case 224-19
* Click on Request Access button 
* Select Substitution of Counsel as doc type 
Expected results 
- [ ] Attachments checkbox is displayed on form 
- [ ] Certificate of Service checkbox is displayed 
- [ ] Exhibits option is removed from form 
- [ ] Objections radio set displays 
- 

#### 9) Practitioner sees updated Review Filing screen 
* [Scenario 6]
* Check COS checkbox and enter 10/01/19 date 
* Check attachments checkbox 
* Select “No” for objections 
* Add “Brief” as supporting document 
* Complete all remaining required fields and click “Review Filing” 
Expected Results 
- [ ] “Certificate of Service 10/01/19” displays under “Document Includes” 
- [ ] “Attachment(s)” displays under Document Includes 
- [ ] “No” displays under “Objections?”
- [ ] Brief with selected pdf document displays as supporting document 
- [ ] Selected parties are displayed 


#### 10) Respondent sees updated Review Filing screen 
* [Scenario 8]
* Check COS checkbox and enter 10/01/19 date 
* Check attachments checkbox 
* Select “Yes” for objections 
* Complete all remaining required fields and click “Review Filing” 
Expected Results 
- [ ] “Certificate of Service 10/01/19” displays under “Document Includes” 
- [ ] “Attachment(s)” displays under Document Includes 
- [ ] “Yes” displays under “Objections?”
- [ ] Brief with selected pdf document displays as supporting document 
- 

#### 11) Concatenated document title is displayed correctly 
* [Scenario 9]
* Submit Filing 
* View docket record 
Expected results 
- [ ] Document title displays as “Motion to Substitute Parties and Change Caption (C/S 10/01/19) (Attachment(s)) (No Objection)”

**Comment by mariahkannenberg** [comment]
Feedback from QA review: 
When logged in as a practitioner, requesting case access, selecting Motion to Substitute Parties and Change Caption, adding Brief as supporting doc, Brief in Support of is not concatenated with the actual document name.

 ![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/d7e45a6c-8a04-446d-a8d8-ee70d20fe216)
