### ISSUE TITLE
Stip Decision: Ability to sign after it's in draft state (Already done)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3010]
As a Sr. Attorney, so that I may save my signature on a stipulated decision before sending to the docket clerk, I need the ability to save and later access the signed stipulated decision in draft format. 

## Acceptance Criteria
* ADC can sign a Proposed Stipulated Decision after it is QC’d
* Docket clerk can sign a Proposed Stipulated Decision after it is QC’d
* Judge role can sign a Proposed Stipulated Decision after it is QC’d
* Chambers role can sign a Proposed Stipulated Decision after it is QC’d
* Docket clerk/ADC/Judge/Chambers user must be able to remove a signature from a signed STIP while in draft state 
* Docket Clerk can delete a draft STIP
 

* Note - that in the system's current state only a Petitions clerk has the "Create Order" button but this story should not be limited by permissions at all in terms of how it's implemented. All Court users should have the ability to interact with draft states

## Notes
* Need to discuss what to do if user applies a signature to a doc, sees an error, then wants to go back, correct and reapply signature. When does the document become a PDF?
* No version control needed. Only latest version of document should be retained (MVP)
* This story includes creation of draft documents tab, which is the space where signed stip decisions and orders will be held until they are linked to a docket entry and served. 
* Can user see an aggregated list of "in progress" orders or do they have to go back into that case first?
* Can user delete an in progress order?
* Can other users see the drafted order?
* Draft state for orders/decisions don't have work item
* Proposed Stip Decision have work item; Work item persists until the signed version is

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
- [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
- [ ] Automated test scripts have been written
- [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Code refactored for clarity and to remove any known technical debt 
 - [ ] Deployed to the dev environment
- [ ] Deployed to the stage environment

**Comment by klohman** [comment]
# OLD test cases - NEED TO BE UPDATED - USE FOR REFERENCE ONLY

## TEST CASES (Draft)

### Draft State for Signed Stip Decision
Practitioner or IRS Attorney uploads a proposed stipulated decision
Docket clerk sees proposed stipulated decision in Section Document QC
Docket clerk clicks on proposed stipulated decision, reviews the doc, FORWARDS (“send”) the message to the Sr. Attorney and clicks save, which sends the message to the Sr. Attorney and removes the item from the QC inbox.
Sr. Attorney logs in and sees the Proposed Stipulate Decision message in their message box. 
* Route1 - Save and Send:
       * Sr. Attorney clicks on the proposed stipulated decision, review and signs the doc, crafts a message to the docket clerk (which becomes a new message thread), then clicks “Save and Send,” which closes out the original message thread for the proposed stipulated decision (all users), generates a new signed stipulated decision message.
      * The signed stipulated decision is saved in draft format and viewable from both the new message thread **and the draft tab on the case detail page.**

* Route 2 - Save
      * Sr. Attorney clicks on proposed stipulated decision, reviews and signs the doc and clicks “Save,” which generates a new signed stipulated decision.
      * The signed stipulated decision is saved in draft format **and is viewable in the draft tab on the case detail page.**
Docket Clerk navigates to My Messages>Inbox and sees Signed Stipulated Decision message from Sr. Attorney
Docket Clerk select Signed Stipulated Decision and sees the document in draft form
From the draft form Docket Clerk serves the Signed Stipulated Decision
Service of the Signed Stip Decision is recorded in the docket record

### Create Draft Orders
Petitions Clerk navigates to case detail page and clicks Create Order
Petitions Clerk creates order and selects Save Order, which **creates a draft of the order**
**Draft Order is viewable from the case detail page draft tab**

### Edit a Draft Signed Stipulated Decision
**Court user navigates to case detail page/draft tab**
**Court user selects signed stipulated decision draft**
(Then what? Remove and reapply signature? This is not in the AC. )

### Edit a Draft Order (Without Signature)
Court user navigates to case detail page/draft tab
Court user selects draft order and is taken to the Document Detail page for a Draft Order
Court user selects “Edit” edits the order and clicks save
Court confirms that their changes have saved

### Edit a Draft Order (With Signature)
Draft order with signature, not yet done.

**Comment by klohman** [comment]
# OLD DESIGN NOTES - USE FOR REFERENCE ONLY

## General behavior

- When an order gets saved it sits in the draft state of that case until it is served
- When a user clicks "add signature" to a proposed stip decision, that triggers it to move into draft state where it remains until it is served
    - When in draft state, only thing that can be changed on stip decision is removing the signature and adding a new one
- There are only 2 types of documents  - "order/decision" and "stipulated decision" 
- If a doc is in a draft state it should NOT appear on the docket record

## Design

### Create order

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/72187800-6714-4104-8df0-a0b66a6c3cee)

- [x] Update text on button to "Save Order" 

### Case detail page - draft documents tab

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/7eab2ad2-1dfc-4d38-9823-0d168a25a924)

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/c31778cd-7e76-4171-8240-a52dcb301533)

- [ ] Add Draft Documents tab to the case detail page between Docket Record and Case Info
- Draft docs table should have the following columns: 
    - Date (this is the document was created) 
    - Doc name 
    - Who created the doc (user name) 
    - 2 actions to edit or delete
- Draft docs table should be sorted by Date with oldest on top
- Clicking on doc name takes user to doc detail page (view page, not edit) 
- Clicking on Edit takes user to Edit page
- Clicking on Delete launches "Are you sure?" modal 
- Null state - if there are no draft documents display "There are no draft documents." in semi bold body copy style

### Delete are you sure modal & success message

#### Order are you sure modal
![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/4a94804a-a9b8-47d5-b0b3-c9426dbd3d33)

#### Stip are you sure modal
![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/2cb03313-9375-4949-a7c8-d2c3eb4b2188)

#### Success message
![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/b596225f-fa10-447e-a482-e5d553e19312)

- If user selects Yes: 
   - Close modal and return to case detail page with draft tab selected
   - Delete draft document
   - Display success message on case detail page that draft was deleted successfully 

- If user selects No: 
   - Close modal and return to previous screen

### Document detail page of a draft Order

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/68899e5e-be86-4b2c-86ea-48cbb57ea7c8)

- [ ] add actions to edit and delete order
- [ ] Add "DRAFT" after the order name
    -  [ ] This DRAFT label should NOT appear attached to the doc name in other places (so not in message table, draft docs table, etc.) 

### Document detail page of a draft Signed stip decision

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/e0a57d90-9b35-41f4-83a1-1bcfb0247ae4)

- [ ] Add "DRAFT" after the order name
    -  [ ] This DRAFT label should NOT appear attached to the doc name in other places (so not in message table, draft docs table, etc.)

### Edit order page

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/ee1c8c75-85ce-4d98-b808-48bb368f95f8)

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/44f9abc2-9c31-4549-bcf5-2c1d5f7dc264)

- Looks same as "create order" page except the title is "Edit [order name]" and all previously entered content is pre-populated
- After edit is saved, return to Doc detail page and show success message 

### Sign Proposed Stip Decision

#### With no message info filled out
![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/43bac406-e5a4-4897-bd25-7ad1d9e76a72)

#### With message info filled out
![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/b9fcdd90-2011-445a-a870-94f9b0f0083b)

- As part of this story it should no longer be required to create a message when signing a stip decision. 
- [ ] Add "(optional)" to messgae section of sign stip decision page and remove form validation as a required field 
- [ ] Update button behavior
    - On page load, "Save" is enabled and "Save & Send Message" is disabled
    - Once user starts filling out any of the 3 message fields, "Save" becomes disabled and "Save & Send Message" is enabled
    - If there are no selections for the message (user clears them all for instance) the default state would return with "Save" is enabled and "Save & Send Message" is disabled
