### ISSUE TITLE
Court: Ability to correct a case caption

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#310]
As a Court User, so that I can correct any typos the Petitioner makes, I need the ability to correct case captions that were generated by the system. 

Case captions are automatically being generated by system, based on Petitioner-entered data. If a Petitioner accidentally enters incorrect information, the system will generate a caption from that incorrect data. During the QC process or at any other time, court users need the ability to correct the case caption, just as they would with any other case metadata. 

## Pre-Conditions
* Case caption has been automatically generated
* Court user can see the auto-generated case caption

## Acceptance Criteria
* Court user can edit and save the auto-generated case caption
* Only the part of the caption before "v. Commissioner of Internal Revenue" needs to be editable
* Change is captured on the docket record as an entry that reads "Caption of case is amended from [old caption] to [new caption]"
* Anywhere the case caption currently displays, it displays the corrected case caption after it is edited

## Research/Analysis Notes
* This can happen during the Petitions Clerk QC process and any other time.

## Tasks
- [x] Design mechanism for editing the case caption (Kristen) 
- [x] Update Case Detail page - add edit button 
- [x] Update Document Detail page - add edit button
- [x] Create Edit Case Caption modal 
- [x] Add checkbox icon and text beside Case Caption (kris)
- [x] Create Modal for editing Case Caption (kris)
- [x] Create Sequences for opening, closing modal (William)
- [x] Create sequence & actions for saving case caption (William)
- [x] Add Docket Record Item when the case caption is updated (William)
- [x] write tests for sequence which updates case caption (William)

 ## Definition of Done
- Product Owner
  - [ ] acceptance criteria have been met
- UX
  - [x] usability has been validated
- Engineering
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] library/module dependencies are up-to-date and are at the latest resolvable version
  -  [x] CI/CD - Code is deployed to DEV
- Other
  - [ ] alerting and monitoring for new functionality in place and successfully exercised

**Comment by klohman** [comment]
## Editing Case Caption 

- Case caption will be autogenerated when the case is created 
- After the case is created, all updates to the case caption can only be done manually by editing the text itself 

## Case Detail Page 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e7818016-e2eb-493d-a423-fa557f95bbd7)

- Include an "Edit" button on the case detail to the right of the Case Caption 
- the edit button should align with the first text row of the caption (the caption text need to wrap but should be in a separate column from the Edit button) 

## Document Detail Page 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/76ddba83-248f-4803-bc81-0d7d2df3beda)

- Edit button should display on all document detail pages in the record 

## Edit Caption Modal 
- On click of the Edit button from either the Case Detail or Document Detail page, the Edit Caption Modal displays 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7f94726f-4e1e-4c79-9106-fbb52be69e21)

- Case Caption field is pre-populated by the current case caption 
- Case Caption field is editable 

- On click of Save, the case caption is updated and modal closes
- On click of Cancel, no changes are saved and modal closes 


## Batched for IRS status 
- when a case in in the status "Batched for IRS" - the Edit button for the case caption is hidden on case detail and document detail screens
