### ISSUE TITLE
Petitioner: Clean up petition form

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#315]
As a petitioner, so that my petition process can be clear and streamlined, I need my dashboard and upload functions to be user friendly. 

## Acceptance Criteria
* Dashboard table is consistent with other table design
* Dashboard blank state is usable and contains small amount of relative content
* For success messages, update positioning of "dismiss" text and icon to float it so text doesn't wrap into it
* Recommendations from usability study implemented
* Make sure all language from 307 has been updated (see comment from Kristen from 2/20)
* Make sure docket record views are consistent across all users
* Email address of Petitioner should display as part of contact information in the Case Info. tab
* Name of Petitioner that shows up on the dashboard table once a case is started is NOT the name of the person logged in, it should be the name of the Petitioner in the caption (all of the stuff before ", Petitioner v..."). [Added to #367]
* The message generated in the work queue/message thread for an incoming Petition should read "A Petition filed by [name of Petitioner in the caption] is ready for review." [Added to #367]

## Notes
* Size limitations for uploads will be handled in a separate story
* Field level error messaging on the Start a Case page will be addressed here

### Design 
- [x] Update Petitioner Dashboard design 
- [x] Improve the details and placement of the form instructions to prepare users for completing the form itself - done 
- [x] Include information regarding fee payment before the petition is submitted - updated info on dashboard
- [x] Move the upload petition field closer to the form instructions - done 
- [x] Update the placement of the “All Fields Required” message - done
- [x] Replace greater than (>) and less than (<) symbols with text - done
- [x] Reinforce the “no right to appeal” for small tax case selection - no changes 
- [x] Change the color of the header text in the accordion so they aren’t confused with links (MVP)
- [x] Update the design of the accordion to be more prominent (MVP)
- [x] Update language to prompt users to select their closest city - no changes needed
- [x] Provide a more detailed page-level list of which fields have errors (update in progress) 
- [x] Add field-level error design and messaging (update in progress)
- [x] Update the success indicator for file upload fields - done 
- [x] Build out instructions and other contextual information on the petitioner dashboard- done
- [ ] Remove the search box for petitioners (MVP- HOLD)
- [x] Make it more clear that users can’t edit the petition after they submit the case- done 
- [x] Design "Before You Begin" page downloadable PDF 
- [x] Design "how to merge pdfs" downloadable PDF 
- [x] Update design for Respondent Dashboard 

### Dev
- [x]  Fix the bottom margin on the read-only field labels - on QC screen and Case Info tab  (William)
- [x]  Error message spacing on QC screen - for date field (William)
- [x]  Correct Spacing on Document Detail page - Date filed and Filed By (Eric)
- [x]  Correct 6 column layout for Case Info tab (Eric)
- [x] On document detail, bottom align the Batched for IRS section with the tabs (Eric)
- [x] Update petitioner dashboard view per design (Eric)
- [x] Update Start a Case form view per design (William)
- [x] Change "Start a Case" button text to title case (Eric)
- [x] Update success message design (see comment) (William)
- [x] Update respondent dashboard per new design (Eric)
- [x] Updated language for party types (see comment) (William)
- [x] Add links to downloadable PDFs on Petitioner Dashboard and Before you Begin page (Eric)
- [x] Update table design on Petitioner and Respondent dashboards  (Eric)
- [x] Update language on "Before You Begin" page (see comment) (Eric)
- [x] Update language to "legally incompetent person" anywhere that "incompetent person" appears (William)

## Definition of Done
- [x] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version

**Comment by klohman** [comment]
# Updated designs for the Petitioner Dashboard 

## Default - when user has not created any cases 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/df8880da-a569-42f0-b720-9cdc802de3ab)

### Links 
- "How to prepare your documents before filing your case" - on click, download the How to Prepare Your Documents Before Filing Your Case" pdf (to be provided) 

- "Find a court location"- on click open link in new tab: https://www.ustaxcourt.gov/dpt_cities.htm

- " View forms" - on click, open link in new tab: https://www.ustaxcourt.gov/forms.htm

"How to file a case by mail or in person" - open link in new tab- link TBD 


## Dashboard View- When a user has one or more cases 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d737ff1c-f422-441b-984c-ba0f3cb9c192)

**Comment by klohman** [comment]
## Updates to Start a Case Form 

### File Upload success indicator 
- updated icon for file upload success indicator 
- .fas.fa-check-circle 
- color fill - #2E8540

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8367d238-c732-4ed0-9924-92abe599deaa)

### Update language in message 
- change "Petition" to case - see change in red in screenshot. 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d29222c9-b25d-40a9-932a-4cb3fefa8089)

### Add icon to accordion text 
- Add icon to the "how is a small case different.." accordion 
- .fas.fa-question-circle
- color fill- 0071BC

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/39c4d78b-5fb8-4c8a-b9be-d412a878285c)

### Update language in Review your information section 
- Change Petition to "case" - see red text in screenshot 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/513d3ace-a622-4f62-ae6a-adaec83cc905)

### Updated design for accordion 
- Updated the text "less than $50,000..." for case limits 
- Changed the header color for "More Location Options" etc to #212121

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/405b792d-7ad2-48a7-8b25-40e2193173ec)

**Comment by klohman** [comment]
## Success and Alert Messages 

Update Dev to match design for these messages
- "Dismiss" link should align with the first row of message text 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/aab6d134-3dfd-44cb-b35d-e552ecc8cbdf)

**Comment by klohman** [comment]
## Updates to Contact Party Language 

### Corporation 

- Change "In Care Of" field to required 
- Update language of In Care of label to "In Care Of (Your Name) 

### Partner (Other than a Tax Matters Partner)

- Update name field label to "Name of Partner (Other than a Tax Matters Partner) 

### Estate with Executor 

- Update header language to "Tell Us About Yourself as the Executor/Personal Representative/etc. For This Estate"   
- Update primary contact name field to "Name of Executor/Personal Representative, etc."

### Estate without Executor 

- Update In Care of field label to "In Care Of (Your Name) 

### Incompetent Person 

- Update language to "legally incompetent person" anywhere that "incompetent person" appears 
- In radio button sets 
![Screen Shot 2019-02-20 at 12.07.41 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/71410e3b-a445-419d-953b-dbb1145525a8)

![Screen Shot 2019-02-20 at 12.07.59 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b08f0d9e-5489-4f0f-b6bf-d9b3e824a528)
- Update header to "Tell Us About Yourself as the Next Friend for This Legally Incompetent Person" and "Tell Us About the Legally Incompetent Person You Are Filing For "

- Update secondary contact name field label to " Name of Legally Incompetent Person"

**Comment by klohman** [comment]
## Before Your Begin page 

### Update language below " Before You Begin Your Case" 
-  Change sentence to " There are a few things you need to do to prepare your documents before filing your case. Read through and follow these instructions carefully. "

### Update language under Have the IRS Notice(s) You’ve Received Available to Submit
- Change first sentence to "If you’ve received an IRS notice, such as a Notice of Deficiency or Notice of Determination, you’ll need to include a copy with your Petition."

### Add link to PDF 
On Before You Begin Page, on click of " Learn more about how to merge files into one PDF", download the PDF located here:  https://drive.google.com/open?id=1TU7YIXAIiBjBu4600sExQyejU1zFyGd3

**Comment by klohman** [comment]
## Respondent Dashboard 

### Blank State 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/38caee9e-9052-4821-b6ad-f082f5aae2e1)

### With Cases 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/14c41ac4-59dd-4a03-972c-22ae16b08274)
