### ISSUE TITLE
Upload of additional documents after initial filing (Nice to Have)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#328]

**Comment by mariahkannenberg** [comment]
@JessicaMarine  This item was categorized as nice to have in one of your initial prioritizations. Is this still the case?

**Comment by JessicaMarine** [comment]
I don’t see it as a necessary feature, and definitely not for MVP.

**Comment by mariahkannenberg** [comment]
I believe this is done.

**Comment by cholly75** [comment]
Closing issue.
