### ISSUE TITLE
UX:  Additional testing for filing a petition with pro-se petitioners

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#3286]
Following the on-site testing with two mock petitioners in DC in September 2019, it became clear that additional testing with pro-se petitioners is needed.

* Petitioner testers: who are they? (using our current user role) Per Jessica: Any US taxpayer could be a potential user of the system.  Friends, family, neighbors are a good candidate pool.
* Petitioner testers: what makes them fit the criteria? what is criteria
* Petitioner testers: where do we get them from find willing participants?
* Petitioner testers: when do we schedule?
* Review, edit, add to current test cases from Sept 2019
* Create new test cases
* Create test cases based on their user role petitioner, petitioner and spouse, whistleblower)

* Tips page A/B testing
* Small vs regular cases- understand the difference?
* Terminology- is this the correct usage
* How much attention to content are users making?
* What material do we need to provide user?
* What are the rules for having a user test? Per Jessica: the Court is not able to offer any incentive to have people serve as testers; it must be voluntary.  Flexion should let them know that this is a project still under development and is not a final product. There aren't any other restriction except the UX team shouldn't do anything to embarrass themselves, Flexion or the Court.

**Comment by alsmith1** [comment]
notes: 
-  talk to team about sending out blast via social media
- blast other channels
- court cannot send out blast, need to obtain permission
- Jessica has document and will look into getting documentation for us
- age range opened up to 18-65+ after talk with jessica

**Comment by alsmith1** [comment]
- staging to be frozen on Wednesday
- after freezing staging data will need to be set up and Jessica will need to be informed of case numbers.
- 15 current testers
testing to be scheduled for Friday through next week.

**Comment by klohman** [comment]
# Recommendations 

Complete report available: https://docs.google.com/presentation/d/1TV7nq-LTmqlr3oqYCRmajvDILRDrVDV2fLl7ruxZ1xM/edit?usp=sharing

**Dashboard / Landing Page** 
* Consider adding simplified information on the petition process (infographics, etc.) (Priority) 
* Include filing fee payment options and when to pay information upfront 
* Add external link icon for all petitioner tools 

**Instructions**
* Create simplified instructional materials, available on the public site (Priority)
* Break the form instructions down into bite-sized chunks to make it clear which forms need to be completed, what they are for, and when they will be used (Priority) 
* Spell out all acronyms in their first use (Priority) 
* Use plain language to rewrite all headers and descriptions (Priority) 
* Add visual examples of IRS Notices, STIN, and Petition forms, how to redact information from documents 
* Add alternative instructions for merging PDFs for users without Adobe Pro (Priority) 

**File Uploads**
* Clearly define the file upload fields by user-friendly form names (Priority) 
* Inform the user upfront of how many PDF documents they will need to upload (Priority) 
* Include reference links to the corresponding forms co-located with upload field (Priority) 
* Clarify the redaction warning message to ensure that users understand that it does not apply to the STIN (Priority) 

**Case Type** 
* Provide examples of IRS notices to initial instructions page; reference here 

**Party Type / Contact Information** 
* Add “copy” address functionality for spouse information 
* Update “All Fields Required” to be more visible throughout the form 
* Consider redesign / relocation of the ODS form fields for businesses to immediately follow the party type selector 
* Change language on “In Care Of” fields to exclude “(Your Name)” 

**Case Procedure** 
* Define what a “case procedure” is and what it will mean to the user in plain language (Priority) 
* Add logic to provide eligibility information to users based on their specific case
* Redesign the helper text to include parallel information between small case and regular case benefits (Priority) 

**Trial Location**
* Consider adding suggested trial locations based on petitioner address (Post-MVP) 

**Review Screen** 
* Add more direct edit functionality (Priority) 
* Define service email more clearly, and add information about what this email will be used for throughout the case 
* Revise reminder text for clarification around PDF inclusions/exclusions; consider co-locating with PDF previews 

**Confirmation / Case Detail** 
* Define court terminology more clearly (especially “docket”)
* Add dynamic text to success message to say “You’ve been assigned docket # XXX” 
* Consider including option to pay filing fee as part of the online petition process, or provide immediate payment options after submission (Priority) 
* Add “what to expect” information after petition is submitted, including what happens next in the process, how petitioner will be notified of updates, etc. ) (Priority) 
* Create null state for Case Detail > Case Information tab for external parties
