### ISSUE TITLE
Non-Party Upload of Documents (Nice to Have)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#329]

**Comment by mariahkannenberg** [comment]
@JessicaMarine Can you provide a little description for this one? I can't remember what it's for.

**Comment by JessicaMarine** [comment]
Sometimes there are non-parties that may want to file something in a case.  This is very rare and the most common would be an interested group wanting to file an Amicus brief on an issue.  This is not something we need to consider for MVP.
