### ISSUE TITLE
Petitions/Docket Clerks: Flatbed and two-sided scanning (by 1/8)

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#3290]
As a Petitions Clerk or Docket Clerk, in order to process paper-filed documents, I need flatbed and two-sided scanning.

As part of the on-site UX testing in September 2019, it became clear that Petitions Clerks and Docket Clerks need flatbed and two-sided scanning functionality.

## Acceptance Criteria: ##
* As a Petitions or Docket Clerk, I can use the flatbed of the scanner to scan in a paper document.
* As a Petitions or Docket Clerk, I can perform two-sided scanning.
* User may need to use one-sided, two-sided and flat-bed scanning all with one document, so they need to be able to choose between one-sided, two-sided, and flatbed per scanning batch.
* Once scanned, the document is saved and displays on the docket record

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes: ##
* The Court's scanner is a Kodak i2900 | 250-page hopper, 60ppm, 300 dpi, dual rotary / flatbed

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by alsmith1** [comment]
*** DRAFT ***
Scenario 1 - A Petitions or Docket Clerk can use the flatbed of the scanner to scan in a paper document.
1. Login as a petitions or docket clerk
2. Navigate to Document QC and click on the “Create a Case” Button
3. Fill in the case information on the left side
4. On the right side “Add Document(s)” Verify that the text in the blue header displays “Scanner: [scanner name (scanner setting)] change
5. Click on the change link in the header
6. Verify that a modal displays to set the Scanner being used and what type of scan is being done
7. From the “How would you like to scan your documents” section select Flatbed option from the dropdown menu
8. Select the scan radio button
9. Place your document on the flatbed of the scanner
10. Click on start scan
11. After scan completes verify the batch information displays under scanned batches header and is labeled as Batch 1 Flatbed # of pages rescan delete
12. Verify the pdf view displays what is on the paper document

Expected result
- [ ] “ Add Document” Verify that the text in the blue header displays “Scanner: [scanner name (Flatbed)] change
- [ ]  A modal displays  to set the Scanner being used and what type of scan is being used
- [ ] Document scans from the flatbed of the scanner
- [ ] Batch information displays under scanned batches header and is labeled as Batch 1 Flatbed # of pages rescan delete
- [ ] The pdf view displays what is on the paper document

Scenario 2 - A Petitions or Docket Clerk can perform two-sided scan
1. Login as a petitions or docket clerk
2. Navigate to Document QC and click on the “Create a Case” Button
3. Fill in the case information on the left side
4. On the right side “ Add Document” Verify that the text in the blue header displays “Scanner: [scanner name (scanner setting)] change
5. Click on the change link in the header
6. Verify that a modal displays  to set the Scanner being used and what type of scan is being used
7. From the “How would you like to scan your documents” section select Double sided option from the dropdown menu
8. Select the scan radio button
9. Place your document on the feeder of the scanner
10. Click on start scan
11. After scan completes verify the batch information displays under scanned batches header and is labeled as Batch 1 Double sided # of pages rescan delete
12. Verify the pdf view displays what is on the paper document

Expected result
- [ ] “ Add Document” Verify that the text in the blue header displays “Scanner: [scanner name (Double sided)] change
- [ ]  A modal displays  to set the Scanner being used and what type of scan is being used
- [ ] Document scans from the feeder of the scanner
- [ ] Batch information displays under scanned batches header and is labeled as Batch 1 double sided # of pages rescan delete
- [ ] The pdf view displays what is on the paper document


Scenario 3 - User may need to use one-sided, two-sided and flat-bed scanning all with one document, so they need to be able to choose between one-sided, two-sided, and flatbed per scanning batch.
1. Login as a petitions or docket clerk
2. Navigate to Document QC and click on the “Create a Case” Button
3. Fill in the case information on the left side
4. On the right side “ Add Document” Verify that the text in the blue header displays “Scanner: [scanner name (scanner setting)] change
5. Click on the change link in the header
6. Verify that a modal displays  to set the Scanner being used and what type of scan is being used
7. From the “How would you like to scan your documents” section select Double sided option
8. Select the scan radio button
9. Place your document on the flatbed of the scanner
10. Click on start scan
11. After scan completes verify the batch information displays under scanned batches header and is labeled as Batch 1 Double sided # of pages rescan delete
12. Verify the pdf view displays what is on the paper document
13. Click on the change link in the header
14. Verify that a modal displays  to set the Scanner being used and what type of scan is being used
15. From the “How would you like to scan your documents” section select flatbed option
16. Select the scan radio button
17. Place your document on the flatbed of the scanner
18. Click on start scan
19. After scan completes verify the batch information displays under scanned batches header and is labeled as Batch 2 Flatbed # of pages rescan delete
20. Verify the pdf view displays what is on the paper document
21. Click on the change link in the header
22. Verify that a modal displays  to set the Scanner being used and what type of scan is being used
23. From the “How would you like to scan your documents” section select Single sided option
24. Select the scan radio button
25. Place your document in the feeder of the scanner
26. Click on start scan
27. After scan completes verify the batch information displays under scanned batches header and is labeled as Batch 3 Single sided # of pages rescan delete
28. Verify the pdf view displays what is on the paper document

Expected result
- [ ] “Add Document” Verify that the text in the blue header displays “Scanner: [scanner name (scanner setting)] change
- [ ]  A modal displays  to set the Scanner being used and what type of scan is being used
- [ ] Document scans double sided from the feeder of the scanner
- [ ] Batch information displays under scanned batches header and is labeled as Batch 1 double sided # of pages rescan delete
- [ ] The pdf view displays what is on the paper document
- [ ]  Scanner modal displays and flatbed option is saved
- [ ] Document scans from the flatbed of the scanner
- [ ] Batch information displays under scanned batches header and is labeled as Batch 2 flatbed # of pages rescan delete
- [ ] The pdf view displays what is on the paper document
- [ ] “Add Document” Verify that the text in the blue header displays “Scanner: [scanner name (scanner setting)] change
- [ ]  Scanner modal displays and single sided option is saved
- [ ] Document scans single sided from the feeder of the scanner
- [ ] Batch information displays under scanned batches header and is labeled as Batch 3 Single sided # of pages rescan delete
- [ ] The pdf view displays what is on the paper document

Scenario 4 - Once scanned, the document is saved and displays on the docket record.
1. Login as a petitions or docket clerk
2. Preform steps 2-28 from scenario 3
3. Click “Create PDF” button
4. Verify that the PDF generates with all three of the batches scans

Expected result
- [ ] “Add Document” Verify that the text in the blue header displays “Scanner: [scanner name (scanner setting)] change
- [ ]  A modal displays  to set the Scanner being used and what type of scan is being used
- [ ] Document scans double sided from the feeder of the scanner
- [ ] Batch information displays under scanned batches header and is labeled as Batch 1 double sided # of pages rescan delete
- [ ] The pdf view displays what is on the paper document
- [ ]  Scanner modal displays and flatbed option is saved
- [ ] Document scans from the flatbed of the scanner
- [ ] Batch information displays under scanned batches header and is labeled as Batch 2 flatbed # of pages rescan delete
- [ ] The pdf view displays what is on the paper document
- [ ] “Add Document” Verify that the text in the blue header displays “Scanner: [scanner name (scanner setting)] change
- [ ]  Scanner modal displays and single sided option is saved
- [ ] Document scans single sided from the feeder of the scanner
- [ ] Batch information displays under scanned batches header and is labeled as Batch 3 Single sided # of pages rescan delete
- [ ] The pdf view displays what is on the paper document
- [ ] PDF generates with all three of the batches scans

**Comment by alsmith1** [comment]
![Screen Shot 2019-12-17 at 12.56.52 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/82267ea6-024f-4b4f-b49f-a3711a4e95ed)![Screen Shot 2019-12-17 at 12.57.12 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/30156aaf-f278-4fd1-8366-b5fa44885c0f)![Screen Shot 2019-12-17 at 12.57.23 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/e5ccc1c2-a6b4-4c2b-a887-0cfeec512edb)![Screen Shot 2019-12-17 at 12.57.47 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/72c8bc94-0f41-4f8c-bc60-26beb1b0fa48)![Screen Shot 2019-12-17 at 12.57.56 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/7a5be873-7dc0-4c77-9976-1b0fcb3af34f)
