### ISSUE TITLE
Make pracitioner search elastic

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3497]
Use elastic search for practitioner search

**Comment by cholly75** [comment]
@mariahkannenberg - is this another candidate for DevEx/OpEx? Not sure what the user benefit is here (or how we're doing the practitioner search now) .

**Comment by ttlenard** [comment]
Some additional information that will be helpful for this story.

- When searching for a specific attorney in the Advanced Practitioner Search, partial matches return results.
     -  example: 
     - Search for Peter Karl
     - Results return for Peter Adam Karl III
- When searching for a specific attorney to add them as counsel on the Parties tab within a case, partial matches do NOT return any results
     - example:
     - Go to any case
     - click on case information tab
     - click on parties tab
     - In the add counsel area, enter "Peter Karl"
     - no results will appear
     - The only way to get this attorney to appear is if you type out his entire name "Peter Adam Karl III"
     - This text box will ONLY search for exact matches
- We need the search box for adding counsel within a case to be able to search on partial matches just like it does within the Practitioner Database.
