### ISSUE TITLE
Court User: Add Judge filter to deadline report

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3796]
As a court user, so that I may easily see navigate my deadlines, I want the ability to filter the deadline report by judge. 

## Acceptance Criteria
* Judge is added to deadline report
* Court user can filter the deadline report by judge

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] add associatedJudge to the CaseDeadline entity
- [x] add the judge to the objects returned by the getAllCaseDeadlines persistence function
- [x] add CaseDeadline validation to the getAllCaseDeadlinesInteractor (Eric)
- [x] add judges to the Case Deadline table View
- [x] add judge filter to view
- [x] write tests for deadline report (Rae)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt

**Comment by alsmith1** [comment]
![Screen Shot 2020-01-29 at 10.57.45 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/863019d9-7d8f-4dd8-9992-176deb8fd29f)

**Comment by alsmith1** [comment]
####DRAFT####

## Test scenarios
#### Scenario 1 - Judge is added to deadline report
1. Log in as a internal court user
2. Navigate to Deadlines Report from the Reports Menu
3. Select a timeframe from the deadlines calendar
4. Verify that the table populates with any cases in that timeframe with deadlines added to it
5. Verify that the columns in this table  include: Due date, Docket, Case title, Description and Judge


Expected result
- [ ] The table populates with any cases in that timeframe with deadlines added to it
- [ ] The columns in this table  include: Due date, Docket, Case title, Description and Judge

#### Scenario 2 - Court user can filter the deadline report by judge
1. Log in as a internal court user
2. Navigate to Deadlines Report from the Reports Menu
3. Select a timeframe from the deadlines calendar
4. Verify that the table populates with any cases in that timeframe with deadlines added to it
5. Verify that above the table is a new filter “ filter by judge”
6. Click on the dropdown menu and select a judge
7. Verify that the table filters the results by the judge selected


Expected result
- [ ] The table populates with any cases in that timeframe with deadlines added to it 
- [ ]  Above the table is a new filter “ filter by judge”
- [ ]  The table filters the results by the judge selected
