### ISSUE TITLE
Prod: Create Court's Testing and Production Environments

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3893]
As the court, in order to facilitate user testing in a real-world environment, we need to set up our testing and production sites

## Acceptance Criteria
* Court's testing and production sites are set up
* Users can access the application through Court's test and production sites
* Ensure environments are updated with latest functionality
* Ensure users are set up in test environment

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Court will perform daily testing of test environment (T-F), starting on 1/13
* Court does not need test data in the test environment
* TEST environment URL is https://ui-test.ef-cms.ustaxcourt.gov/
* PRODUCTION environment URL is https://ui-prod.ef-cms.ustaxcourt.gov/

## Tasks
- [x] Set up testing environment and load test users (Eric) 
    - [x] Add variables to the config files; Waldo to create branch on court side that matches it
- [x] Set up production environment
- [x] Provide PR to tax court, w/changes necessary to set up test environment w/users (Kris and Eric)
- [x] Update AWS roles (Waldo)
- [x] Determine update schedule for testing and production environments (Waldo, for now)
- [ ] Testing of both environments - general UX review (Court will test details during daily session)

**Comment by waldoj** [comment]
This is going to necessitate procuring an additional software license for the scanning software.

**Comment by mariahkannenberg** [comment]
Court will continue to receive PR from flexion every 2 weeks for Court's staging environment. Then, up to court on when they merge to Court's testing and production.

Waldo will queue up the PR for the testing environment. Jessica will merge when it works for her.

**Comment by mariahkannenberg** [comment]
Feedback from Jessica:
* Logo missing from login page
* Can't get logged in. Are users uploaded?
* Still needs a UX review
* Open task for Waldo - AWS roles?

**Comment by waldoj** [comment]
I continue to work on getting these two environments created: run the build, see where it breaks, fix that thing; run the build, see where it breaks, fix that thing; and so on. Mostly it's a lot of deleting of roles and stacks. I will continue to do this.

**Comment by waldoj** [comment]
As of yesterday morning, these environments have been built and they work. Users have been created.

**Comment by alsmith1** [comment]
testing cannot be fully tested.jusdges are not in the system which full testing.
![Screen Shot 2020-01-30 at 11.52.22 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/1630e744-0a48-4e16-84d4-b438bd5d18bf)![Screen Shot 2020-01-30 at 11.40.20 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/56fa14f2-d639-41dc-a99a-72fa8919975d)

some instances of printing a paper service document gave errors generating document
![Screen Shot 2020-01-30 at 11.29.31 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/c5dcf5a7-4595-40ec-9e20-1175bbbf836a)

After cases have become consolidated the first search for one of the cases and view of case information displays no consolidated cases on the tile, after refreshing and clicking around to the other consoliidated cases clicking back to the case information the tile displays all cases consolidated

**Comment by mariahkannenberg** [comment]
Build issue that Waldo needs to troubleshoot with the team when he returns from travel.

**Comment by mariahkannenberg** [comment]
Cognito create users step failing on deploy. Team has been working. Failing on all branches sprint 333and 34.
