### ISSUE TITLE
E2E Round Table Testing (1/8)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3896]
As a project team, in order to identify showstoppers, we need to conduct unscripted usability testing in the Court's environment using real court data and scenarios. 

## Pre-Conditions
* Court's testing and production sites are set up (#3893)

## Acceptance Criteria
* Testers are varied and represent a variety of personalities, experience, backgrounds, technical ability, etc
* Test scenarios created are as close to real life as possible, including setting up unscripted scenarios and having users use their own court data
* Testers identified
* Test plan created
* Test plan executed
* Gaps that are identified and haven't been considered previously are documented
* Gaps are assessed by Jessica and and next step determined (Backlog, provide documentation, do the work, etc)

**Comment by klohman** [comment]
Complete findings and recommendations are available: https://docs.google.com/presentation/d/1MoLp0rC_QBfoBlULk5FCjbng-Lg70v6zOegp6brsnRM/edit?usp=sharing


### Key Findings 

* Overall, handoffs between roles went smoothly and as expected 
* Participants were able to easily navigate the system (even without prior training) 
* Petition batch process / order generation is a new process for petitions clerks; current workflow requires some updates to meet their needs/expectations 
* When drafting orders, judges want easier access to the docket record and previous documents on the case (split screen) 
* Participants were able to communicate with each other via the messages function, but there is a disconnect between original messages and subsequent actions/documents generated (i.e., original message is attached to Motion; Judge creates Order in response to Motion and now creates a new message thread)
* Docket/Calendar Clerk needs easier access to party address information from their QC screens 
* Docket Clerks need more flexibility around automated minute entries 

### Recommendations 
* Update Order title field to optional; do not display title on actual Order PDF, only on docket entry - (HIGH)
* Update petition > order workflow to guide clerks to create all orders required for a case before serving (TBD - dependent on discussion about real-time petition service) - (HIGH)
* Update “Create Order” screens to allow users to navigate and preview other documents in the docket record while drafting the order text 
* Add visibility to party contact information/address from all Document QC screens (HIGH)
* Add ability to manipulate PDF document orientation (Available via PDF viewer - train users) 
* Limit character count on all date fields (HIGH) 
* Add ability to include free text on Notice of Docket Change (MEDIUM??) 
* Add option to choose if an automatic minute entry should be created when action is taken (filing fee update, address updates, etc. )
* Add “digits” to docket clerk names in all dropdowns (MEDIUM?) 
* Add bar number to practitioner names across application (LOW?)
* Revise messaging flow to allow message threads to span or link across multiple documents (HIGH)
* Add ability to send bulk notices for cases on a trial session (HIGH) 
* Provide better wayfinding from trial session to case and back (LOW) 
* Reorder options in party types in dropdown: myself, myself and spouse, and corporation should be first (LOW) 
* Generate new cover sheet when petition received / file date is updated (MEDIUM)
* Need to account for petitions mailed in previous year but created in system in current year; docket number needs to be manually edited/added (LOW) 
* Clear dynamic fields when a new selection is made (order checkbox didn’t clear when Paid was selected) (MEDIUM)
* Consider revising the print Petition Receipt flow (TBD - dependent on discussion about real-time petition service) - (MEDIUM)
* Add ability to replace PDF on existing docket entry (MEDIUM)
* Ensure that Served and Parties columns are being populated on docket record when Petition and any orders served with the petition are served in batch 
* If externally filed document with COS - should not have served or parties fields populated in docket record (per Cheryl)
* Add ability to create a dual case status on a case (i.e., could be Calendared and Assigned-Motion) - (LOW) 
In the processed tab of Petitions, show orders nested with the petition they were served with (HIGH)

### Recommendations (Design updates)
* Print paper service screen - needs the “Actions” button in header 
* Serve to parties button should be single line and have an icon
* Flow/Design update needed: When you hit cancel on PDF upload error,  it makes you go all the way back to the beginning and start over in the form (HIGH) 
* Need to redesign the upload failure dialog (HIGH)
* Permission Update - Case Services Director - needs access to Petition Document QC - (HIGH) 
* Update label on Save and/or Serve buttons on Add Docket Entry screen 
* Update scan interface; decrease height on box to minimize blank space 
* On deadlines area, fix extra spacing between edit/delete links
* On Draft Order page, the edit/delete actions get lost - look at different placement
