### ISSUE TITLE
Standing Pretrial Order/Notice

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3910]
As the Court, in order to notify the parties about standard deadlines/next steps, a Standing Pretrial Order or Standing Pretrial Notice is issued simultaneously with a Notice of Trial 

## Acceptance Criteria
* When a calendar is set/automatically scheduled, all cases on that session should be issued a Standing Pretrial Order or a Standing Pretrial Notice
   * A Standing Pretrial Order is issued in all regular cases (sample below in comments; need to retain exact content)
   * A Standing Pretrial Notice is issued in all small cases (sample below in comments; need to retain exact content)
* If a case is manually added to a trial session *before* it is set/automatically scheduled, the case should not be issued a issued a "Notice of Trial" or a "Standing Pretrial Order/Notice" until that automatic scheduling
* If a case is manually added to a trial session *after* it is set/automatically scheduled, that case should be issued a "Notice of Trial" and a "Standing Pretrial Order/Notice" at the time the case is added to the trial session
* Standing Pretrial Order/Notice needs to have signature applied of judicial officer that's assigned to that trial session.  System needs to auto-apply the signature of judicial officer
* When the Standing Pretrial Order/Notice is issued, it is added to the Docket Record as a separate entry and served on the parties:
   * served date added to document; 
   * docket record displays served date and parties; 
   * parties receiving electronic service get email; 
   * parties receiving paper service get paper.
* Docket Entry Text should read:
  * Standing Pretrial Order = Standing Pretrial Order
   * Standing Pretrial Notice = Standing Pretrial Notice
* The document should be hyperlinked from the docket entry
* Codes for Docket Record
   * Standing Pretrial Order = SPTO
   * Standing Pretrial Notice = SPTN

## Notes:
* order = regular cases; notice = small; 
* gets issued at the same time as notice of trial. When they hit set calendar, it will kick off both documents

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Matt)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning (Matt)
 - [x] New screens have been added to pa11y scripts (Matt)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html  (Matt)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Matt)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required) (Matt)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Jojo)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Matt)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs (Matt)
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by JessicaMarine** [comment]
Content needed for Standing Pretrial Order:
[https://app.zenhub.com/files/152320868/298b2a09-2726-4b1f-a75b-c5c8ed51cb39/download](https://app.zenhub.com/files/152320868/298b2a09-2726-4b1f-a75b-c5c8ed51cb39/download)

Content needed for Standing Pretrial Notice:
[https://app.zenhub.com/files/152320868/12c92a20-39e5-43e1-9b89-1cec3024ffb7/download](https://app.zenhub.com/files/152320868/12c92a20-39e5-43e1-9b89-1cec3024ffb7/download)

**Comment by alsmith1** [comment]
---DRAFT---


## Test scenarios
#### Scenario 1 - When a calendar is set/automatically scheduled, all regular cases on that session should be issued a Standing Pretrial Order
1. Login as any internal user
2. Navigate to trial sessions and select a session
3. Verify this session has not been calendared, the set calendar button appears
4. Scroll down to the eligible cases section and click on the Set Calendar Button
5. Verify a modal displays” are you sure you want to set the calendar for this trial session?”
6. Click Yes, set calendar
7. Verify success message displays at top of session information screen
8. Verify after you submit trial a pdf viewer displays with a notice of set trial and the standing pretrial order (for paper fillers only)
8. Click on a case’s docket number in the trial session
9. Verify that a Standing Pretrial Order has been added to the docket record as Oder Code: SPTO 
10 Verify that a standing pretrial order has been added to the docket record as Filing and proceedings: Standing Pretrial Order Attached to Notice of Trial 
11. Click on the notice of set trial link and view the pdf is a 5 page document with the first page the notice of set trial, the next two pages are court/trial/case information and the last two pages being a form to fill out

Expected result
- [ ] Session has not been calendared and displays set calendar button
- [ ] Modal displays upon clicking of set calendar button “are you sure you want to set the calendar for this trial 
- [ ] On the trial session page, the selected trial now displays a column Notice issued
- [ ] pdf viewer displays and shows the notice of set trial and standing pretrial order document (for paper fillers only)
- [ ] Notice of Standing Pretrial Order Attached to Notice of Trial displays in Case’s docket record
- [ ] Notice of Standing Pretrial Order order code SPTO displays in Case’s docket record
- [ ] the document displays as a 5 page document with the first page the notice of set trial, the next two pages are court/trial/case information and the last two pages being a form to fill out 

#### Scenario 2 - When a calendar is set/automatically scheduled, all small cases on that session should be issued a Standing Pretrial Notice
1. Login as any internal user
2. Navigate to trial sessions and select a session
3. Verify this session has not been calendared, the set calendar button appears
4. Scroll down to the eligible cases section and click on the Set Calendar Button
5. Verify a modal displays” are you sure you want to set the calendar for this trial session?”
6. Click Yes, set calendar
7. Verify success message displays at top of session information screen
8. Verify after you submit trial a pdf viewer displays with a notice of set trial and the standing pretrial notice (for paper fillers only)
8. Click on a case’s docket number in the trial session
9. Verify that a Standing Pretrial Notice has been added to the docket record as Oder Code: SPTN 
10 Verify that a standing pretrial Notice has been added to the docket record as Filing and proceedings: Standing Pretrial Notice Attached to Notice of Trial 
11. Click on the notice of set trial link and view the pdf is a 3 page document with the first page the notice of set trial, the next two pages are court/trial/case information

Expected result
- [ ] Session has not been calendared and displays set calendar button
- [ ] Modal displays upon clicking of set calendar button “are you sure you want to set the calendar for this trial 
- [ ] On the trial session page, the selected trial now displays a column Notice issued
- [ ] pdf viewer displays and shows the notice of set trial and standing pretrial notice document (for paper fillers only)
- [ ] Notice of Standing Pretrial Notice Attached to Notice of Trial displays in Case’s docket record
- [ ] Notice of Standing Pretrial Notice order code SPTN displays in Case’s docket record
- [ ] the document displays as a 3 page document with the first page the notice of set trial, the next two pages are court/trial/case information 


#### Scenario 3 - If a case is manually added to a trial session before it is set/automatically scheduled, the case should not be issued a issued a "Notice of Trial" or a "Standing Pretrial Order/Notice" until that automatic scheduling
1. Login as any internal user
2. Locate a case that is ready for trial
3. Schedule the case above to an upcoming trial session that has not been calendared yet
4. Navigate to the docket record and Verify no notice is generated

Expected result
- [ ] No notice of set trial displays in the docket record 


#### Scenario 4 - If a case is manually added to a trial session after it is set/automatically scheduled, that case should be issued a "Notice of Trial" and a "Standing Pretrial Order/Notice" at the time the case is added to the trial session
1. Login as any internal user
2. Locate a case that is ready for trial
3. Schedule the case above to an upcoming trial session that has been calendared
4. Verify a pdf viewer displays with the Notice of trial and Standing Pretrial  Order/Notice documentation (for paper filers only)
5. Verify on the trial session selected displays a column Notice issued
6. Verify on the docket record a Standing Pretrial Order/Notice has been added and has  	a. order code SPTO or SPTN
	b. Filings and proceedings - Notice of Standing Pretrial Notice Attached to Notice or Notice of Standing Pretrial Notice Attached to order

Expected result
- [ ] Column displays on trial sessions page “notice issued” 
- [ ] Date displays under notice issued column for selected 
- [ ] Standing Pretrial Order/Notice has been added and has  	a. order code SPTO or SPTN
	b. Filings and proceedings - Notice of Standing Pretrial Notice Attached to Notice or Notice of Standing Pretrial   Notice Attached to order




#### Scenario 6 - Standing Pretrial Order/Notice needs to have signature applied to the judicial officer that's assigned to that trial session. System needs to auto-apply the signature of judicial officer
1. Login as any internal user
2. Navigate to trial sessions and select a session that has not been calendared
4. Scroll down to the eligible cases section and click on the Set Calendar Button
5. Verify a modal displays” are you sure you want to set the calendar for this trial session?”
6. Click Yes, set calendar
7. Verify success message displays at top of session information screen
8. Navigate to the docket record and click on the notice of set trial document link and verify that the standing pretrial order/notice has the signature of the judge assigned to the trial.

Expected result
- [ ] Session has not been calendared and displays set calendar button
- [ ] Modal displays
- [ ] success message displays
- [ ] the judge who is assigned to the trial signature displays on the standing pretrial notice/order


#### Scenario 7 - When the Standing Pretrial Order/Notice is issued, it is added to the Docket Record as a separate entry and served on the parties(Electronic Service)
1. Login as any internal user
2. Locate a case that is ready for trial
3. Schedule the case above to an upcoming trial session that has been calendared
4. Navigate to the docket record and Verify a notice of set trial is generated
5. Verify on the document that the served date appears at the bottom of the first page of the notice
6. On the Docket Record verify that the notice was served via the Served/Parties column in the docket record table

Expected result
- [ ] Notice of set trial displays in the docket record
- [ ] Served date appears at the bottom of the first page of the notice
- [ ] Served column displays date notice was served 
- [ ] Parties column displays who the document was served to



#### Scenario 8 - When the Standing Pretrial Order/Notice is issued, it is added to the Docket Record as a separate entry and served on the parties (paper service)
1. Login as any internal user
2. Locate a case that is ready for trial
3. Schedule the case above to an upcoming trial session that has been calendared
4. Navigate to the docket record and Verify a notice of set trial is generated
5. Verify on the document that the served date appears at the bottom of the first page of the notice
6. On the Docket Record verify that the notice was served via the Served/Parties column in the docket record table

Expected result
- [ ] Notice of set trial displays in the docket record
- [ ] Served date appears at the bottom of the first page of the notice
- [ ] Served column displays date notice was served 
- [ ] Parties column displays who the document was served to

**Comment by alsmith1** [comment]
---DRAFT WIREFRAMES---
![Screen Shot 2020-01-09 at 3.22.55 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/2224b115-a89d-4b21-bd86-0022c916a3d3)![Screen Shot 2020-01-09 at 3.23.28 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/6864cb16-6cd4-4ef9-a9e3-5a1ddaba45b3)![Screen Shot 2020-01-09 at 3.23.48 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/7a74eb48-52d1-43e7-840d-cb61c2558458)![Screen Shot 2020-01-09 at 3.24.00 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/e75e08aa-c460-4b47-aa3d-fc5294c348d7)![Screen Shot 2020-01-09 at 3.24.09 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/e04e8819-cef8-4099-ab58-47b9adaf54bb)![Screen Shot 2020-01-09 at 3.24.26 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/9f273b4b-14cb-43f0-96c0-2818fb07f01f)![Screen Shot 2020-01-09 at 3.24.35 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/9998f1fd-8795-42f8-b6a0-f59a2775bb4f)![Screen Shot 2020-01-09 at 3.24.45 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/576f0e32-531f-43bc-8048-a1a77dac5242)![Screen Shot 2020-01-09 at 3.24.53 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/441ed018-1398-4b23-9140-43dbc11a4c17)![Screen Shot 2020-01-09 at 3.25.05 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/65cd5ec2-d97c-44d1-ad07-d5ddb3e34aa1)![Screen Shot 2020-01-09 at 3.25.13 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/828207c6-b7db-4b19-8adf-15d3e0448527)

**Comment by JessicaMarine** [comment]
PO Review 1/29/2020:
(1) the SPTN is not generating any content (105-20 and 106-20 on staging); 
(2) the SPTO looks like it is signed by the Chief Judge -- it should be signed by the Judge assigned to the session (i noted this before); and
(3) the docket record does not indicate that the SPTO or SPTN has been served

**Comment by Tinabuck5** [comment]
I tested each scenario (minus a scenario 5 which appears missing from the testing script) and everything is working as it should.  The SPTN is now generating (see 118-20 and 119-20).  The SPTO is now signed by the appropriate Judge (122-20) and service is recorded properly on both the SPTO and SPTN. (as shown on all test cases mentioned above.

**Comment by JessicaMarine** [comment]
PO Review 2.5.2020: I'm experiencing some weird bug issues.  In 118-20 on staging, I logged in a respondent1 and tried to file an Answer.  The Answer went through and shows on the docket record, but respondent1 is not associated with the case -- case not showing on dashboard and respondent info not under Case Information.  I was trying to do this to test the respondent contact info being added to the content in the SPTN, but I cannot get it to work.

**Comment by Tinabuck5** [comment]
I just tried to log in as respondent1 several times and when I do, I quickly see a displayed error message and it kicks me out.
