### ISSUE TITLE
Fee information on Notice of Receipt of Petition

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3911]
As the Court, in order to not pass inaccurate information to the parties, we need the Notice of Receipt of Petition to accurately reflect information on the case.

The Notice of Receipt of Petition currently indicates that the filing fee has been paid *regardless* if is has or has not.  We need remove that content from the Notice of Receipt of Petition.

## Acceptance Criteria
* We need remove the fee payment content from the Notice of Receipt of Petition.

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (#4404)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (#4404)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by alsmith1** [comment]
## Test scenarios
#### Scenario 1 - Filing fee payment content does not display on the Notice of Receipt of Petition (external users)
1. Log in as a petitioner
2. Navigate to one of your cases
3. Navigate to the docket record case information tab
4. Click on the Printable confirmation link on the petition details tile
5. Verify that pdf view opens with the Notification of receipt of petition
6. Verify that after The Court received and filed your petition on [date] and served it on respondent on [date] filing fee paid does not display.

Expected result
- [ ] Printable confirmation link on the petition details tile displays
- [ ] Pdf view opens with the Notification of receipt of petition
- [ ] After The Court received and filed your petition on [date] and served it on respondent on [date] filing fee paid does not display

#### Scenario 2 - Filing fee payment content does not display on the Notice of Receipt of Petition (internal users)
1. Log in as a court user
2. Navigate to a case
3. Navigate to the docket record case information tab
4. Click on the Printable confirmation link on the petition details tile
5. Verify that pdf view opens with the Notification of receipt of petition
6. Verify that after The Court received and filed your petition on [date] and served it on respondent on [date] filing fee paid does not display.

Expected result
- [ ] Printable confirmation link on the petition details tile displays
- [ ] Pdf view opens with the Notification of receipt of petition
- [ ] After The Court received and filed your petition on [date] and served it on respondent on [date] filing fee paid does not display

**Comment by alsmith1** [comment]
![Screen Shot 2020-01-31 at 11.12.14 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/2f3d4b1e-4d3c-490e-b32d-c34e5b84ad2c)

**Comment by alsmith1** [comment]
![address1.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/817054dd-b293-48db-bdb4-93bf4914dec3)![envelope1.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/9cf73faf-bc68-431c-bbcb-b56aabe7b994)

**Comment by JessicaMarine** [comment]
I was trying to test #3911 but I think it has been affected by the work on #4296 -- the receipt doesn't appear in the case info tab until the petition is served.  And, I think we have broken the Run IRS Service script.  Is there another way I can test this, or do i need to wait until service is restored?
