### ISSUE TITLE
CMS User: Basic Opinion Search

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3913]
As a CMS User, to quickly locate an opinion, I need the ability to search just opinions.

## Acceptance Criteria ##
* CMS User (both internal Court User and the public) has the ability to search Court's opinions based on keyword (Basic search)
* Opinions in sealed cases show in results; Don't need to display the sealed icon
* Only served Opinions are visible in search results
]* Results display page count in results
Security requirement - API only returns data as specified in design. (Write test scenarios around only returning specific data)
* Ensure uploaded orders are also searchable (pdf content has been indexed)

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Mobile design needs to be reconsidered for opinion (and order) search. Design is not optimal for public and parties in the case. Story backlogged to reconsider overall design for mobile search. #5025
* For opinions in sealed cases, anything security related will be handled manually by the person drafting the document
* Note: See #4814 for PDF content scraping solution notes. Since uploaded orders requires the same PDF content scraping, should we do as part of this story or create a separate story?

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt (#5181) 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by JessicaMarine** [comment]
Court's current public search tool for opinions:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/18b282e2-9066-4dea-b474-ecf1e543acf0)

**Comment by alsmith1** [comment]
![Screen Shot 2020-03-16 at 4.03.32 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/e3832505-57e9-45d8-8ff9-29fae93c8c91)![Screen Shot 2020-03-16 at 4.03.40 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/785d4728-c57b-4e30-833c-3b2c12f75981)![Screen Shot 2020-03-16 at 4.03.47 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/9f3155b8-82d7-4584-b1d7-37f0afb254cf)

**Comment by klohman** [comment]
### Updated Design - Advanced Search > Opinions tab 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/580b27ba-5ee8-48cb-a2e1-5fa3a74da52a)

#### Error message (Docket number and case title entered) 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/90617893-4e00-494f-8a39-02c2c0d1c706)


### Design Notes:

#### Search Criteria 
**Keyword**
* is required
* searches for matches in text in opinion title and  body of Opinion document 

**Docket Number**
* is optional 
* limits scope of keyword search to the entered docket number (keyword + within docket xxx-20) 
* docket number must be an exact match 
* if user enters both a docket number and case title, error message displays 

**Case Title** 
* is optional 
* Case title  can be case title or Petitioner's Name
* Can be exact match or partial match 
* Searches for matches in case caption AND petitioner contact information (primary 1 and 2) 
* limits scope of keyword search to cases with exact or partial matching Case Title 
* if user enters both a docket number and case title, error message displays 


**Opinion Type** 
* is optional 
* Opinion type dropdown includes T.C. Opinion, Memorandum Opinion, Summary Opinion
* Limits scope of keyword search to opinion documents with a matching event code 

**Judge**
* is optional 
* Dropdown Includes all judges past and present 
* Limits scope of keyword search to opinion documents with a matching judge (Judge’s Name selected on Add Docket Entry screen)

**Date range**
* field group is optional 
* Limits scope of keyword search to opinions with matching Filed date within entered date range 
* Scope includes start and ending date 
* Date format must be complete: MM/DD/YYYY
* If start date is entered, but end date is left blank - copy start date to end date field and search 

#### Search criteria relevancy 
**Keyword-only**
* keyword /phrase -  exact match 
* keyword/ phrase partial match 

**Keyword + docket number + [judge, date]**
* keyword exact match + docket exact match + judge exact match + date exact match
* keyword partial match + docket exact match  + judge exact match + Date exact match 
* keyword exact match + docket exact match + judge exact match + date range match - sort by date oldest to newest 
* keyword partial match + docket exact match  + judge exact match + Date range match - sort by date oldest to newest

**Keyword + case title + [judge, date]**
* keyword exact match + case title exact match + judge exact match + date exact match 
* keyword partial match + case title exact match + judge exact match + date exact match 
* keyword exact match + case title partial match + judge exact match + date exact match 
* keyword partial match + case title partial match + judge exact match + date exact match 
* keyword exact match + case title exact match + judge exact match + date range match  - sort by date oldest to newest 
* keyword partial match + case title exact match + judge exact match + date range match  - sort by date oldest to newest 
* keyword exact match + case title partial match + judge exact match + date range match  - sort by date oldest to newest 
* keyword partial match + case title partial match + judge exact match + date range match  - sort by date oldest to newest 

**Keyword + judge**
* keyword exact match + Judge exact match 
* keyword partial match + Judge exact match

**Keyword + date**
* keyword exact match + date exact match 
* keyword partial match + date exact match 
* keyword exact match + date range match - sorted by date oldest to newest 
* keyword partial match + date range match - sorted by date oldest to newest
 
#### Search Results Display
* display up to 25 matching results on search 
* If more than 25 matching results exists, displays "Load 25 More" button

**Results header** 
* display total number of matching results 

**Docket number** 
* links to Case Detail page 

**Case title**
* displays matching / partial matching case title 

**Opinion Type**
* displays Document Type for opinion (T.C. Opinion, Memorandum Opinion, Summary Opinion) 
* link opens Opinion PDF in new tab 

**Judge**
* displays Judge associated with the Opinion (Judge’s Name selected on Add Docket Entry screen)

*Pages* 
* Pages are the number of pages that makes up the Opinion PDF

**Date**
* Displays Filed date for Opinion 

**Load More button**
* On click, display next 25 matching results 
* If more than the next 25 results exists,  display "Load 25 More" button
* Hide "Load 25 More" button when no hidden results exist

**Comment by alsmith1** [comment]
#### Scenario 1 - All CMS internal or external users can see the search functionality of Opinions
1. Log in as an internal/external user
2. Click on the Advanced Search link
3. Click on the Opinions tab

Expected result
- [ ] Opinions tab displays on advanced search screen
- [ ] Enter Keyword or Phrase displays as a header with Search for ... above the search box
  
#### Scenario 2 - Public can see the search functionality of Court issued Opinions
1. Navigate to the public site’s Search page
2. Click on the Order tab

Expected result
- [ ] Order tab displays on advanced search screen
- [ ] Enter Keyword or Phrase displays as a header with Search for ... above the search box

**All test cases should be performed as internal user/ external user/ public user**
Test scenario set up
### Test set up 1
1. Login as ADC
2. 2. Navigate to Case xxx-20
3. 3. Create and upload a T.C. Opinion
4. Login as a docket clerk
5. Navigate to case xxx-20
6. Sign, the opinion doc and add to docket entry as a T.C. Opinion
### Test set up 2
1. Login as Judge Buch
2. Navigate to Case xxx-20
3. Create and upload a Summary Opinion
4. Navigate to Draft Documents and sign the Opinion
5. Login as a docket clerk
6. Navigate to case xxx-20
7. QC the Opinion and add to docket entry as a Summary Opinion
### Test set up 2a
1. Login as Judge Buch
2. Navigate to Case xxx-20
3. Create a Summary opinion with keyword “star” in the body text and upload a Summary Opinion
4. Navigate to Draft Documents and sign the Opinion
5. Login as a docket clerk
6. Navigate to case xxx-20
7. QC the Opinion and add to docket entry as a Summary Opinion
### Test set up 3
1. Login as a member of Judge Buch’s Chambers
2. Navigate to Case xxx-20
3. Create and upload a Memorandum Opinion
4. Login as Judge Buch
5. Navigate to Draft Documents and sign the Opinion
6. Login as a docket clerk
7. Navigate to case xxx-20
8. QC the Opinion and add to docket entry as a Memorandum Opinion
### Test set up 4 (Sealed Case)
1. Login as a member of Judge Buch’s Chambers
2. Navigate to Case xxx-20
3. Create and upload a Summary Opinion
4. Login as Judge Buch
5. Navigate to Draft Documents and sign the Opinion
6. Login as a docket clerk
7. Navigate to case xxx-20
8. QC the Opinion and add to docket entry as a Summary Opinion
9. Navigate to Case Information and seal the case

#### Scenario 3 - All users search by keyword 
1.  Test Setup 1
2. Navigate to Search
3. Click on the Opinion tab
4. Enter in a keyword T.C. Opinion
5. Click search

Expected result
- [ ] T.C. Opinion for Case xxx-20 displays in results 
- [ ] Results Count displays number of results found from search
- [ ] Verify the table displays with the following columns
- Docket number
- Case title
- Opinion Type
- Pages
- Date
- Judge
- [ ] Order column displays “ T.C. Opinion Judge Buch (listed as full concatenated title)
- [ ] load 25 more button displays below the table if header displays over 25 results


#### Scenario 4 - Users should opinion results even if they are part of a sealed case
1. Test setup 4 (Sealed Case)
2. Navigate to Search 
3. Click on the Order tab
4. Enter in keyword (Summary opinion)
5. Click search
6. Check table for case (xxx-20)

Expected result
- [ ]  Summary Opinion docket number (xxx-20) displays in results 

#### Scenario 5 - Opinions that have been served and added to docket record are indexed and searchable
1. Login as a member of Judge Buch’s Chambers
2. Navigate to Case xxxa-20
3. Create and upload a Memorandum Opinion
4. Login as Judge Buch
5. Navigate to Draft Documents and sign the Opinion
6. Login as a docket clerk
7. Navigate to case xxxa-20
8. QC the Opinion and add to docket entry as a Memorandum Opinion
9. Navigate to Case xxxb-20
10. Create and upload a Memorandum Opinion
11. Login as Judge Buch
12. Navigate to Draft Documents and sign the Opinion
13. Login as a docket clerk
14. Navigate to case xxxb-20
15. QC the Opinion and add to docket entry as a Memorandum Opinion 
16. Navigate to Advanced Search > Opinions tab
17. Enter “Show Cause” in keyword
18. Click Search 
Expected results 
- [ ] Memorandum for case xxa-20 is displayed in results 
- [ ] Memorandum for case xxb-20 is displayed in results 

#### Scenario 6 -Court orders that are in draft documents are not searchable
1. Login as a member of Judge Buch’s Chambers
2. Navigate to Case xxxa-20
3. Create and upload a Memorandum Opinion
4. Login as Judge Buch
5. Navigate to Draft Documents and sign the Opinion
6. Login as docket clerk
7. Navigate to Advanced Search > Opinion tab 
8. Enter “Memorandum” in keyword
Expected results 
- [ ] Memorandum Opinion for case xxa-20 does not display in search results 

#### Scenario 7 -Court orders that are added to docket record but have not been served are not searchable
* Scenario 5 
* Login as docket clerk 
* Navigate to Case xxa-20 - Case Detail > In Progress > Draft Documents
* Click on Memorandum Opinion  
* Click Add Docket Entry 
* Complete Add Docket Entry Form 
* Click Save Entry button 
* Login as [internal user] 
* Navigate to Advanced Search > Opinions tab 
* Enter “Decision” in keyword 
Expected results 
- [ ] Memorandum Opinion for case xxa-20 does not display in search results 

#### Scenario 12 Search for Opinion with keyword in title 
1. Test Setup 2
5. Navigate to Search
6. Click on the Order tab
7. Enter in a keyword Summary Opinion
8. Click search

Expected result
- [ ] Opinion Documents with keyword “Summary Opinion” in the title are listed in the table

#### Scenario 13 Search for opinion with keyword in body copy 
1. Test Setup 2a
5. Navigate to Search
6. Click on the Order tab
7. Enter in a keyword Star
8. Click search

Expected result
- [ ] Opinion Documents that have keyword “Star” in the body copy are listed in the table

#### Scenario 14) User views Order PDF from search results 
* Navigate to Search 
*Enter in a keyword Memorandum Opinion
*Click search
* Click on a Memorandum Opinion link from results table 
Expected results 
- [ ] Order PDF opens in new tab

#### Scenario 15) User does not see court-issued documents other than Opinions in search results 
* Test Setup 2 
* Test Setup 1
* Navigate to Advanced Search > Opinion 
* Enter keyword Memorandum
* Click Search 

Expected results
- [ ] Opinion and Memorandum Opinion document for case xxb-20 displays in results 
- [ ] Memorandum Opinion document for case xxx-20 does not display in results   

Scenario 16 - User clicks search without entering keyword
* Navigate to Advanced Search > Opinion
* Click Search
 Expected results
- [ ] form is not submitted
- [ ] Page-level error message displays
- [ ] Field-level error message displays on keyword field “Please correct the following errors: Enter a keyword”

Scenario 17 - User clicks clear search link
* Navigate to Advanced Search > Opinion
* Enter keyword Memorandum
* Click Clear Search Link 
Expected results
- [ ] form is not submitted
- [ ] Form clears/resets

**Comment by alsmith1** [comment]
dev has been set up with test cases for this story as of 4-13-2020

xx1-20 --> 105-20
xx2-20 --> 107-20
xx3-20 --> 108-20
xx4-20 --> 109-20
xx5-20 --> 110-20
xx8-20 --> 114-20
xx9-20 --> 113-20
x10-20 --> 115-20
