### ISSUE TITLE
Docket Clerk: Ability to modify docket entry

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3914]
As a Docket Clerk, in order to make sure that the Docket Record is correct, I need the ability to modify any entry in the Docket Record.

For MVP, a Docket Clerk will need the ability to manually manipulate the Docket Record.  This includes manually putting something in the action status column, correcting typo w/o generating a notice of docket change, etc.  In general, the Docket Clerk should be able to edit any cell within any Docket Record entry.

## Acceptance Criteria: ##
* Docket Clerk [permission based] needs the ability to edit the Filings and Proceedings, Filed By, Action, ~~Served Date~~, and Served Parties cells in the Docket Record.
* The new text overwrites the old text and does not need to create any Notice of Docket Change.

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* This story doesn't cover changing PDFs, including those that are system-generated

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Jojo)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (Matt)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Matt)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Jojo)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Jojo)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by alsmith1** [comment]
---DRAFT---

## Test scenarios
#### Scenario 1 - Docket Clerk [permission based] needs the ability to edit the Filings and Proceedings, Filed By, Action and Served cells in the Docket Record
1. Login as a docket clerk
2. Navigate to a docket record
3. Click the edit link on the far right of a docket entry that needs to be updated/changed
4. Verify that modal appears asking what parts of the docket record you would like to update
5. Make edits to one or all of the fields (filings and proceedings, filed by, action, served)
6. Click the update docket record button
7. Verify that a success message displays at the top of the docket record screen stating your changes have been saved
8. Verify that the updates you made display correctly in the docket record

Expected result
- [ ] Modal appears asking what parts of the docket record you would like to update
- [ ] Text fields in Modal are pre populated with what is currently in the docket record
- [ ] Edits can be made to one or all fields
- [ ] Success message displays at the top of the docket record screen stating your changes have been saved
- [ ] The updates you made display correctly in the docket record

#### Scenario 2 - The new text overwrites the old text and does not need to create any Notice of Docket Change
1. Login as a docket clerk
2. Navigate to a docket record
3. Click the edit link on the far right of a docket entry that needs to be updated/changed
4. Verify that modal appears asking what parts of the docket record you would like to update
5. Make edits to one or all of the fields (filings and proceedings, filed by, action, served)
6. Click the update docket record button
7. Verify that a success message displays at the top of the docket record screen stating your changes have been saved
8. Verify that the updates you made display correctly in the docket record
9. Verify on the docket record there is no new entry stating notice of docket change

Expected result
- [ ] Modal appears asking what parts of the docket record you would like to update
- [ ] Text fields in Modal are pre populated with what is currently in the docket record
- [ ] Edits can be made to one or all fields
- [ ] Success message displays at the top of the docket record screen stating your changes have been saved
- [ ] The updates you made display correctly in the docket record
- [ ] There is no new entry to the docket record stating notice of docket change

**Comment by alsmith1** [comment]
![Screen Shot 2020-01-20 at 10.45.59 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/c51a8fc3-0c30-4aad-925c-cbd4d7a266a8)![Screen Shot 2020-01-20 at 10.48.16 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/e3f29bae-3d8e-4855-9e2a-3016654ca88a)![Screen Shot 2020-01-20 at 10.48.05 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/c6b24886-e05f-424a-92b4-787ad374ab71)

**Comment by Tinabuck5** [comment]
Scenario 1:  Tested docket nos. 107-20 Administrative Record and 118-20 Motion for continuance.  I was able to edit filed date, action and served.  It did not allow me to change the filed by.  Please note:  that when a new cover sheet is created the received date is changing to the date of the edit.  Shouldn't it be the same date as the document is filed?  Also on docket nos. 119-20 and 122-20 the filed dates were changed a new cover sheet was created and the titles of the documents changed.  For example the title before amended the filed date was "Request for Place of Trial at Denver, CO  the title changed to "Request for Place of Trial at (Place)

Scenario 2: The new text overwrites the old text and displays properly.

Scenario 3: Action column allows for free text and is saved correctly

Scenario 4: Edits made to the Filed date field does generate a new cover sheet however, the title of the document changes on the cover sheet as does the received date.  Date edits display correctly  and everything else in this scenario works as expected.

Scenario 5:  Works as stated, once document was qc'd the edit link/button did not display.

Scenario 6:  If a document is not qc'd, no edit link/button is displayed.

**Comment by JessicaMarine** [comment]
Feedback from Tina:

I re-tested yesterday….see comments below.

RE-TESTED 2/12/20
Please note:  This did NOT happen before but when I hit the edit button the filed date changes to the current date even though I'm not changing the filed date.

Scenario 1:  Test case 118-20; I changed the filed date of entry no. 2 from 2/6/20 to 2/10/20 on Request for Place of Trial.  The Filed date updated on the cover sheet but the Received date did not update.  Other than that the edits reflected on the record.

Scenario 2: The new text does overwrite the old text and does not initiate a notice of docket change.

Scenario 3:  Action column allows for free text and is saved correctly.

Scenario 4:  I entered a "notice of change of address and telephone number in case 130-20.  I uploaded a document. the filed date that I entered was 2/11/20.  The cover sheet displays the filed date as 2/13/20???  I clicked edit to attempt to edit the filed date and the date displayed shows 2/13/20 but should display 2/11/20.  I edited the filed date to 2/12/20 saved the edit.  The filed date shows the correction on the docket record.  When I clicked on the document to verify the cover sheet reflected the correct filed date, both the received and filed dates show 2/13/20.  It seems to be changing to the current date.

Scenario 5:  Works as stated
Scenario 6:  Works as stated
