### ISSUE TITLE
Page Numbers on Docket Record

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#4429]
As a CMS user, so that I know how large a document is before I open it, I need to see how many pages are in the document.

## Acceptance Criteria
* All CMS user can see how many pages are in a document before opening it.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by alsmith1** [comment]
![Screen Shot 2020-05-26 at 12.03.48 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/c8bbac6e-3032-4a0e-bc4f-0798bfec98d6)
Page numbers are added to the docket record and display the actual amount of pages included in the document
All CMS users can see how many pages are in a document before opening it.

**Comment by alsmith1** [comment]
Test Scenarios

### Scenario 1 - A CMS internal or external users can see  see how many pages are in a document before opening it on the docket record. (Desktop internal user)
1. Log in as an internal court user
2. Navigate to a case’s docket record
3. Click on one of the document links 
Expected result
- [ ] Docket record table displays the following columns 
        * NO
	* Date(mm/dd/yy)
        * Event
        * Date 
	* Filings and proceedings
	* Pages
	* Filed By Action
	* Served
	* Parties
- [ ] Page column displays how many pages are in the document
- [ ] Document opens and displays page count that matches the count on docket record


### Scenario 2 - A CMS internal or external users can see  see how many pages are in a document before opening it on the docket record. (Desktop external user)
1. Log in as an external court user
2. Navigate to a case’s docket record
3. Click on one of the document links 
Expected result
- [ ] Docket record table displays the following columns 
        * NO
	* Date(mm/dd/yy)
        * Event
	* Filings and proceedings
	* Pages
	* Filed By 
	* Action
	* Served
	* Parties
- [ ] Page column displays how many pages are in the document
- [ ] Document opens and displays page count that matches the count on docket record

### Scenario 3 - A public users can see  see how many pages are in a document before opening it on the docket record. (Desktop public user)
1. Log in as member of the public
2. Search for a case 
3. Click on one of the document links 
Expected result
- [ ] Docket record table displays the following columns 
        * NO
	* Date(mm/dd/yy)
        * Event
	* Filings and proceedings
	* Pages
	* Filed By 
	* Action
	* Served
	* Parties
- [ ] Page column displays how many pages are in the document
- [ ] Document opens and displays page count that matches the count on docket record

### Scenario 4 - A CMS internal or external users can see  see how many pages are in a document before opening it on the docket record. (Mobile internal user)
1. Log in as an internal court user
2. Navigate to a case’s docket record
3. Click on one of the document links
Expected result
- [ ] Document detail page loads and displays the following data 
	* Date(mm/dd/yy)
	* Pages
	* Filed By
	* Action
	* Served
	* Parties
- [ ] Page  field displays how many pages are in the document
- [ ] Document opens and displays page count that matches the count on docket record

### Scenario 5 - A CMS internal or external users can see  see how many pages are in a document before opening it on the docket record. (Mobile external user)
1. Log in as an external user
2. Navigate to a case’s docket record
3. Click on one of the document links 
Expected result
- [ ] Document detail page loads and displays the following data 
	* Date(mm/dd/yy)
	* Pages
	* Filed By
	* Action
	* Served
	* Parties
- [ ] Page  field displays how many pages are in the document
- [ ] Document opens and displays page count that matches the count on docket record

### Scenario 6 - A CMS internal or external users can see  see how many pages are in a document before opening it on the docket record. (Mobile external user)
1. Log in as member of the public
2. Search for a case
3. Click on one of the document links 
Expected result
- [ ] Document detail page loads and displays the following data 
	* Date(mm/dd/yy)
	* Pages
	* Filed By
	* Action
	* Served
	* Parties
- [ ] Page  field displays how many pages are in the document
- [ ] Document opens and displays page count that matches the count on docket record
