### ISSUE TITLE
Parties: Display open and closed cases separately; add pagination

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4493]
As a party in a case (petitioner, practitioner, IRS attorney), so that I may easily navigate my cases, I need open and closed cases differentiated on my dashboard

## Acceptance Criteria
* Open and closed cases display separately on the petitioner, practitioner and IRS attorney dashboard
* System user can view cases in manageable quantities; page loads quickly (pagination?)

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* There's an item in the refactoring backlog to try to speed up load:
"Speed up dashboard network requests - getConsolidatedCasesByUser taking 10 seconds with only 30 cases locally" If we can speed up by doing the refactoring, may not need to have pagination. 
* Was this story created to limit the number of cases or because the system will not quickly load a lot of cases? Loading

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by alsmith1** [comment]
![Screen Shot 2020-05-27 at 10.49.24 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/67f02996-c31d-4081-8513-a216c2e354ec)


![Screen Shot 2020-05-27 at 10.49.37 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/1156ccab-7daf-4fcc-a64c-811eed367e30)

**Comment by alsmith1** [comment]
Test Scenarios

### Scenario 1 - A petitioner, practitioner, IRS attorney sees open and closed cases separately in tabs on dashboard 
1. Log in as a petitioner, practitioner, or IRS attorney 
Expected result
- [ ] Two tabs display on the screen
	- Open Cases
	- Closed Cases
- [ ] Open Cases tab is set as default
- [ ] open cases tab displays and case which is not marked as closed
- [ ] closed cases tab displays any cases listed in the system as closed


### Scenario 2 - A petitioner, practitioner, IRS attorney sees total cases in footer of cases table
1. Log in as a petitioner, practitioner, or IRS attorney 
Expected result
- [ ] Grey footer bar displays on bottom of table
- [ ] Case count displays the amount of cases displayed in the footer right
- [ ] Case count displays as (1-# of # cases)

### Scenario 3 - A petitioner, practitioner, IRS attorney sees pagination and total cases in footer of cases table (for users with more then 20 open/closed cases)
1. Log in as a petitioner, practitioner, or IRS attorney with more then 20 cases
Expected result
- [ ] Grey footer bar displays on bottom of table
- [ ] pagination controls displayed in the footer left
- [ ] pagination controls include
	-  First
         - Previous
         - #’s in order (numbers will display as needed)
         - Next          - Last
- [ ] Grey footer bar displays on bottom of table
- [ ] Case count displays the amount of cases displayed in the footer right
- [ ] Case count displays as (1-# of # cases)

### Scenario 4- A petitioner, practitioner, IRS attorney sees pagination and total cases in footer of cases table (for users with more less than 20 open/closed cases)
1. Log in as a petitioner, practitioner, or IRS attorney with less then 20 cases
Expected result
- [ ] Grey footer bar displays on bottom of table
- [ ] pagination controls are NOT displayed in the footer left
- [ ] Grey footer bar displays on bottom of table
- [ ] Case count displays the amount of cases displayed in the footer right
- [ ] Case count displays as (1-# of # cases)

**Comment by JessicaMarine** [comment]
6/13/2020 PO Review:
The `Load 20 more` button does not dynamically change to reflect less then 20 when there are less than 20 more to load.  In staging, I had 42 open cases. With 40 displaying, the button still said `Load 20 more`.  I'm happy to do whatever is easiest here -- if it makes sense to just change the button to `Load more` versus `Load # more` so that it doesn't have to dynamically change, I'm fine with that.





3:45
The button does disappear when all the cases are loaded, so i think Load more would work
