### ISSUE TITLE
Court users: Correspondence File

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4658]
As the Court, in order to have a place to store case-related documents that are not added to the docket record, I need a separate area where these documents can be stored.

There are certain case-related documents (e.g., scanned payment receipt, cover letters included with filings, internal memos, etc.) that are not added to the case's docket record.  Court users need to be able to see these items at the case level.  We currently call this the "correspondence" file

## Acceptance Criteria
* Petitions/Calendar Clerks and Docket Clerks should have the ability to add (upload) non-docket record documents to a dedicated space within a case [Note: direct upload is okay for MVP; no need for direct scan]
* Petitions/Calendar Clerks and Docket Clerks should have the ability to remove document previously added to this space
* All Court users should be able to view these documents
* No externals can view correspondence documents

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (#5274 Mrinalini/Jojo)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by alsmith1** [comment]
![Screen Shot 2020-05-12 at 12.21.25 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/5cf4c8f3-21ab-4bcd-b92c-375ae7e7fa15)![Screen Shot 2020-05-12 at 12.21.33 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/98e235bf-a1f8-4836-9198-8ec279e4c9b8)![Screen Shot 2020-05-12 at 12.21.40 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/6ccba92e-73fa-433f-913d-d7058b557a25)![Screen Shot 2020-05-12 at 12.21.45 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/abe4eaee-11a8-4d94-906a-3a1530c57ea5)

**Comment by alsmith1** [comment]
Draft test scenarios:

### Scenario 1 - Petitions and Docket Clerk’s should be able to add a correspondence file by selecting the button under the actions menu
1. Log in as a petitions or a docket clerk
2. Navigate to a docket record
3. Click on the actions button dropdown
4. Verify Add Correspondence File link appears

Expected result
- [ ] Add Correspondence File link displays in dropdown list

### Scenario 2 - Petitions/Calendar Clerks and Docket Clerks should have the ability to add (upload) non-docket record (access from actions menu)
1. Log in as a petitions or a case
2. Navigate to a docket record
3. Click on the actions button dropdown
4. Click on Add Correspondence File link
5. Enter in a Correspondence description
6. Click choose file button and select a document to upload
7. Click finish

Expected result
- [ ] Add Correspondence File link displays in dropdown list
- [ ] Add Correspondence File page displays
- [ ] A green circle with a checkbox in it displays next to uploaded file name
- [ ] A change link appears next to the uploaded file name
- [ ] page redirects to the case’s correspondence tab and displays on the table
- [ ] success message displays

### Scenario 3 - Petitions/Calendar Clerks and Docket Clerks should have the ability to add (upload) non-docket record (access from correspondence tab)
1. Log in as a petitions or a docket clerk
2. Navigate to a case
3. . Navigate to a case’s correspondence tab
3. Click on Add Correspondence File link
4. Enter in a Correspondence description
5. Click choose file button and select a document to upload
6. Click finish

Expected result
- [ ] Add Correspondence File link displays in dropdown list
- [ ] Add Correspondence File page displays
- [ ] A green circle with a checkbox in it displays next to uploaded file name
- [ ] A change link appears next to the uploaded file name
- [ ] page redirects to the case’s correspondence tab and displays on the table
- [ ] success message displays


### Scenario 43- Petitions/Calendar Clerks and Docket Clerks should have the ability to remove document previously added to this space
1. Log in as a petitions or a docket clerk
2. Navigate to a case’s correspondence tab
3. Click on the delete link for a document in the table
4. Click Yes, Delete

Expected result
- [ ] Correspondence tab opens and displays any correspondence files in the table below
- [ ] Correspondence files are ordered by date filed
- [ ] are you sure you want to delete this document modal appears
- [ ] Document is removed from table


### Scenario 5 - Petitions and Docket Clerks should have the ability to edit document previously added to this space
1.  Log in as a petitions or a docket clerk
2. Navigate to a case’s correspondence tab
3. Click on the delete link for a document in the table
4. Make a change to the Correspondence description
5. Click change button and select a new document to upload
6. Click save

Expected result
- [ ] Correspondence tab opens and displays any correspondence files in the table below
- [ ] Correspondence files are ordered by date filed
- [ ] Edit Correspondence file page displays with view of pdf
- [ ] Document record in the correspondence table is updated 
- [ ] success message displays

### Scenario 6 - All Court users should be able to view these documents
 1. Log in as a court user who is not a petitions/docket clerk
2. Navigate to a case’s correspondence tab
3. Click one of the document links

Expected result
- [ ] Correspondence tab opens and displays any correspondence files in the table below
- [ ] Correspondence files are ordered by date filed
- [ ] Edit and Delete links do not display
- [ ] Document view page displays
- [ ] No Edit/delete links display

### Scenario 7 - No externals can view correspondence documents
1. Login as a petitioner/ private practitioner or IRS practitioner
2. Navigate to a case

Expected result
- [ ] Correspondence tab does not display in the tased case menu

### Scenario 8 - Error messaging from Add / Edit Correspondence File pages
1. Log in as a petitions or a docket clerk
2. Navigate to a case
3. . Navigate to a case’s correspondence tab
3. Click on Add Correspondence File link
4. Click finish

Expected result
- [ ] Page does not submit
- [ ] error message at the top of the page displays
    - If no correspondence description error displays “Enter a description”
    - If no file uploaded error displays “Upload a document”
- [ ] error message at field level displays
    - If no correspondence description error displays “Enter a description”
    - If no file uploaded error displays “Upload a document”
