### ISSUE TITLE
Petitions Clerk: Revamp Petition Flow *EDIT in PROGRESS* (Paper)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4761]
Story for edit in progress - paper petition

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
- [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
- [ ] Automated test scripts have been written
- [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Code refactored for clarity and to remove any known technical debt 
 - [ ] Deployed to the dev environment
- [ ] Deployed to the stage environment

**Comment by mariahkannenberg** [comment]
Edit In-Progress Petition/Parties
Edit In-Progress Petition/Case Info
Edit In-Progress Petition/IRS Notice
Edit In-Progress Petition/PDFs (View Only)

**Comment by alsmith1** [comment]
Draft Test Scenarios 

#### 1) User views Saved Petition 
Navigate to My Document QC > In Progress 
Click into saved Petition 
Expected results 
[ ] App navigates to Petition - Review screen 
[ ] Header displays case information (Docket Number, Case Caption, etc.) 

#### 2) Edit In Progress/Saved for Later doc of Petitioner and Spouse petition 
Follow steps from #1 above
Review the data on the screen
Click on the edit link on the parties tab
Verify when page loads it opens to the parties tab
Update the petitioner’s address
Verify that the Spouse’s address updates
Make a change to the Spouse’s phone number
Verify the Petitioner’s phone number does not change
Click review petition
Verify the updated petitioner contact information displays in the second column of the parties tile
Verify the updated spouse contact information displays in the third column of the parties tile
Expected results 
[ ] Review page loads with header displaying case information (Docket Number, Case Caption, etc.) 
[ ] Page Displays with values entered in form
[ ] After click page redirects to the petition form parties tab
[ ] Petitioner’s address is updated, spouse’s address is updated
[ ] Spouse’s phone number is updated, Petitioner’s phone number stays the same
[ ] Page Navigates to the Review Petition Screen
[ ] Petitioner and Spouse's address display new information entered
[ ] Spouse’s phone number is updated but Petitioner’s phone stays same as before
#### 3) Edit In Progress/Saved for Later doc of Corporation petition 
Follow steps from #1 above
Review the data on the screen
Click on the edit link on the parties tab
Verify when page loads it opens to the parties tab
Make a change to the business name
Add in Suite 101 in Address line 2
Click review petition
Verify the updated petitioner contact information (business name and address line 2) displays in the second column of the parties tile
Expected results 
[ ] Review page loads with header displaying case information (Docket Number, Case Caption, etc.) 
[ ] Page Displays with values entered in form
[ ] After click page redirects to the petition form parties tab
[ ] Page Navigates to the Review Petition Screen
[ ] Business Name and address line 2 display new information entered

#### 4) Edit In Progress/Saved for Later doc of Petitioner petition 
Follow steps from #1 above
Review the data on the screen
Click on the edit link on the parties tab
Verify when page loads it opens to the parties tab
Make a change to the city
Sdd in Suite 101 in Address line 2
Click review petition
Verify the updated petitioner contact information (Address line 2 and City) displays in the second column of the parties tile
Expected results 
[ ] Review page loads with header displaying case information (Docket Number, Case Caption, etc.) 
[ ] Page Displays with values entered in form
[ ] After click page redirects to the petition form parties tab
[ ] Page Navigates to the Review Petition Screen
[ ] Address line 2 and city display new information entered

#### 5) Edit In Progress/Saved for Later doc of Trust petition 
Follow steps from #1 above
Review the data on the screen
Click on the edit link on the parties tab
Verify when page loads it opens to the parties tab
Make a change to the Name of Trust
Add in Suite 101 in Address line 2
Click review petition
Verify the updated petitioner contact information (Name of trust and address line 2) displays in the second column of the parties tile
Expected results 
[ ] Review page loads with header displaying case information (Docket Number, Case Caption, etc.) 
[ ] Page Displays with values entered in form
[ ] After click page redirects to the petition form parties tab
[ ] Page Navigates to the Review Petition Screen
[ ] Name of trust and address line 2 display new information entered
[ ] Verify on the case info tile that the case caption has been updated as well
#### 6) Edit In Progress/Saved for Later doc of Petitioner and Spouse petition to Petitioner
Follow steps from #1 above
Review the data on the screen
Click on the edit link on the parties tab
Verify when page loads it opens to the parties tab
Update the party type to Petitioner
Verify that the Spouse’s information disappears from the form
Add in Suite 101 in Address line 2
Click review petition
Verify Party type is now listed as Petitioner and not Petitioner and Spouse in column 1
Verify the updated (address line 2) petitioner contact information displays in the second column of the parties tile
Verify the third column in the tile does not display, there is no spouse on this case.
Expected results 
[ ] Review page loads with header displaying case information (Docket Number, Case Caption, etc.) 
[ ] Page Displays with values entered in form
[ ] After click page redirects to the petition form parties tab
[ ] Page Navigates to the Review Petition Screen
[ ] Party type display’s Petitioner
[ ] Address line 2 display new information entered
[ ] Spouse no longer displays on the review screen
[ ] Case caption in the case info tile has been updated

### Edit/Review of New Petition - Case Info 

#### 1) User edits Date received and views updated Review screen
Navigate to saved Petition
Update Date received to 03/02/2020
Click Review Petition
Expected results 
[ ] Date received displays as 03/02/20 on Review screen after edit 
#### 2) User edits Mailing date and view updated Review screen
Navigate to saved Petition
Click Edit on Case Information card
Update Mailing date to “Postmarked 03/01/2020”
Click Review Petition
Expected results 
[ ] Mailing date displays as “Postmarked 03/01/20” on Review screen after edit 

#### 3) User edits case caption field and views updated Review screen 
Navigate to saved Petition
Click Edit on Case Information card
Update Case caption field directly 
Click Review Petition 
Expected results 
[ ] Case caption on Case Information card on Review screen displays edits made on Case Info tab 
[ ] Case caption in case header displays edits made on Case Info tab 

#### 4) User edits party information and views updated case caption on Review screen
Navigate to saved Petition
Click Edit on Case Information card
Navigate to Parties tab 
Edit Petitioner name
Click Review Petition 
Expected results 
[ ] Updated petitioner name displays under Petitioner’s Contact info on Review screen 
[ ] Updated petitioner name displays under Case caption on Review screen 
[ ] Updated case caption displays in case header 
#### 5a) User edits case procedure and views updated Review screen
Navigate to saved Petition
Click Edit on Case Information card
Select Case procedure > Small
Click Review Petition
Expected results 
[ ] Case procedure displays as “Small” on Review screen 
[ ] Docket number suffix “S” is added 

#### 5b) User edits case procedure and views updated Review screen
Navigate to saved Petition
Click Edit on Case Information card
Select Case procedure > Regular
Click Review Petition
Expected results 
[ ] Case procedure displays as “Regular” on Review screen 
[ ] Docket number suffix “S” is removed 
#### 6) User edits Trial location and views updated Review screen 
Navigate to saved Petition
Click Edit on Case Information card
Select a different Trial location 
Click Review Petition 
Expected results 
[ ] updated Trial location displays under Requested trial location on Review screen
#### 7) User edits Filing fee to “Paid” and views updated Review screen 
Navigate to saved Petition
Click Edit on Case Information card
Change “Not paid” to “Paid” 
Enter 03/18/20 as Payment date 
Enter “money order” as Payment method 
Click Review Petition 
Expected results 
[ ] Filing fee field displays as “Paid 03/18/20 money order” on Review screen after edit 

#### 8) User edits Filing fee to “Waived” and views updated Review screen 
Navigate to saved Petition
Click Edit on Case Information cardt 
Change “Not paid” to “Waived” 
Enter 03/09/20 as Date waived
Click Review Petition
Expected results 
[ ] Filing fee field displays as “Waived 03/09/20” on Review screen after edit 

#### 9) User edits Filing fee to “Not paid” and views updated Review screen 
Navigate to saved Petition
Click Edit on Case Information card 
Change “Waived” to “Not paid” 
Click Review Petition
Expected results 
[ ] Filing fee field displays “Not paid” on Review screen after edit 

 10) User edits Orders Needed and views Review screen
Click Create Case 
Check Order for Ratification of Petition
Check Notice of Attachments in the Nature of Evidence 
Check Order for Amended Petition
Check Order for Amended Petition and Filing Fee
Complete form
Click Review Petition
Click Save for Later 
Navigate to saved Petition 
Click Edit 
Navigate to Case Info 
Uncheck Order for Amended Petition
Uncheck Order for Amended Petition and Filing Fee
Click Review Petition 
Expected results 
[ ] Orders Needed alert message displays on Review Screen 
[ ] Order for Ratification of Petition displays in alert 
[ ] Notice of Attachments in the Nature of Evidence displays in alert 
[ ] Order for Amended Petition does not display in alert 
[ ] Order for Amended Petition and Filing Fee does not display in alert 



### Edit/Review of New Petition - IRS Notice 

#### 1) User edits Notice attached to petition from “No” to “Yes” and views updated Review screen
Navigate to saved Petition
Click Edit on Case Information card
Change “No” to “Yes” for Notice attached to petition field 
Enter 03/18/2020 for Date of Notice 
Click Review Petition
Expected results 
[ ] Notice attached to petition field displays as “Yes”  on Review screen after edit 
[ ] Date of Notice displays as “03/18/20” on Review screen after edit 


#### 2) User edit Notice attached to petition from “Yes” to No” and views updated Review screen
Navigate to saved Petition
Click Edit on Case Information card 
Change “Yes” to “No” for Notice attached to petition field 
Click Review Petition
Expected results 
[ ] Notice attached to petition field displays as “No” on Review screen after edit 
[ ] Date of Notice field is hidden on Review screen after edit 

#### 4) User edits Case type and views updated Review screen 

Navigate to saved Petition
Click Edit on Case Information card 
Change case type 
Click Review Petition
Expected results 
[ ] Updated case type displays on Review screen after edit 
[ ] Docket number suffix is added/removed depending on case type selected 








Edit In Progress/Saved for Later Documents (There is no functionality right now to edit these documents- for future development)

#### 1) User cannot edit documents on the Review screen
Navigate to My Document QC > In Progress 
Click into saved Petition 
Verify the header displays case information
Verify the documents tile includes links to modal views of the PDF documents
Verify there is no edit link on the Documents tile
Expected results 
[ ] App navigates to Petition - Review screen 
[ ] Header displays case information (Docket Number, Case Caption, etc.) 
[ ] Documents tile includes links to modal views of the PDF documents
[ ] There is no edit link on the Documents tile


Reviewing Saved for Later Petition - Documents

#### 1) Review the Documents Tile
Navigate to My Document QC > In Progress 
Click into saved Petition 
Verify the header displays case information
Verify Documents tile displays
Verify that all documents that were uploaded in the entry process are listed as a link with a descriptive header above the link in the tile
 Expected results 
[ ] Review page displays
[ ] Documents tile displays with all documents scanned/uploaded from form
[ ] Each document is a link which opens a modal/pdf preview of the document being submitted with the petition
