### ISSUE TITLE
Petitions Clerk: Revamp Petition Flow *SERVE* (Paper)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4762]
Story for serve paper petition

## Note: ##
* When processing a paper document, cover sheet should not be added until it's served
* Consider how much of #3923 to implement here

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
- [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
- [ ] Automated test scripts have been written
- [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Code refactored for clarity and to remove any known technical debt 
 - [ ] Deployed to the dev environment
- [ ] Deployed to the stage environment

**Comment by mariahkannenberg** [comment]
Serve New Petition
- Serves to IRS
 - Posts everything on the docket record
 - Print confirmation
 - Adds cover sheets to documents
- Creates the case
Serve In-Progress Petition
- Serves to IRS
 - Posts everything on the docket record
 - Print confirmation
 - Adds cover sheets to documents

**Comment by alsmith1** [comment]
Draft Test Scenarios 
#### Scenario 1) Petition Clerk Serves a Newly Entered Paper Petition
1. Log in as a petitions clerk
2. Navigate to My Document QC
3. Click on Create a Case
4. Enter the field data and upload/scan all included documents
5. Click on Review Petition button
6. Verify Review screen displays
7. Verify that the blue header says Create Case
8. Verify 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
9. Verify that each tile has an edit link
10. Verify Serve to IRS and Save for Later button appear below the tiles
11. Click Serve to IRS
12. Verify modal appears “Are You Sure You Want to Serve This Petition to the IRS?”
13. Click Yes, Serve
14. Verify page redirects to Docket Record
15. Verify modal opens “Paper service is required for the following document:”
16. Click Print now
17. Verify Print PDF View opens
18. Click Back link
19. Verify docket record loads with success message “The petition has been successfully submitted." 

Expected result
- [ ] Verify Form displays parties tab as default
- [ ] Petition data is entered into the correct fields
- [ ] Review page displays
- [ ] The blue header says Create Case
- [ ] 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
- [ ] Each tile has an edit link
- [ ] Serve to IRS and save for later buttons appears below the tiles
- [ ] modal appears “Are You Sure You Want to Serve This Petition to the IRS?”
- [ ] page redirects to Docket Record
- [ ] modal opens “Paper service is required for the following document:”
- [ ] Print PDF View opens
- [ ] docket record loads with success message “The petition has been successfully submitted."



[ ] Case is created in system
[ ] Docket number is assigned to case  
[ ] Documents are recorded on docket record 
[ ] Docket record displays Served date as current date for Petition (and other documents) 
[ ] Docket record displays Parties as “B” for Petition (and other documents) 
[ ] Petition displays in My Document QC > Served tab and Section Document QC > Served tab 
[ ] Petition Detail page displays “QC completed on <current date> by <username>
[ ] Petition Detail page displays “Served <current date>”
[ ] Cover sheet is applied to all Petition documents 
[ ] Petition is electronically served to IRS ?


#### Scenario 2) Petition clerk can serve a “Saved for Later”  paper petition
1. Login as petitions clerk 
2. Navigate to Document QC In Progress tab 
3. Click into a saved Petition
4. Click “Serve to IRS” 
5. Confirm to Serve on confirmation modal
Expected results 
On select of saved Petition
- [x] app navigates to Petition Review screen 
On click of Serve to IRS 
- [x] Serve paper document modal displays with print option 
- [ ] Once serve paper document modal is closed or Back button is clicked from Printable Document page, app navigates to Case Detail > Docket Record with success message displayed 
- [ ] Petition and any associated documents (RQT, APW, ODS) display on docket record as Served with current date and parties displayed as “B”
- [ ] Cover Sheet is applied to Petition and any associated documents (RQT, APW, ODS) 
- [ ] Petition no long displays in Document QC > In Progress tab 
- [ ] Petition displayed in My Document QC > Served tab and Section Document QC > Served tab
- [ ] Petition clerk’s name who served the petition displays on the Petition Document Detail page and on Section QC Served tab

**Comment by klohman** [comment]
**Serve to IRS button**
On click, confirmation modal displays

**On click of Yes, Serve**
* Case is created in system 
* All attached documents are entered onto Docket Record 
* All attached documents are served to IRS - electronic email to IRS Super User 
* If no parties require paper service, modal closes, and app navigates to Case Detail > Docket record with success message displayed "Petition served to IRS."
* If parties require paper service, app navigates to Case Detail > Docket record with success message displayed "Petition served to IRS." with Paper Service modal displayed.

**Paper service modal**
* On click of Print Now button, navigate to Print Paper Service documents screen 
* On click of 
https://github.com/flexion/ef-cms/blob/develop/docs/entities/Case.md
