### ISSUE TITLE
Spike: Investigate PDF content scraping for search for uploaded docs

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4814]
As a development team, so that we can read the text content of a pdf for search (indexing) purposes, we need to perform a spike on PDF content scraping. 

AC:
Team understands how to read text content of a PDF to index it

**Comment by matthopson** [comment]
**First Attempt**

Using the `pdf-parse` library (https://www.npmjs.com/package/pdf-parse), we were able to successfully pull all "scrapeable" content from a PDF. This DOES NOT handle cases where the text is rasterized (flattened as an image), as it strips the metadata from the PDF.


![Screen Shot 2020-04-14 at 10.38.21 AM.png](https://images.zenhubusercontent.com/5cadf168c7e4b91e9a637015/915621ca-0632-4a48-aa4b-4499e100a2c6)

**Comment by matthopson** [comment]
**First Attempt**

Using the `pdf-parse` library (https://www.npmjs.com/package/pdf-parse), we were able to successfully pull all "scrapeable" content from a PDF. This DOES NOT handle cases where the text is rasterized (flattened as an image), as it strips the metadata from the PDF.


![Screen Shot 2020-04-14 at 10.38.21 AM.png](https://images.zenhubusercontent.com/5cadf168c7e4b91e9a637015/915621ca-0632-4a48-aa4b-4499e100a2c6)
