### ISSUE TITLE
Advanced Search for Orders (system-created)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4829]
As a CMS user, in order to locate a relevant Order, I need the ability to narrow my keyword results by additional search criteria.

## Pre-Conditions: ##
* Basic order search is complete (#3926)

## Acceptance Criteria ##
* When a CMS user performs a keyword search for orders, they can limit their search by:
   * Date Range
   * Judge [Note: Current Judges only; past Judges will be handled in #4830]
   * Case (Docket No. or Petitioner's Name)
   * Keyword
* When searching by Judge, results can pull current judges (past judges handled in separate story)
* Mobile design needs to be reconsidered for order (and opinion) search. Design is not optimal for public and parties in the case. Story backlogged to reconsider overall design for mobile search. #5025

Security requirement - API only returns data as specified in design. (Write test scenarios around only returning specific data)

## Notes ##
* Uploaded Orders will be handled in separate story

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security? Yes.
 - [ ] Does this work make major changes to the system? No.
 - [ ] Does this work implement new authentication or security controls? Kind of.
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features? Yes. 

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by alsmith1** [comment]
![Screen Shot 2020-03-27 at 12.53.32 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/7e9b35d3-8341-411f-9bf2-9281cb590a81)![Screen Shot 2020-03-27 at 12.53.36 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/ac0edc6d-dbdf-4f08-99eb-a8a006912e11)![Screen Shot 2020-03-27 at 12.53.42 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/714909cb-87dd-420c-b73a-7bddbcedb2b6)![Screen Shot 2020-03-27 at 12.53.48 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/7f81a148-8869-40cd-b44a-b37004912524)![Screen Shot 2020-03-27 at 12.53.54 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/a7a82f0b-376e-4af2-8073-67c4faa40d4b)

**Comment by alsmith1** [comment]
#### Scenario 1 - All users searches by keyword 
1. Login as docket clerk 
2. Navigate to Case xxx-20
3. Create, sign, and serve Order for Dismissal
4. Navigate to Search
5. Click on the Order tab
6. Enter in a keyword Dismissal
7. Click search

Expected result
- [ ] Results Count displays number of results found from search
- [ ] Verify the table displays with the following columns
- Docket number
- Case Name
- Order
- Pages
- Date
- Judge
- [ ] Only documents with “Order” in the title are listed in the table
- [ ] Order column displays "Order for Dismissal Entered (listed as full concatenated title)
- [ ] load 25 more button displays below the table if header displays over 25 results

### Scenario 10 - User can narrow search by a current judge 
* Login as Judge Buch 
* Navigate to case xxa-20
* Create Order and Decision, sign, and save as draft
* Login as docket clerk 
* Navigate to case xxa-20 
* Serve Order and Decision
* Login as [internal user] 
* Navigate to Advanced Search > Orders 
* Enter keyword “Decision” 
* Select “Judge Buch” from judge dropdown 
* Click Search 
Expected results 
- [ ] Judge’s dropdown includes all judges (see list in story) 
- [ ] Order and Decision for case xxa-20 signed by Judge Buch displays in results 

#### Scenario 2 - User searches by keyword and docket number with exact match 
1. Login as Judge Cohen 
2. Navigate to Case xxx-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxx-20 
6. Serve Order for Filing Fee
7. Navigate to Search
8. Click on the Order tab
9. Enter in keyword Filing Fee
10. Enter in docket number (xxx-20)
11. Click search

Expected result
- [ ] Results Count displays number of results found from search
- [ ] Only documents with “Order” in the title are listed in the table
- [ ] Order column displays "Order for [Something] Entered Judge [Judge Name]
- [ ] Results that display in table are exact matches for both Keyword (filing fee) and docket number (xxx-20)

#### Scenario 2a - User searches by keyword and docket number with no exact match (no matches found message displays)
1. Login as Judge Cohen 
2. Navigate to Case xxxa-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxxa-20 
6. Serve Order for Filing Fee
7. Navigate to Search
8. Click on the Order tab
9. Enter in keyword Filing Fee
10. Enter in docket number (xxxb-20)
11. Click search

Expected result
- [ ] Message displays below search area with the header “No Matches found”
- [ ] Message displays below search area with test “Check your search terms and try again.” 

#### Scenario 3 - User searches by keyword, docket number and judge 
1. Login as Judge Cohen 
2. Navigate to Case xxx-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxx-20 
6. Serve Order for Filing Fee
7. Navigate to Search
8. Click on the Order tab
9. Enter in keyword Filing Fee
10. Enter in docket number (xxx-20)
11. Enter judge (Cohen)
12. Click search

Expected result
- [ ] Results Count displays number of results found from search
- [ ] Only documents with “Order” in the title are listed in the table
- [ ] Order column displays "Order for [Something] Entered Judge [Judge Name]
- [ ] Results that display in table are exact matches for Keyword (filing fee), docket number (xxx-20) and Judge (Cohen)

#### Scenario 4 - User searches by keyword, docket number, judge, and date range 
1. Login as Judge Cohen 
2. Navigate to Case xxx-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxx-20 
6. Serve Order for Filing Fee
7. Navigate to Search
8. Click on the Order tab
9. Enter in keyword Filing Fee
10. Enter in docket number (xxx-20)
11. Enter judge (Cohen)
12. Enter Date range(10/04/1980-03/27/2020)
12. Click search

Expected result
- [ ] Results Count displays number of results found from search
- [ ] Only documents with “Order” in the title are listed in the table
- [ ] Order column displays "Order for [Something] Entered Judge [Judge Name]
- [ ] Results that display in table are exact matches for Keyword (filing fee), docket number (xxx-20), Judge (Cohen) and date range (10/04/1980-03/27/2020)

#### Scenario 5 - User searches by keyword, docket number, and date range 
1. Login as Judge Cohen 
2. Navigate to Case xxx-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxx-20 
6. Serve Order for Filing Fee
7. Navigate to Search
8. Click on the Order tab
9. Enter in keyword Filing Fee
10. Enter in docket number (xxx-20)
11. Enter Date range(10/04/1980-03/27/2020)
12. Click search

Expected result
- [ ] Results Count displays number of results found from search
- [ ] Only documents with “Order” in the title are listed in the table
- [ ] Order column displays "Order for [Something] Entered Judge [Judge Name]
- [ ] Results that display in table are exact matches for Keyword (filing fee), docket number (xxx-20),  and date range (10/04/1980-03/27/2020)
 
#### Scenario 6 - User searches by keyword and case name with exact match
**Test data**
* Create case - petitioner and spouse John Smith and Mary Jones (case xxx-20)
    * Create, sign and serve order - Order to Show Cause - signed by Judge Pugh 
        * Include keyword “affirmative” 
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John Smith and Mary Jones”
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxx-20 displays in results 

#### Scenario 7 - User searches by keyword and case name with partial matches
**Test data**
* Create case - petitioner and spouse John Smith and Mary Jones (case xxx-20)
    * Create, sign and serve order - Order to Show Cause 
        * Filed by date 12/20/19
        * Include keyword “affirmative” 
* Create case - estate with executor - Estate of John Baxter, Deceased, Wade Baxter, Executor, Petitioner(s) (case xxb-20)
    * Create, sign and Serve - Order for Dismissal - signed by Judge Buch 
        * Filed by date - 03/20/20
        * Include keyword “affirmative”  
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John”
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxx-20 displays in results 
- [ ] Order for Dismissal for case xxb-20 displays in results

#### Scenario 8 - User searches by keyword and case name (no matches) 
**Test data**
* Same as above  
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “Bob”
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxx-20 does not display in results 
- [ ] Order for Dismissal for case xxb-20 does not displays in results 
- [ ] “No matching results” message displays 

#### Scenario 9 - User searches by keyword, case name (exact match)and judge 
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John Smith and Mary Jones”
* Select Judge Pugh from Judge dropdown
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxx-20 displays in results 

#### Scenario 10 - User searches by keyword, case name (partial match)and judge 
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John”
* Select Judge Buch from Judge dropdown
* Click Search 
Expected results 
- [ ] Order for Dismissal for case xxb-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 does not display in results 


#### Scenario 11 - User searches by keyword, case name (exact match), judge, and date range 
**Test Data** 
* Same as above 
* Case xxx-20 (John Smith and Mary Jones) 
    * Create, sign and serve Order for Filing Fee - signed by Judge Pugh 
        * Include word - “affirmative” 
        * Filed date - 01/1/20
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John Smith and Mary Jones”
* Select Judge Pugh from Judge dropdown
* Enter Date range - 01/1/20 - 03/01/20
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 does not display in results 


#### Scenario 12 - User searches by keyword, case name (partial match), judge, and date range 
**Test Data** 
* Same as above 

**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John”
* Select Judge Pugh from Judge dropdown
* Enter Date range - 01/1/20 - 03/01/20
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 

#### Scenario 13 - User searches by keyword, case name (exact match) and date range 
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John Smith and Mary Jones”
* Enter Date range - 1/1/19 - 04/01/20
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 displays in results 

#### Scenario 14 - User searches by keyword, case name (partial match) and date range 
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John”
* Enter Date range - 1/1/19 - 04/01/20
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 displays in results 
- [ [ Order for Dismissal for case xxb-20 displays in results 

#### Scenario 15 - User searches by keyword, docket number and case name (exact match)
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter docket number xxx-20
* Enter case name “John Smith and Mary Jones” 
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 displays in results

#### Scenario 16 - User searches by keyword, docket number, and case name (not exact match) 
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter docket number xxx-20
* Enter case name “John” 
* Click Search 
Expected results 
- [ ] form is not submitted
- [ ] Page-level error message displays
- [ ] Field-level error message displays on docket number and case name fields “Enter either a Docket number or a Case name/Petitioner name, not both”

**Comment by alsmith1** [comment]
#### Scenario 1 - All CMS internal or external users can see the search functionality of Court issued Orders
1. Log in as an internal/external user
2. Click on the Advanced Search link
3. Verify when the page loads there are 3 tabs under the advanced search bar (Case, Orders, and Practitioner)
4. Click on the Order tab

Expected result
- [ ] Order tab displays on advanced search screen
- [ ] Form is broken down into 2 sections
     1. Keyword(s) Required field
     2. Narrow your search filters
    - Docket Number
    - Case Name
    - Judge
    - Date  (MM/DD/YYYY to MM/DD/YYYY)

#### Scenario 2 - Public can see the search functionality of Court issued Orders
1. Navigate to the public site’s Search page
3. Verify when the page loads there are 2 tabs under the advanced search bar (Case, and Orders)
4. Click on the Order tab

Expected result
- [ ] Order tab displays on advanced search screen
- [ ] Form is broken down into 2 sections
     1. Keyword(s) Required field
     2. Narrow your search filters
    - Docket Number
    - Case Name
    - Judge
    - Date  (MM/DD/YYYY to MM/DD/YYYY)

#### Scenario 3 - Internal Court Users should see results with any documents or data that are part of a sealed case
1. Login as Judge Cohen 
2. Navigate to Case xxx-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxx-20 
6. Serve Order for Show Cause
7. Navigate to Case Information tab 
8. Seal case
9. Navigate to Search 
10. Click on the Order tab
11. Enter in keyword (Show Cause)
12. Click search
13. Check table for case (xxx-20)

Expected result
[ ]  Order  to show cause docket number (xxx-20) displays in results with a red lock next to the docket number

#### Scenario 4 - External Court Users should see results with any documents or data that are part of a sealed case if they are associated with that case Break down with docket number
1. Login as Judge Cohen 
2. Navigate to Case xxx-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxx-20 
6. Serve Order for Dismissal
7. Log in as an external user that is associated with case (xxx-20)
8. Click on the Advanced Search link
9. Click on the Order tab
10. Enter in a keyword
11. Click search

Expected result
- [ ]  Order for Dismissal docket number (xxx-20) displays in results with a red lock next to the docket number


#### Scenario 5 - The public should not see any documents or data that are part of a sealed case
* Login as docket clerk 
* Navigate to Case xxx-20
* Create, sign, and serve Order for Dismissal 
* Navigate to Case Information tab 
* Seal case 
* Access site as public user 
* Enter keyword “Order for Dismissal” and docket “xxx-20” 
* Click Search 
Expected results 
- [ ] Order for Dismissal for Case xxx-20 does not display in results 
- [ ] “No Matches Found” message displays 

#### Scenario 6 - External Users should not see any documents or data that are part of a sealed case if they are not associated with that case
* Create case as petitioner1 (xxx-20)
* Login as docket clerk 
* Navigate to case (xxx-20)
* Create, sign, and  serve Order for Filing Fee 
* Seal case 
* Login as petitioner2 / privatePractitioner1 / irsPractitioner
* Navigate to Advanced Search > Orders tab 
* Enter “Order for Filing Fee” and docket “xxx-20”
Expected results 
- [ ] Order for Filing Fee for Case xxx-20 does not display in results 
- [ ] “No Matches Found” message displays

#### Scenario 7 - Court orders that have been served and added to docket record are indexed and searchable
* Login as docket clerk 
* Navigate to case xxa-20
* Create, sign, and serve Order to Show Cause
* Navigate to case xxb-20
* Create, sign, and serve Order to Show Cause  
* Navigate to Advanced Search > Orders tab 
* Enter “Show Cause” in keyword 
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxa-20 is displayed in results 
- [ ] Order to Show Cause for case xxb-20 is displayed in results 

#### Scenario 8 -Court orders that are in draft documents are not searchable
* Login as Judge Buch 
* Navigate to case xxa-20
* Create Order and Decision, sign, and save as draft
* Login as docket clerk 
* Navigate to Advanced Search > Orders tab 
* Enter “Decision” in keyword and docket “xxa-20” 
Expected results 
- [ ] Order and Decision for case xxa-20 does not display in search results 

#### Scenario 9 -Court orders that are added to docket record but have not been served are not searchable
* Scenario 8 
* Login as docket clerk 
* Navigate to Case xxa-20 - Case Detail > In Progress > Draft Documents
* Click on Order and Decision  
* Click Add Docket Entry 
* Complete Add Docket Entry Form 
* Click Save Entry button 
* Login as [internal user] 
* Navigate to Advanced Search > Orders tab 
* Enter “Decision” in keyword and docket “xxa-20” 
Expected results 
- [ ] Order and Decision for case xxa-20 does not display in search results 

#### Scenario 12 Search for order with keyword in title 
1. Login as docket clerk 
2. Navigate to Case xxx-20
3. Create, sign, and serve Order for Dismissal
4. Log in as Judge Cohen
5. Navigate to Search
6. Click on the Order tab
7. Enter in a keyword Dismissal
8. Click search

Expected result
- [ ] Documents with keyword “Dismissal” in the title are listed in the table

#### Scenario 13 Search for order with keyword in body copy 
1. Login as docket clerk 
2. Navigate to Case xxx-20
3. Create, sign, and serve Order for Dismissal with keyword “Star” in the body copy
4. Log in as an ADC
5. Navigate to Search
6. Click on the Order tab
7. Enter in a keyword Star
8. Click search

Expected result
- [ ] Documents that have keyword “Star” in the body copy are listed in the table

#### Scenario 14) User views Order PDF from search results 
* Scenario 12 
* Click on Order for Dismissal link from results table 
Expected results 
- [ ] Order PDF opens in new tab

**Comment by alsmith1** [comment]
#### Scenario 1 - All users searches by keyword 
1. Login as docket clerk 
2. Navigate to Case xxx-20
3. Create, sign, and serve Order for Dismissal
4. Navigate to Search
5. Click on the Order tab
6. Enter in a keyword Dismissal
7. Click search

Expected result
- [ ] Results Count displays number of results found from search
- [ ] Verify the table displays with the following columns
- Docket number
- Case Name
- Order
- Pages
- Date
- Judge
- [ ] Only documents with “Order” in the title are listed in the table
- [ ] Order column displays "Order for Dismissal Entered (listed as full concatenated title)
- [ ] load 25 more button displays below the table if header displays over 25 results



#### Scenario 2 - User searches by keyword and docket number with exact match 
1. Login as Judge Cohen 
2. Navigate to Case xxx-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxx-20 
6. Serve Order for Filing Fee
7. Navigate to Search
8. Click on the Order tab
9. Enter in keyword Filing Fee
10. Enter in docket number (xxx-20)
11. Click search

Expected result
- [ ] Results Count displays number of results found from search
- [ ] Only documents with “Order” in the title are listed in the table
- [ ] Order column displays "Order for [Something] Entered Judge [Judge Name]
- [ ] Results that display in table are exact matches for both Keyword (filing fee) and docket number (xxx-20)

#### Scenario 2a - User searches by keyword and docket number with no exact match (no matches found message displays)
1. Login as Judge Cohen 
2. Navigate to Case xxxa-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxxa-20 
6. Serve Order for Filing Fee
7. Navigate to Search
8. Click on the Order tab
9. Enter in keyword Filing Fee
10. Enter in docket number (xxxb-20)
11. Click search

Expected result
- [ ] Message displays below search area with the header “No Matches found”
- [ ] Message displays below search area with test “Check your search terms and try again.” 

#### Scenario 3 - User searches by keyword, docket number and judge 
1. Login as Judge Cohen 
2. Navigate to Case xxx-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxx-20 
6. Serve Order for Filing Fee
7. Navigate to Search
8. Click on the Order tab
9. Enter in keyword Filing Fee
10. Enter in docket number (xxx-20)
11. Enter judge (Cohen)
12. Click search

Expected result
- [ ] Results Count displays number of results found from search
- [ ] Only documents with “Order” in the title are listed in the table
- [ ] Order column displays "Order for [Something] Entered Judge [Judge Name]
- [ ] Results that display in table are exact matches for Keyword (filing fee), docket number (xxx-20) and Judge (Cohen)

#### Scenario 4 - User searches by keyword, docket number, judge, and date range 
1. Login as Judge Cohen 
2. Navigate to Case xxx-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxx-20 
6. Serve Order for Filing Fee
7. Navigate to Search
8. Click on the Order tab
9. Enter in keyword Filing Fee
10. Enter in docket number (xxx-20)
11. Enter judge (Cohen)
12. Enter Date range(10/04/1980-03/27/2020)
12. Click search

Expected result
- [ ] Results Count displays number of results found from search
- [ ] Only documents with “Order” in the title are listed in the table
- [ ] Order column displays "Order for [Something] Entered Judge [Judge Name]
- [ ] Results that display in table are exact matches for Keyword (filing fee), docket number (xxx-20), Judge (Cohen) and date range (10/04/1980-03/27/2020)

#### Scenario 5 - User searches by keyword, docket number, and date range 
1. Login as Judge Cohen 
2. Navigate to Case xxx-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxx-20 
6. Serve Order for Filing Fee
7. Navigate to Search
8. Click on the Order tab
9. Enter in keyword Filing Fee
10. Enter in docket number (xxx-20)
11. Enter Date range(10/04/1980-03/27/2020)
12. Click search

Expected result
- [ ] Results Count displays number of results found from search
- [ ] Only documents with “Order” in the title are listed in the table
- [ ] Order column displays "Order for [Something] Entered Judge [Judge Name]
- [ ] Results that display in table are exact matches for Keyword (filing fee), docket number (xxx-20),  and date range (10/04/1980-03/27/2020)
 
#### Scenario 6 - User searches by keyword and case name with exact match
**Test data**
* Create case - petitioner and spouse John Smith and Mary Jones (case xxx-20)
    * Create, sign and serve order - Order to Show Cause - signed by Judge Pugh 
        * Include keyword “affirmative” 
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John Smith and Mary Jones”
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxx-20 displays in results 

#### Scenario 7 - User searches by keyword and case name with partial matches
**Test data**
* Create case - petitioner and spouse John Smith and Mary Jones (case xxx-20)
    * Create, sign and serve order - Order to Show Cause 
        * Filed by date 12/20/19
        * Include keyword “affirmative” 
* Create case - estate with executor - Estate of John Baxter, Deceased, Wade Baxter, Executor, Petitioner(s) (case xxb-20)
    * Create, sign and Serve - Order for Dismissal - signed by Judge Buch 
        * Filed by date - 03/20/20
        * Include keyword “affirmative”  
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John”
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxx-20 displays in results 
- [ ] Order for Dismissal for case xxb-20 displays in results

#### Scenario 8 - User searches by keyword and case name (no matches) 
**Test data**
* Same as above  
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “Bob”
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxx-20 does not display in results 
- [ ] Order for Dismissal for case xxb-20 does not displays in results 
- [ ] “No matching results” message displays 

#### Scenario 9 - User searches by keyword, case name (exact match)and judge 
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John Smith and Mary Jones”
* Select Judge Pugh from Judge dropdown
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxx-20 displays in results 

#### Scenario 10 - User searches by keyword, case name (partial match)and judge 
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John”
* Select Judge Buch from Judge dropdown
* Click Search 
Expected results 
- [ ] Order for Dismissal for case xxb-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 does not display in results 


#### Scenario 11 - User searches by keyword, case name (exact match), judge, and date range 
**Test Data** 
* Same as above 
* Case xxx-20 (John Smith and Mary Jones) 
    * Create, sign and serve Order for Filing Fee - signed by Judge Pugh 
        * Include word - “affirmative” 
        * Filed date - 01/1/20
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John Smith and Mary Jones”
* Select Judge Pugh from Judge dropdown
* Enter Date range - 01/1/20 - 03/01/20
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 does not display in results 


#### Scenario 12 - User searches by keyword, case name (partial match), judge, and date range 
**Test Data** 
* Same as above 

**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John”
* Select Judge Pugh from Judge dropdown
* Enter Date range - 01/1/20 - 03/01/20
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 

#### Scenario 13 - User searches by keyword, case name (exact match) and date range 
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John Smith and Mary Jones”
* Enter Date range - 1/1/19 - 04/01/20
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 displays in results 

#### Scenario 14 - User searches by keyword, case name (partial match) and date range 
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John”
* Enter Date range - 1/1/19 - 04/01/20
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 displays in results 
- [ [ Order for Dismissal for case xxb-20 displays in results 

#### Scenario 15 - User searches by keyword, docket number and case name (exact match)
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter docket number xxx-20
* Enter case name “John Smith and Mary Jones” 
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 displays in results
Search Results functionality ---
#### Scenario 16 - User searches by keyword, docket number, and case name (not exact match) 
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter docket number xxx-20
* Enter case name “John” 
* Click Search 
Expected results 
- [ ] form is not submitted
- [ ] Page-level error message displays
- [ ] Field-level error message displays on docket number and case name fields “Enter either a Docket number or a Case name/Petitioner name, not both”

**Comment by alsmith1** [comment]
Stg test cases
xx1-20 --> 109-20
