### ISSUE TITLE
Parties: Filing a document in a consolidated case (DESCOPE)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#483]
As a party in a case, so that I may file my documents in a set of consolidated cases, I need to be presented with an option to file in one or multiple cases in a set that is consolidated.

## Pre-Conditions
* Cases have been consolidated

## Final tasks
* PR out for permissions to hide document upload
* User who is not a party in a case is unable to link to that case from the dashboard (petitioners, practitioners and IRS - test to make sure all permissions are correct)

## Acceptance Criteria (STORY STOPPED PART WAY THROUGH DUE TO DESCOPING. ENTIRE STORY, INCLUDING TEST CASES AND WIREFRAMES BACKLOGGED FOR POST-MVP IN #3898)
* When a party attempts to file a document in a case that is in a set of consolidated cases, they are prompted to choose one or multiple cases to file the document in
* Filer should indicate which parties in each case the document is being filed for
* The document is uploaded to the system and linked to via the docket record of each case it's filed in
* Only 1 QC item is created even if document is filed in multiple cases
* The filers and associated docket numbers should be easily viewable on the docket record
* If a doc was filed in case #1, #2, but not #3, the docket entry still shows up on #3 as an entry for filing 

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Cover sheet for filing will be a separate story
* Rhonda to go through the list of documents to identify any special circumstances needed for an individual document
* When a document is filed in a consolidated case, court only wants one item in the QC
* QC is not part of this story
* Cover page is not part of this story
* Let's define a "lead case"
Notes from 12/4:
 * Check box is auto-checked for the case in which the filer started the consolidation
* Remove docket numbers behind party names in file a document flow
* On parties section of filing, require at least one party for each case

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)(#3933)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by alsmith1** [comment]
From Rhonda: An entry of appearance, substitution of counsel and proposed stipulated decision are the only documents that the efiler must file a separate document in each docket number.

**Comment by alsmith1** [comment]
—DRAFT—
## Test scenarios
#### Scenario 1 - When a party attempts to file a document in a case that is in a set of consolidated cases, they are prompted to choose one or multiple cases to file the document in
1. Login as any external user
2.  Click on one of the docket numbers that is part of a consolidated case
3. Click The file a document button
4. Verify that after you click on “ok, I’m ready to file” button a modal appears
5. Click on the checkboxes next to the cases you would like to file your document in
6. Click on Add to Case(s) button

Expected result
- [ ] Modal appears “would you like to file your document in multiple cases” with list of cases in which chosen case is consolidated with. 


#### Scenario 2 - File a document page displays what cases user is filing into
1. Login as any external user
2.  Click on one of the docket numbers that is part of a consolidated case
3. Click The file a document button
4. Verify that after you click on “ok, I’m ready to file” button a modal appears
5. Click on the checkboxes next to the cases you would like to file your document in
6. Click on Add to Case(s) button
7. Verify when the what document are you filing page loads, at the top displays a message that states, “ your document will be filled in docket numbers #, #, and #.

Expected result
- [ ] Modal appears “would you like to file your document in multiple cases” with list of cases in which chosen case is consolidated with. 
- [ ] Message appears at the top of the “What document are you filing” page that displays a message that states, “ your document will be filled in docket numbers #, #, and #.

#### Scenario 3 - Error occurs if “Proposed stipulated decision” is chosen to file in multiple consolidated cases
1. Login as any external user
2.  Click on one of the docket numbers that is part of a consolidated case
3. Click The file a document button
4. Verify that after you click on “ok, I’m ready to file” button a modal appears
5. Click on the checkboxes next to the cases you would like to file your document in
6. Click on Add to Case(s) button
7. Select Proposed Stipulated decision
8. Click continue
9. Verify when the what document are you filing page loads, at the top displays a message that states, “ your document will be filled in docket numbers #, #, and #.
10. Verify that a red vertical line displays next to the document dropdown and a red error message displays under the dropdown which reads “ Proposed Stipulated Decision must be filled for each case”

Expected result
- [ ] Modal appears “would you like to file your document in multiple cases” with list of cases in which chosen case is consolidated with. 
- [ ] Message appears at the top of the “What document are you filing” page that displays a message that states, “ your document will be filled in docket numbers #, #, and #.
- [ ] A red vertical line displays next to the document dropdown and a red error message displays under the dropdown which reads “ Proposed Stipulated Decision must be filled for each case”

#### Scenario 4 - User can select who filed the document for each case in the file a document flow
1. Login as any external user
2.  Click on one of the docket numbers that is part of a consolidated case
3. Click The file a document button
4. Verify that after you click on “ok, I’m ready to file” button a modal appears
5. Click on the checkboxes next to the cases you would like to file your document in
6. Click on Add to Case(s) button
7. Verify when the what document are you filing page loads, at the top displays a message that states, “ your document will be filled in docket numbers #, #, and #.
8. Select a document and click continue
9. Verify that in “tell us about the parties filing the document(s) each case the document will be filed displays with checkboxes next to the filing parties

Expected result
- [ ] Modal appears “would you like to file your document in multiple cases” with list of cases in which chosen case is consolidated with. 
- [ ] Message appears at the top of the “What document are you filing” page that displays a message that states, “ your document will be filled in docket numbers #, #, and #.
- [ ] In the “tell us about the parties filing the document(s) each case the document will be filed displays checkboxes next to the filing parties


#### Scenario 5 -On the Review page user can see what cases their document is filed in and that parties filed the document
1. Login as any external user
2.  Click on one of the docket numbers that is part of a consolidated case
3. Click The file a document button
4. Verify that after you click on “ok, I’m ready to file” button a modal appears
5. Click on the checkboxes next to the cases you would like to file your document in
6. Click on Add to Case(s) button
7. Verify when the what document are you filing page loads, at the top displays a message that states, “ your document will be filled in docket numbers #, #, and #.
8. Select a document and click continue
9. Select the filing party/parties for each case
10. Click submit filing button
11. Verify on the review screen under Parties filing the document(s) each case, of the consolidated cases, are listed below and who the filing party is is listed for each

Expected result
- [ ] Modal appears “would you like to file your document in multiple cases” with list of cases in which chosen case is consolidated with. 
- [ ] Message appears at the top of the “What document are you filing” page that displays a message that states, “ your document will be filled in docket numbers #, #, and #.
- [ ] In the “tell us about the parties filing the document(s) each case the document will be filed displays checkboxes next to the filing parties
- [ ] On the review screen under Parties filing the document(s) each case, of the consolidated cases, are listed below and who the filing party is is listed for each

#### Scenario 7 -The document filed in scenario 5 displays in the docket record of each case filed in
1. Login as any external user
2.  Click on one of the docket numbers from scenario 5
3. Verify that in the docket record table the document from scenario 5 displays
4. Repeat step 2 & 3 for each case the document was filed to

Expected result
- [ ] The document displays on the docket record for each case the document was filed to

**Comment by alsmith1** [comment]
![Screen Shot 2019-11-29 at 8.16.34 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/7d73130d-b1b3-4c13-85f8-95eaea54f152)![Screen Shot 2019-11-29 at 8.16.42 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/5cbb9568-f36a-4968-abe2-b15b8f5c1f3a)![Screen Shot 2019-11-29 at 8.16.58 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/3fe4f507-112a-4460-a0b5-86685eb6afd7)![Screen Shot 2019-11-29 at 8.17.16 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/cf862f88-2fe3-4f5d-b44d-ff2b217d0263)![Screen Shot 2019-11-29 at 8.17.38 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/de9c9dbf-9111-4aaf-a8a2-dee2dff37b80)![Screen Shot 2019-11-29 at 8.18.06 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/54961dfe-6167-4b5e-be92-259e1ba776f0)

**Comment by alsmith1** [comment]
![Screen Shot 2019-12-03 at 12.58.10 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/e98f70d2-ba40-40bc-806e-2cca1916481d)![Screen Shot 2019-12-03 at 12.58.16 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/1431730f-47b6-49da-83b7-874b0a0542f1)![Screen Shot 2019-12-03 at 12.58.31 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/0f51362c-551e-45be-be8d-60f0ff93e130)![Screen Shot 2019-12-03 at 12.58.41 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/5bfecdc9-0461-4c24-abe7-296f2578ae0c)![Screen Shot 2019-12-03 at 12.58.55 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/13ad4f07-60aa-42ed-afe2-b57186811758)![Screen Shot 2019-12-03 at 12.59.02 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/7c6e9978-8931-4860-a034-3c96585b39e5)
