### ISSUE TITLE
CMS User: Advanced Opinion Search

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4837]
As a CMS User, to quickly locate an opinion, I need the ability to narrow my results for an opinion search. 

## Pre-Conditions: ##
* Basic opinion search is complete (#3913)

## Acceptance Criteria: ##
* CMS User (both internal Court User and the public) can limit the opinion search by:
   * Date Range, down to the day
   * Opinion Type (T.C. Opinion, Memorandum, Summary)
   * Judge [Note: This includes only current Judges; past Judges handled in #4839]
   * Case (Docket No. or Petitioner's Name)
* Results display page count in results

Notes:
* Opinion type is part of the event code. How is it being stored? 
* Judge - needs to be associated to the document
* Mobile design needs to be reconsidered for opinion (and order) search. Design is not optimal for public and parties in the case. Story backlogged to reconsider overall design for mobile search. #5025

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Need to build internal and public-facing (unauthenticated) version
* For opinions in sealed cases, anything security related will be handled manually by the person drafting the document
* Association of judge during concatenation of document can be tied to search/results

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts (Jojo)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Oojo)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Jojo)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by alsmith1** [comment]
![Screen Shot 2020-04-23 at 11.19.35 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/192673b8-eb44-4c9f-9d3b-85179ac8b708)
#### Docket Number 
- Is optional 
- Limits scope of keyword search to the entered docket number (keyword + within docket xxx-20) 
- Docket number must be an exact match 

#### Case Title 
- Is optional 
- Case title can be case name or Petitioner's Name
- Case title can be exact match or partial match 
- Searches for matches in case caption AND petitioner contact information (primary 1 and 2) 
- Limits scope of keyword search to cases with exact or partial matching Case title (dup to bullet #3?)

#### Docket number OR Case title/Petitioner name
- Docket number or Case title/Petitioner name may be entered
- If both are entered an error will display (see notes on error wireframe)

#### Opinion Type
-is optional
-Opinion type dropdown includes T.C. Opinion, Memorandum Opinion, Summary Opinion
-Limits scope of keyword search to opinion documents with a matching event code

#### Judge
- Is optional 
- Dropdown Includes all current judges ( past judges in another story)
- Limits scope of keyword search to opinion documents with a matching judge (Judge’s name is the judge selected while adding opinion document to the docket record)

#### Date range 
- Field group is optional 
- Limits scope of keyword search to opinions with matching Filed date within entered date range 
- Scope includes start and ending date 
- Date format must be complete: MM/DD/YYYY
- If start date is entered, but end date is left blank - copy start date to end date field and search 

### Search results relevancy
- If there are multiple document results which are exact match they are ordered by docket number smallest to largest
- Results appear in relevance of search terms provided

#### Keyword-only 
- keyword /phrase -  exact match 
- keyword/ phrase partial match 

#### Keyword + docket number + [judge, date, opinion type]
- keyword exact match + docket exact match + judge exact match + date exact match + opinion type exact match
- keyword partial match + docket exact match  + judge exact match + Date exact match + opinion type exact match
- keyword exact match + docket exact match + judge exact match + date range match + opinion type exact match - sort by date oldest to newest 
- keyword partial match + docket exact match  + judge exact match + Date range match + opinion type exact match - sort by date oldest to newest

#### Keyword + case title + [judge, date, opinion type]
- keyword exact match + Case title exact match + judge exact match + date exact match + opinion type exact match 
- keyword partial match + Case title exact match + judge exact match + date exact match + opinion type exact match 
- keyword exact match + Case title partial match + judge exact match + date exact match + opinion type exact match 
- keyword partial match + Case title partial match + judge exact match + date exact match + opinion type exact match 
- keyword exact match + Case title exact match + judge exact match + date range match + opinion type exact match  - sort by date oldest to newest 
- keyword partial match + Case title exact match + judge exact match + date range match + opinion type exact match  - sort by date oldest to newest 
- keyword exact match + Case title partial match + judge exact match + date range match + opinion type exact match  - sort by date oldest to newest 
- keyword partial match + Case title partial match + judge exact match + date range match + opinion type exact match  - sort by date oldest to newest 

#### Keyword + Opinion type 
- keyword exact match + Opinion typeexact match 
- keyword partial match + Opinion type exact match

#### Keyword + judge 
- keyword exact match + Judge exact match 
- keyword partial match + Judge exact match

#### Keyword + date 
- keyword exact match + date exact match 
- keyword partial match + date exact match 
- keyword exact match + date range match - sorted by date oldest to newest 
- keyword partial match + date range match - sorted by date oldest to newest

#### Elastic search results 
- Docket number - exact match
-Opinion Type- exact match
- Judge- exact match
- Date - exact match
- Case title- bump exact matches to top but allow for partial match (same way we search petitioner name)
- Can filter search by Docket number or Case title/petitioner name not both ( displays error)

![Screen Shot 2020-04-23 at 11.19.43 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/2659ed0a-c777-4883-b113-1412ee3d89b0)
Design Notes
- Keyword is required
- when no keyword is entered error message displays stating, “Enter a keyword”

![Screen Shot 2020-04-23 at 11.19.51 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/817480e1-7200-40f6-9c67-6d2a02e65132)
Design Notes
- Can filter search by Docket number or Casename/petitioner name not both ( displays error)
- When user enters both docket number and case name... on submit error displays at to of the screen and also inline


![Screen Shot 2020-04-23 at 11.19.58 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/cc0dffe5-d93c-45ce-9a11-2d1ce1bd0177)
Design Notes
- Can filter search by Date Range
- Can enter start date without an end date
- Cannot enter an invalid date or future date in either Start Date or End Date. Error will display “Enter a valid start/end date”
- Can not enter only end date error will display “Enter a start date”

![Screen Shot 2020-04-23 at 11.20.06 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/05c58998-6042-4680-b2c7-824384c61e0e)
If there are no results  default message displays. header No Matches Found text Check your search terms and try again


![Screen Shot 2020-04-23 at 11.20.13 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/f6047fea-e0c3-42df-94a1-26e596bddef4)
Design Notes:

PDF View
- When clicking on the order name in the search result new tab/window opens with PDF viewer of order. 
we want a full page not a modal for ease of use
-Page Header and footer content should not searchable  (Washington, DC etc...)

**Comment by alsmith1** [comment]
## Search Results option breakdown

Test Set Up-
Validate UI
### Scenario 1 - All CMS internal or external users can see the search functionality of Opinions
1. Log in as an internal/external user + Public users
2. Click on the Advanced Search link
3. Click on the Opinion tab Expected result
- [ ] Opinion tab displays on advanced search screen
- [ ] Form is separated into two sections
- [ ] Enter Keyword or Phrase displays as a header with Search for ... above the search button
- [ ] Narrow Your Search 
        * Docket number or case title/petitioner’s name
	* Opinion Type
        * Judge
        * Date (mm/dd/yyyy-mm/dd/yyyy)

---------------------------------------------------------------------
Test Set Up-
* Case xx1-20
    * Create, sign, serve Summary Opinion 	* PDF contains word “supplemental”
	* Order Signed by Judge Cohen
	*Filed Date is 04/06/2020
* Case xx2-20
    * Create sign, serve Memorandum opinion
        * PDF contains word “supplemental”
* Case xx3-20
    * Create, sign, serve Order for Dismissal
        * PDF contains word “supplemental”  
        * Filed date is 04/10/2020
        * Order Signed by Judge Foley   
* Case xx4-20
    * Create, sign, serve Summary Opinion
        * PDF contains word “supplemental” 
        * Filed date is 04/15/2020
 * Create, sign, serve Memorandum Opinion
        * PDF contains word “supplemental” 
        * Filed date is 04/20/2020

* Case xx5-20
    * Create, sign, serve TC Opinion  	* PDF contains word “supplemental”
	* Order Signed by Judge Cohen
	*Filed Date is 04/06/2020

**Search/Return Results**

#### Scenario 2 - CMS user searches for Opinion by keyword (exact/partial), docket number(exact)
1. Navigate to Advanced Search
2. Click on the Opinion tab
3. Enter in keyword supplemental
4. Enter in docket number (xx5-20)
5. Click search
Expected result
- [ ] Results display “TC Opinion” an exact match keyword (supplemental) and exact match docket number (xx5-20) 

#### Scenario 3 - CMS user searches for Opinion by keyword (exact) and docket number (exact) with no matches found  (message displays)
1. Navigate to Advanced Search
2. Click on the Opinion tab
3. Enter in keyword Umbrella
4. Enter in docket number (x20-20)
5. Click search
Expected result
- [ ] Message displays below search area with the header “No Matches found”
- [ ] Message displays below search area with test “Check your search terms and try again.” 

#### Scenario 4 - CMS user searches for Opinion by keyword, docket number (exact) and Opinion type (exact) 
1. Navigate to Advanced Search
2. Click on the Opinion tab
3. Enter in keyword supplemental
4. Enter in docket number (xx1-20)
5. Select Summary opinion for opinion type dropdown
6. Click search
Expected result
- [ ] Results display “Summary Opinion” an exact match keyword (supplemental), exact match docket number (xx1-20)

#### Scenario 5 - CMS user searches for Opinion by keyword, docket number (exact), Opinion type (exact) and judge (exact)
1. Navigate to Advanced Search
2. Click on the Opinion tab
3. Enter in keyword supplemental
4. Enter in docket number (xx1-20)
5. Select Summary opinion for opinion type dropdown
6. Enter judge (Cohen)
7. Click search
Expected result
- [x] Results display “Summary Opinion” an exact match keyword (supplemental), exact match docket number (xx1-20), and exact match for judge (Cohen)

#### Scenario 6 - CMS user searches for Opinion by keyword, docket number, opinion type, judge, and date range 
1. Navigate to Advanced Search
2. Click on the Opinion tab
3. Enter in keyword supplemental
4. Enter in docket number (xx5-20)
5. Select TC opinion for opinion type dropdown
6. Enter judge (Cohen)
7. Enter Date (03/04/2020-04/06/2020)
8. Click search
Expected result
- [ ]  Results display “TC opinion” an exact match keyword (supplemental), exact match docket number (xx5-20), exact match Judge (Cohen) and Date (04/06/2020)

#### Scenario 7 - CMS user searches for Opinion by keyword, docket number, and date 
1. Navigate to Advanced Search
2. Click on the Opinion tab
3. Enter in keyword supplemental
4. Enter in docket number (xx4-20)
5. Select Summary opinion for opinion type dropdown
6. Enter Date (03/31/2020- 04/20/2020)
7. Click search
Expected result
- [ ] Results display “Summary Opinion” an exact match keyword (supplemental)  and exact match docket number (xx4-20), and exact match Date (04/15/2020)
- [ ] Results display “Memorandum opinion” an exact match keyword (supplemental)  and exact match docket number (xx4-20), and exact match Date (04/20/2020)

#### Scenario 8 - CMS user searches for Opinion by keyword, and Opinion type (exact) 
1. Navigate to Advanced Search
2. Click on the Opinion tab
3. Enter in keyword supplemental
4. Select summary opinion for opinion type dropdown
5. Click search
Expected result
- [ ] Results display “summary opinion” an exact match keyword (supplemental) for case (xx1-20)
- [ ] Results display “summary opinion” an exact match keyword (supplemental)for case (xx4-20)

#### Scenario 9 - CMS user searches for Opinion by keyword, Opinion type (exact), and judge 
1. Navigate to Advanced Search
2. Click on the Opinion tab
3. Enter in keyword supplemental
4. Enter in docket number (xx1-20)
5. Select Summary opinion for opinion type dropdown
6. Enter judge (Cohen)
7. Click search
Expected result
- [ ] Results display “Summary Opinion” an exact match keyword (supplemental), exact match docket number (xx1-20), and exact match for judge (Cohen)

#### Scenario 5 - CMS user searches for Opinion by keyword, Opinion type (exact), judge, and date 
1. Navigate to Advanced Search
2. Click on the Opinion tab
3. Enter in keyword supplemental
4. Enter in docket number (xx1-20)
5. Enter judge (Cohen)
5. Click search
Expected result
- [ ] Results display “Summary Opinion” an exact match keyword (supplemental), exact match docket number (xx1-20), and exact match for judge (Cohen)

#### Scenario 10 - CMS user searches for Opinion by keyword, Opinion type (exact), and date
1. Navigate to Advanced Search
2. Click on the Opinion tab
3. Enter in keyword supplemental
4. Enter in docket number (xx1-20)
5. Enter judge (Cohen)
5. Click search
Expected result
- [ ] Results display “Summary Opinion” an exact match keyword (supplemental), exact match docket number (xx1-20), and exact match for judge (Cohen)


#### Scenario 11 - CMS user searches for Opinion by keyword, docket number (exact) and judge (exact)
1. Navigate to Advanced Search
2. Click on the Opinion tab
3. Enter in keyword supplemental
4. Enter in docket number (xx1-20)
5. Enter judge (Cohen)
5. Click search
Expected result
- [ ] Results display “Summary Opinion” an exact match keyword (supplemental), exact match docket number (xx1-20), and exact match for judge (Cohen)

#### Scenario 12 - CMS user searches for Opinion by keyword, judge (exact)
1. Navigate to Advanced Search
2. Click on the Opinion tab
3. Enter in keyword supplemental
4. Enter in docket number (xx1-20)
5. Enter judge (Cohen)
5. Click search
Expected result
- [ ] Results display “Summary Opinion” an exact match keyword (supplemental), exact match docket number (xx1-20), and exact match for judge (Cohen)

#### Scenario 13 - CMS user searches for Opinion by keyword, judge (exact), and date
1. Navigate to Advanced Search
2. Click on the Opinion tab
3. Enter in keyword supplemental
4. Enter in docket number (xx1-20)
5. Enter judge (Cohen)
5. Click search
Expected result
- [ ] Results display “Summary Opinion” an exact match keyword (supplemental), exact match docket number (xx1-20), and exact match for judge (Cohen)

#### Scenario 14 - CMS user searches for Opinion by keyword, and date
1. Navigate to Advanced Search
2. Click on the Opinion tab
3. Enter in keyword supplemental
4. Enter in docket number (xx1-20)
5. Enter judge (Cohen)
5. Click search
Expected result
- [ ] Results display “Summary Opinion” an exact match keyword (supplemental), exact match docket number (xx1-20), and exact match for judge (Cohen)

#### Scenario 15 - CMS user searches for Opinion by keyword, docket number, and case title
1. Navigate to Advanced Search
2. Click on the Opinion tab 
3. Enter keyword “affirmative” 
4. Enter docket number xx5-20
5. Enter case name “John” 
6. Click Search 
Expected results 
- [ ] form is not submitted
- [ ] Page-level error message displays “Please correct the following errors on the page: “Enter either a Docket number or a Case name/Petitioner name, not both”
- [ ] Field-level error message displays on docket number and case name fields “Enter either a Docket number or a Case name/Petitioner name, not both”

Errors on Date field
### Scenario 16 - CMS User enters an invalid date or date in the future - error message displays
1. Navigate to Advanced Search
2. Click on the Opinion tab
3. Enter in keyword supplemental
4. Enter in Date 05/33/2020-05/25/2020
5. Click search
Expected result
- [ ] orm is not submitted
- [ ] Page-level error message displays “Please correct the following errors on the page: Enter a valid start date, enter a valid end date”
- [ ] Field-level error message displays on docket number and case name fields “Enter a valid start date”
- [ ] Field-level error message displays on docket number and case name fields “Enter a valid end date”

### Scenario 17 - CMS User enters date in only the second set of date range fields- error message displays
1. Navigate to Advanced Search
2. Click on the Opinion tab
3. Enter in keyword supplemental
4. Enter in Date 05/25/2020  in second date field set
5. Click search
Expected result
- [ ] form is not submitted
- [ ] Page-level error message displays “Please correct the following errors on the page: Enter a valid start date.”
- [ ] Field-level error message displays on docket number and case name fields “Enter a valid start date.”

——————————————————————————————————————
Test Set Up-

* Case xx9-20
    * e-File petition for Petitioner and Spouse submitted
        * Brian Carswell and Tiffany Carswell
    * Create, sign, serve T.C. Opinion
        * Signed by Judge Pugh
        * Include keyword “Pursuant”
    * Create, sign, serve Summary Opinion 
        * Signed by Judge Pugh
    * Create, sign, serve Summary opinion 
        * Signed by Judge Pugh
        * Include keyword “Pursuant”
* Case x10-20
    * e-File petition for Corporation submitted
        * ABC Corporation
        * c/o Fredrick Flagstaff 
    * Create, sign, serve Memorandum opinion
        * Signed by Judge Pugh
        * Include keyword “distribution”
        * Filed Date 04/22/2020
* Case x11-20
    * e-File petition for Corporation submitted
        * ABC
    * Create, sign, serve TC Opinion 
        * Signed by Judge Pugh
        * Include keyword “distribution”
        * Filed Date 04/23/2020

* Case x12-20
    * e-File petition for petitioner submitted
        * Hector Whitehall 
    * Create, sign, serve TC opinion
        * Signed by Judge Buch
        * Include keyword “School Funding”
        * Filed Date 04/2/2020
    * Create, sign, serve Summary opinion 
        * Signed by Judge Buch
        * Include keyword “School”
        * Filed Date 04/1/2020
* Case x13-20
    * e-File petition for petitioner submitted
        * Whitehall & Sons
    * Create, sign, serve Memorandum opinion 
        * Signed by Judge Buch
        * Include keyword “Funding”
        * Filed Date 04/2/2020

* Case x14-20
    * e-File petition for Petitioner
        * Brian Carswell
    * Create, sign, serve Summary Opinion 
        * Signed by Judge Pugh
        * Include keyword “Pursuant”
	* Filed Date 04/30/2020

    * Create, sign, serve TC Opinion 
        * Signed by Judge Pugh
        * Include keyword “supplemental”
* Case x15-20
    * e-File petition for Petitioner
        * Brian McClintock
    * Create, sign, serve Summary Opinion
        * Signed by Judge Pugh
        * Include keyword “Pursuant”
	* Filed Date 04/25/2020
___________________________________________________________________________________________________________

#### Scenario 18 - CMS user searches for Opinion by keyword and case title 
1. Navigate to Advanced Search
2. Click on the Opinion tab
3. Enter keyword “Pursuant” 
4. Enter Case Name “Brian Carswell and Tiffany Carswell”
5. Click Search 
Expected results 
- [ ] Results display “TC opinion” an exact match keyword (Pursuant) and exact match case title (Brian Carswell and Tiffany Carswell) for case (xx9-20)
- [ ] Results display “Summary opinion” an exact match keyword (Pursuant) and exact match case title (Brian Carswell and Tiffany Carswell) for case (xx9-20)
- [ ] Results display “Summary Opinion” an exact match keyword (Pursuant) and partial match case title (Brian Carswell) for case (x14-20) 
- [ ] Results display “Summary Opinion” an exact match keyword (Pursuant), and partial match case title (Brian McClintock) for case (x15-20)

#### Scenario 19 - CMS user searches for Opinion by keyword  and case title- (no matches) 
1. Navigate to Advanced Search
2. Click on the Opinion tab 
3. Enter keyword “Drive” 
4. Enter Case Name “Robert Mathew Weir”
5. Click Search 
Expected results 
- [x] “No matching results” message displays 

#### Scenario 20 - CMS user searches for Opinion by keyword, case title, opinion type
1. Navigate to Advanced Search
2. Click on the Opinion tab 
3. Enter keyword “Pursuant” 
4. Enter Case Name “Brian Carswell”
5. Select Summary opinion from opinion type drop down
6. Click Search 
Expected results 
- [ ] Results display “Summary opinion” an exact match keyword (Pursuant) and exact match case title (Brian Carswell and Tiffany Carswell) for case (xx9-20)
- [ ] Results display “Summary Opinion” an exact match keyword (Pursuant) and partial match case title (Brian Carswell) for case (x14-20) 
- [ ] Results display “Summary Opinion” an exact match keyword (Pursuant), and partial match case title (Brian McClintock) for case (x15-20)

#### Scenario 21 - CMS user searches for Opinion by keyword, case title, opinion type, and judge
1. Navigate to Advanced Search
2. Click on the Opinion tab 
3. Enter keyword “Pursuant” 
4. Enter Case Name “Brian Carswell”
5. Select Summary opinion from opinion type drop down
6. Select Judge Pugh from Judge dropdown
7. Click Search 
Expected results 
- [ ] Results display “Summary opinion” an exact match keyword (Pursuant) and exact match case title (Brian Carswell and Tiffany Carswell), and exact match for Judge (Pugh) for case (xx9-20)
- [ ] Results display Results display “Summary Opinion” an exact match keyword (Pursuant) and partial match case title (Brian Carswell), and exact match for Judge (Pugh) for case (x14-20)
- [ ] Results display “Summary Opinion” an exact match keyword (Pursuant), and partial match case title (Brian McClintock), and exact match for Judge (Pugh) for case (x15-20)

#### Scenario 22 - CMS user searches for Opinion by keyword, case title, opinion type, judge, and date range
1. Navigate to Advanced Search
2. Click on the Opinion tab 
3. Enter keyword “Pursuant” 
4. Enter Case Name “Brian Carswel”
5. Select Summary opinion from opinion type drop down
5. Select Judge Pugh from Judge dropdown
6. Enter in 04/30/2020 in start date
7. Click Search 
Expected results 
- [ ] Results display “Summary Opinion” an exact match keyword (Pursuant) and partial match case title (Brian Carswell), exact match for Judge (Pugh), and exact match for 4/30/2020 in start date for case (x14-20)
- [ ] Results display “Summary Opinion” an exact match keyword (Pursuant) and partial match case title (Brian McClintock), exact match for Judge (Pugh) and exact match for 4/25/2020 in date range for case (x15-20)

#### Scenario 23 - CMS user searches for Opinion by keyword, case title, and judge 
1. Navigate to Advanced Search
2. Click on the Opinion tab 
3. Enter keyword “Pursuant” 
4. Enter Case Name “Brian Carswel”
5. Select Judge Pugh from Judge dropdown
6. Click Search 
Expected results 
- [ ] Results display “Summary opinion” an exact match keyword (Pursuant) and exact match case title (Brian Carswell and Tiffany Carswell), and exact match for Judge (Pugh) for case (xx9-20)
- [ ] Results display Results display “Summary Opinion” an exact match keyword (Pursuant) and partial match case title (Brian Carswell), and exact match for Judge (Pugh) for case (x14-20)
- [ ] Results display “Summary Opinion” an exact match keyword (Pursuant), and partial match case title (Brian McClintock), and exact match for Judge (Pugh) for case (x15-20)

#### Scenario 24 - CMS user searches for Opinion by keyword, case title, judge and date
1. Navigate to Advanced Search
2. Click on the Opinion tab 
3. Enter Keyword ”distribution”
4. Enter Case Name “ABC Corporation”
5. Select Judge Pugh from Judge dropdown
6. Enter Date- 04/02/20- 04/02/2020
7. Click Search 
Expected results 
- [ ] Results display “Memorandum opinion” an exact match keyword (distribution), exact match case title (ABC Corporation), exact match Judge (Judge Pugh), and exact match date (04/22/2020)  for case (x10-20)
- [ ] Results display “TC Opinion” an exact match keyword (distribution) and partial match case title (ABC) , exact match Judge (Judge Pugh), and exact match date (04/23/2020)  for case (x11-20)


#### Scenario 25 - CMS user searches for Opinion by keyword , case title , and date (range) with multiple results 
1. Navigate to Advanced Search
2. Click on the Opinion tab  
3. Enter keyword “School Funding” 
4. Enter Case Name “Hector Whitehall”
5.  Enter Date range - 3/31/19 - 04/03/20
6. Click Search 
Expected results 
- [ ] Results display “tc opinion” an exact match keyword (School Funding), exact match case title (Hector Whitehall), and exact match date (04/02/2020)  for case (x12-20) 
- [ ] Results display “summary opinion” a partial match keyword (School), exact match case title (Hector Whitehall), and exact match date (04/02/2020)  for case (x12-20)
- [ ] Results display “Memorandum opinion” an exact match keyword  (Funding), partial match case title (Whitehall) , and exact match date (04/02/2020)  for case (x13-20)

**Comment by alsmith1** [comment]
Staging docket numbers for testing
Xx9-20 = 140-20L
Xx9-20 = 140-20L
Xx9-20 = 140-20L
Xx9-20 = 140-20L
X10-20 = 141-20X
X11-20 = 143-20P
X12-20 = 144-20R
X13-20 = 145-20S
X14-20 = 147-20
X15-20 = 149-20S

**Comment by alsmith1** [comment]
test set-up for dev
xx1-20 --> 117-20
xx2-20 --> 119-20
xx3-20 --> 121-20
xx4-20 --> 123-20
xx5-20 --> 125-20

**Comment by alsmith1** [comment]
STG data cases
xx1-20 -->174-20
xx2-20 -->146-20
xx3-20 -->148-20
xx4-20 -->179-20
xx5-20 -->182-20
