### ISSUE TITLE
CMS Users: Order search - display number of pages in search results

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4853]
As a CMS user, so that I may easily identify which orders are substantive in nature, I need to know how many pages are included in the order when I perform an order search

## Acceptance Criteria
* When user performs an order search they can see in the results how many pages are in each document.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by mariahkannenberg** [comment]
![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/a417a108-43a3-4c7f-a53a-d8077981913b)

**Comment by alsmith1** [comment]
Test Scenarios

Scenario 1 - Display pages column in search results between Order and Date
Preform test as internal/external user/ Public User
1. Navigate to the Advanced Search
2. Click on the Order tab
3. Enter Keyword “Decision”
4. Click Search

Expected result
- [ ] Order tab displays on advanced search screen
- [ ] Enter Keyword or Phrase displays as a header with Search for ... above the search box
- [ ] Results table displays with results from keyword search
- [ ] Page column displays in Search results table between Order and Date columns


Scenario 2 - Data that displays in pages column is the number of pages that make up the document
Preform test as internal/external user/ Public User
1. Navigate to the Advanced Search
2. Click on the Order tab
3. Enter Keyword “Decision”
4. Click Search
5. Click on a order in the results table and verify the number of pages

Expected result
- [ ] Order tab displays on advanced search screen
- [ ] Enter Keyword or Phrase displays as a header with Search for ... above the search box
- [ ] Results table displays with results from keyword search
- [ ] Page column displays in Search results table between Order and Date columns
- [ ] In results table under Page column displays amount of pages per each order
- [ ] Page count in results table matches page count in order document
