### ISSUE TITLE
Document-level required fields

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#5039]
As the Court, in order to make sure that the legacy data is usable in the new system, we need to document the required fields at the document level.

## Acceptance Criteria: ##
* Document the required fields at the document level.
   * Required fields for concatenating name can be ignored.
   * Examples of required fields would be:
     1. Filing party
     2. Judge for all orders and opinions

Note - @klohman Add documentation to API documentation

Documentation to be implemented as separate stories:
#5313 - Required fields for Orders and Opinions
#5314 - Document that filing party is required for all external docs (electronic/paper)

**Comment by adunkman** [comment]
/cc @mark-meyer, this was discussed in today’s sprint planning. We decided that it made most sense to keep this documentation alongside EF-CMS’s API documentation somewhere (wherever makes sense).

@klohman, @mark-meyer will be your point of contact if you have any questions about acceptance criteria or just want a pal! 🎉
