### ISSUE TITLE
Today's Opinions

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#5158]
As the Court, so that we can publicly display the opinions that were released on that day, we need to display "Today's Opinions" on the Court's website.

## Acceptance Criteria
* Need a pre-filtered view for "Today's Opinions"
* Need to have that displayed on Court's website vs. within EF-CMS

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by alsmith1** [comment]
![Screen Shot 2020-05-29 at 12.49.34 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/32ed59b8-025b-4514-91cb-d76e91831bd8)

Need to display "Today's Opinions" on the Court's website for the opinions that were released that day

-this will be a link we will need to give to the court’s design team to add in as an iframe to the court’s main site (possibly)
- need to pre-filter the opinion search to display only results for “today”
- can use same results table from opinion search
- need to display 
    - the court header
    - today’s results banner
    - results table with all the fields as opinion search
    - can we filter by opinion type alpha?

**Comment by alsmith1** [comment]
Test Scenarios

### Scenario 1 - A member of the public or court user accesses the today’s opinions
1. As a court user or member of the public go to:https://www.xxx.com 
Expected result
- [ ] Today’s opinions display with 	- the court header
	- Today’s Opinions blue header
	- Today’s Date
- [ ] Results table
	- Docket number with link to docket
	- Case Title
	- Opinion Type with link to PDF document
	- Pages
    - Date
    - Judge
- [ ] Cases displayed in results table are all “today’s” Date
- [ ] Cases displayed in results are ONLY opinions
- [ ] No Sealed lock icon displays next to any opinion in a sealed case

**Comment by JessicaMarine** [comment]
PO comments: To test on staging, you must go to: https://ui-public-stg.ustc-case-mgmt.flexion.us/todays-opinions
