### ISSUE TITLE
Internal user: See unread messages in work queue

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#517]
As an internal user, in order to properly prioritize work, I need to see easily see my unread messages in my work queue.

An internal user will be working from their work queue throughout the day.  Since this is a dynamic work queue (items coming in and going out), the internal user will need to easily see when they get a new work item.

## Pre-Conditions
* Internal user is logged into the System.
* Internal user is viewing their work queue.

## Acceptance Criteria
* User can easily see which items in their work queue have not been read in their Individual Queue.
* User can easily see how many unread items are in their individual work queue.
* Apply this change to all internal users.

## Notes
* Section Queue has no concept of Read/Unread and only in the individual queue
* Users cannot mark a message as Unread

## Tasks
- [x] update work queue view (Matt)
- [x] update computed with unread flags (Eric)
- [x] update computed with unread count (Eric)
- [x] add read status work item entity (Eric)
- [x] add set read status when assigning work item
- [x] add set read when clicking link on the work queue
- [x] add use case for marking item as read (Cody)
- [x] integration and testing

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x] README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by sarahridgway** [comment]
*Unread Messages in Work Queue*

Messages in an individual's work queue which have not yet been opened will appear in with an unread messages style.

For standard unread work items / messages show:

- font awesome closed envelope icon in #0071BC height 15px, width 20px
- bold linked text for the document title onl

y


- standard hover state color for text and icon 

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/d51f5ed8-95df-4481-ae44-6223aad69cf8)

For standard read work items / messages show:

- no icon
- regular weight linked text for the document title only

For recalled unread work items show: 

- red clock icon (already implemented)
- bold link text for the document title

For recalled read work items show:

- red clock icon (already implemented)
- regular weight linked text for the document title only

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/cef2aff0-12ac-43e7-8b61-8de50f4262f5)

**Comment by matthopson** [comment]
@sarahridgway Should we include an unread count on here? Per AC, line 2: `User can easily see how many unread items are in their individual work queue.`

**Comment by sarahridgway** [comment]
@matthopson Thanks for catching that! Will run the design through review and update the comments and Figma on Wednesday.

**Comment by sarahridgway** [comment]
**Unread Messages Count**

A badge near the Work Queue H1 will display the number of unread messages in the user's personal inbox.

- Count each unread row in the work queue table as 1 unread message
- Badge bg | color: #205493
- Badge text | face: source sans pro; size: 17px;  color: #FFFFFF

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/3790f405-66c4-4e99-aede-ad6d6679431e)

**Deep Link & Highlight Relevant Message in Messages Tab**

When clicking on a link in the work queue, show the Messages tab and highlight the linked message. This action (and only this action) marks only the linked message as "read." 

- Message border highlight | stroke width: 3px; stroke color: #0071BC

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/edea3d23-303e-40e6-b021-2f5d97791530)

**Notes** 

- Users who navigate to the messages tab in any way other than by clicking a link in their work queue shall not cause any messages to be marked as "read."

- Users will not, at this time, have the ability to manually mark messages as "read"

**Comment by matthopson** [comment]
@sarahridgway When we use color values, could we also reference them from our own color variables or here https://designsystem.digital.gov/components/colors/ when applicable?

I still like seeing the hex value, but not having to work out if this is a standard variable or something already added to our styles / needs to be added to styles, etc... would be helpful.

**Comment by sarahridgway** [comment]
@matthopson Can do! I'll update the comments above.

**Comment by JessicaMarine** [comment]
QA notes 4/26/19:
* The new message count is 1 higher than the new messages appearing in the Inbox
