### ISSUE TITLE
Data Migration: More than 2 Petitioners (Multiple Petitioners))

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#5430]
As the Court, in order to make sure that the legacy data with respect to more than two petitioners is not lost, we need a way to allow information for more than two petitioners to be migrated (where applicable).

The Court has legacy with more than 2 petitioners.  While we are NOT dealing with the UI for this for MVP, we do need a way to allow those data points to migrate from legacy database as part of the data migration.

## Acceptance Criteria: ##
* As part of the data migration, the CMS must allow information for more than two petitioners to be migrated (where applicable).
* Information for each petitioner: Name (required), 
- Title  (optional) 
- address 1 (required), 
- address 2 (optional) 
- address 3 (optional) 
- City (required),
- State (required)
- Zip (required)
- phone number (optional), 
- email address (optional), 
- service indicator (required)
* Whatever is marked as the first one (or two) petitioners in the legacy data are the one (or two) who display in the CMS -- depending on party type. [May need to discuss to Mike/data migration team]
* need email address displayed for legacy and new cases
*Update migration documentation as needed 
* Keep Migration team informed on any updates and/or changes

## Notes: ##
* Dealing with UI for more than 2 petitioners is not part of MVP
I *Story will not be tested until legacy data starts migrating. Any issues will be addressed then.

## Definition of Done (Updated 6-19-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by mariahkannenberg** [comment]
Notes from 6/15 design meeting w/Mike, Mark and Loretta
Primary and secondary (petitioner +spouse) - populated into the UI. 
Additional petitioners populated only to the back end. 
Include "paper" identifier. 
Leave roles blank for legacy data (contact type)
Include additional petitioners in the UI as read only, so we can test appropriately. 
Start w/one party type. 
Start w/a case that has multiple executors. 
12492-06 (Legacy case w/3 executors) Mike to provide more. 
12328-06
013193-13 (x3)
013244-16 (x4)
Mike to identify all the cases in legacy data that are open and have more than 2 petitioners, so Jessica can identify all of the party types. 
Amy to mock up UI


Open questions:
Different party types have different required fields for primary and secondary. 
- When we add more than two parties, what is required for additional contacts?
- What is the structure of the legacy data for additional contact fields?

**Comment by alsmith1** [comment]
![Screen Shot 2020-06-18 at 1.31.30 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/5bebbfd0-4d2c-4ce7-a040-a9bf855323a0)

![Screen Shot 2020-06-18 at 1.31.41 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/642d906e-d02f-425c-b6d2-d6ab82d14408)

![Screen Shot 2020-06-18 at 1.31.48 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/0f6c759d-1d25-4b12-9eb8-0a9d5f980ad7)

![Screen Shot 2020-06-18 at 1.31.56 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/43c219f8-5adf-4427-9357-c75428ace6c8)

![Screen Shot 2020-06-18 at 1.32.03 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/a96a915d-9f79-4b4a-88bd-d0e3dafe02a1)

![Screen Shot 2020-06-18 at 1.32.12 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/2b681848-8be5-4492-9caa-883ef5b241f2)

![Screen Shot 2020-06-18 at 1.32.20 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/7920378f-9be5-49ec-8bc7-fd4b7b7e5803)

![Screen Shot 2020-06-18 at 1.32.29 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/d9c31af8-caea-4e15-9bef-51147499b48e)

![Screen Shot 2020-06-18 at 1.32.37 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/9f701609-64df-4ab7-8ed1-dc4d9096bb25)

![Screen Shot 2020-06-18 at 1.32.46 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/a782d4a1-e79e-4b9a-b2d7-053e27b89677)

![Screen Shot 2020-06-18 at 1.32.55 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/4d9c5e5a-03fe-489b-b456-cea58f7cca91)

![Screen Shot 2020-06-18 at 1.33.02 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/7f18c813-f241-4b7c-9886-65e30debd899)

![Screen Shot 2020-06-18 at 1.33.09 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/078e7eff-0562-4c1c-bcfb-f6126d18c66d)

![Screen Shot 2020-06-18 at 1.33.15 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/67bf58c5-7c52-449d-b1cb-567fb9241aa0)

![Screen Shot 2020-06-18 at 1.33.23 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/4149eea3-758f-4573-9063-4a507d6b9b41)

![Screen Shot 2020-06-18 at 1.33.31 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/288124b6-a33a-4030-8594-bd8d41cf3e2f)

![Screen Shot 2020-06-18 at 1.33.46 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/b1eb15e2-fe6f-4c98-9472-d6f9f286457f)

**Comment by alsmith1** [comment]
design notes:
Case information > Petitioner

- Petitioner Contact tile stays as is when displaying Petitioner
- When no spouse contact available petitioner tile spans cross page

Other Petitioner Info Tile
- displays under the main petitioner contact tile
- Can display 5 contacts across if available
- View additional Petitioners link will expand the other petitioner info tile to display the rest of the other petitioners if available
-  When the other petitioner info tile is expanded view additional petitioners link changes to Hide Additional petitioners
- Default state on page load has fist row displayed with view additional petitioners link

Fields needed for other petitioner information (Petitioner)
- Name (required), 
- Title  (optional) 
- address 1 (required), 
- address 2 (optional) 
- address 3 (optional) 
- City (required),
- State (required)
- Zip (required)
- phone number (optional), 
- email address (optional), 
- service indicator (required)

For this story other petitioners are read only


Case information > Petitioner

- Petitioner Contact tile stays as is when displaying Petitioner and spouse (living or dead)
- When no spouse contact available petitioner tile spans cross page

Other Petitioner Info Tile
- displays under the main petitioner contact tile
- Can display 5 contacts across if available
- View additional Petitioners link will expand the other petitioner info tile to display the rest of the other petitioners if available
-  When the other petitioner info tile is expanded view additional petitioners link changes to Hide Additional petitioners

Fields needed for other petitioner information (Petitioner & deceased spouse)
- Name (required), 
- Title  (optional) 
- address 1 (required), 
- address 2 (optional) 
- address 3 (optional) 
- City (required),
- State (required)
- Zip (required)
- phone number (optional), 
- email address (optional), 
- service indicator (required)

For this story other petitioners are read only


Case information > Petitioner 

- Petitioner Contact tile stays as is when displaying Petitioner and spouse (living or dead)
- When no spouse contact available petitioner tile spans cross page

Other Petitioner Info Tile
- displays under the main petitioner contact tile
- Can display 5 contacts across if available
- View additional Petitioners link will expand the other petitioner info tile to display the rest of the other petitioners if available
-  When the other petitioner info tile is expanded view additional petitioners link changes to Hide Additional petitioners

Fields needed for other petitioner information (Petitioner & spouse)
- Name (required), 
- Title  (optional) 
- address 1 (required), 
- address 2 (optional) 
- address 3 (optional) 
- City (required),
- State (required)
- Zip (required)
- phone number (optional), 
- email address (optional), 
- service indicator (required)

For this story other petitioners are read only


Case information > Petitioner

- Petitioner Contact tile stays as is when displaying Estate with an executor/personal representative/fiduciary/etc.
- When no spouse contact available petitioner tile spans cross page

Other Petitioner Info Tile
- displays under the main petitioner contact tile
- Can display 5 contacts across if available
- View additional Petitioners link will expand the other petitioner info tile to display the rest of the other petitioners if available
-  When the other petitioner info tile is expanded view additional petitioners link changes to Hide Additional petitioners

Fields needed for other petitioner information (Estate with an executor/personal representative/fiduciary/etc.)
- Name (required), 
- Title  (optional) 
- address 1 (required), 
- address 2 (optional) 
- address 3 (optional) 
- City (required),
- State (required)
- Zip (required)
- phone number (optional), 
- email address (optional), 
- service indicator (required)

For this story other petitioners are read only


Case information > Petitioner

- Petitioner Contact tile stays as is when displaying Guardian.
- When no spouse contact available petitioner tile spans cross page

Other Petitioner Info Tile
- displays under the main petitioner contact tile
- Can display 5 contacts across if available
- View additional Petitioners link will expand the other petitioner info tile to display the rest of the other petitioners if available
-  When the other petitioner info tile is expanded view additional petitioners link changes to Hide Additional petitioners

Fields needed for other petitioner information (Guardian)
- Name (required), 
- Title  (optional) 
- address 1 (required), 
- address 2 (optional) 
- address 3 (optional) 
- City (required),
- State (required)
- Zip (required)
- phone number (optional), 
- email address (optional), 
- service indicator (required)

For this story other petitioners are read only


Case information > Petitioner

- Petitioner Contact tile stays as is when displaying Conservator.
- When no spouse contact available petitioner tile spans cross page

Other Petitioner Info Tile
- displays under the main petitioner contact tile
- Can display 5 contacts across if available
- View additional Petitioners link will expand the other petitioner info tile to display the rest of the other petitioners if available
-  When the other petitioner info tile is expanded view additional petitioners link changes to Hide Additional petitioners

Fields needed for other petitioner information (Conservator)
- Name (required), 
- Title  (optional) 
- address 1 (required), 
- address 2 (optional) 
- address 3 (optional) 
- City (required),
- State (required)
- Zip (required)
- phone number (optional), 
- email address (optional), 
- service indicator (required)

For this story other petitioners are read only


Case information > Petitioner

- Petitioner Contact tile stays as is when displaying Custodian
- When no spouse contact available petitioner tile spans cross page

Other Petitioner Info Tile
- displays under the main petitioner contact tile
- Can display 5 contacts across if available
- View additional Petitioners link will expand the other petitioner info tile to display the rest of the other petitioners if available
-  When the other petitioner info tile is expanded view additional petitioners link changes to Hide Additional petitioners

Fields needed for other petitioner information (Custodian)
- Name (required), 
- Title  (optional) 
- address 1 (required), 
- address 2 (optional) 
- address 3 (optional) 
- City (required),
- State (required)
- Zip (required)
- phone number (optional), 
- email address (optional), 
- service indicator (required)

For this story other petitioners are read only


Case information > Petitioner

- Petitioner Contact tile stays as is when displaying Trust.
- When no spouse contact available petitioner tile spans cross page

Other Petitioner Info Tile
- displays under the main petitioner contact tile
- Can display 5 contacts across if available
- View additional Petitioners link will expand the other petitioner info tile to display the rest of the other petitioners if available
-  When the other petitioner info tile is expanded view additional petitioners link changes to Hide Additional petitioners

Fields needed for other petitioner information (Trust)
- Name (required), 
- Title  (optional) 
- address 1 (required), 
- address 2 (optional) 
- address 3 (optional) 
- City (required),
- State (required)
- Zip (required)
- phone number (optional), 
- email address (optional), 
- service indicator (required)

For this story other petitioners are read only


Case information > Petitioner

- Petitioner Contact tile stays as is when displaying Partnership (as a partnership representative under the BBA regime).
- When no spouse contact available petitioner tile spans cross page

Other Petitioner Info Tile
- displays under the main petitioner contact tile
- Can display 5 contacts across if available
- View additional Petitioners link will expand the other petitioner info tile to display the rest of the other petitioners if available
-  When the other petitioner info tile is expanded view additional petitioners link changes to Hide Additional petitioners

Fields needed for other petitioner information (Partnership (as a partnership representative under the BBA regime))
- Name (required), 
- Title  (optional) 
- address 1 (required), 
- address 2 (optional) 
- address 3 (optional) 
- City (required),
- State (required)
- Zip (required)
- phone number (optional), 
- email address (optional), 
- service indicator (required)

For this story other petitioners are read only


Case information > Petitioner

- Petitioner Contact tile stays as is when displaying Partnership (as the Tax Matters Partner).
- When no spouse contact available petitioner tile spans cross page

Other Petitioner Info Tile
- displays under the main petitioner contact tile
- Can display 5 contacts across if available
- View additional Petitioners link will expand the other petitioner info tile to display the rest of the other petitioners if available
-  When the other petitioner info tile is expanded view additional petitioners link changes to Hide Additional petitioners

Fields needed for other petitioner information (Partnership (as the Tax Matters Partner))
- Name (required), 
- Title  (optional) 
- address 1 (required), 
- address 2 (optional) 
- address 3 (optional) 
- City (required),
- State (required)
- Zip (required)
- phone number (optional), 
- email address (optional), 
- service indicator (required)

For this story other petitioners are read only


Case information > Petitioner

- Petitioner Contact tile stays as is when displaying Partnership (as a partner other than Tax Matters Partner)
- When no spouse contact available petitioner tile spans cross page

Other Petitioner Info Tile
- displays under the main petitioner contact tile
- Can display 5 contacts across if available
- View additional Petitioners link will expand the other petitioner info tile to display the rest of the other petitioners if available
-  When the other petitioner info tile is expanded view additional petitioners link changes to Hide Additional petitioners

Fields needed for other petitioner information (Partnership (as a partner other than Tax Matters Partner))
- Name (required), 
- Title  (optional) 
- address 1 (required), 
- address 2 (optional) 
- address 3 (optional) 
- City (required),
- State (required)
- Zip (required)
- phone number (optional), 
- email address (optional), 
- service indicator (required)

For this story other petitioners are read only


Case information > Petitioner

- Petitioner Contact tile stays as is when displaying Corporation
- When no spouse contact available petitioner tile spans cross page

Other Petitioner Info Tile
- displays under the main petitioner contact tile
- Can display 5 contacts across if available
- View additional Petitioners link will expand the other petitioner info tile to display the rest of the other petitioners if available
-  When the other petitioner info tile is expanded view additional petitioners link changes to Hide Additional petitioners

Fields needed for other petitioner information (Corporation)
- Name (required), 
- Title  (optional) 
- address 1 (required), 
- address 2 (optional) 
- address 3 (optional) 
- City (required),
- State (required)
- Zip (required)
- phone number (optional), 
- email address (optional), 
- service indicator (required)

For this story other petitioners are read only


Case information > Petitioner

- Petitioner Contact tile stays as is when displaying Next friend for a legally incompetent person (without a guardian, conservator, or other like fiduciary)
- When no spouse contact available petitioner tile spans cross page

Other Petitioner Info Tile
- displays under the main petitioner contact tile
- Can display 5 contacts across if available
- View additional Petitioners link will expand the other petitioner info tile to display the rest of the other petitioners if available
-  When the other petitioner info tile is expanded view additional petitioners link changes to Hide Additional petitioners

Fields needed for other petitioner information (Next friend for a legally incompetent person (without a guardian, conservator, or other like fiduciary))
- Name (required), 
- Title  (optional) 
- address 1 (required), 
- address 2 (optional) 
- address 3 (optional) 
- City (required),
- State (required)
- Zip (required)
- phone number (optional), 
- email address (optional), 
- service indicator (required)

For this story other petitioners are read only


Case information > Petitioner

- Petitioner Contact tile stays as is when displaying Transferee.
- When no spouse contact available petitioner tile spans cross page

Other Petitioner Info Tile
- displays under the main petitioner contact tile
- Can display 5 contacts across if available
- View additional Petitioners link will expand the other petitioner info tile to display the rest of the other petitioners if available
-  When the other petitioner info tile is expanded view additional petitioners link changes to Hide Additional petitioners

Fields needed for other petitioner information (Transferee)
- Name (required), 
- Title  (optional) 
- address 1 (required), 
- address 2 (optional) 
- address 3 (optional) 
- City (required),
- State (required)
- Zip (required)
- phone number (optional), 
- email address (optional), 
- service indicator (required)

For this story other petitioners are read only

**Comment by alsmith1** [comment]
[https://app.zenhub.com/files/152320868/9e9e17de-4bd0-4df8-b54a-3173d3434ceb/download](https://app.zenhub.com/files/152320868/9e9e17de-4bd0-4df8-b54a-3173d3434ceb/download)

**Comment by alsmith1** [comment]
[https://app.zenhub.com/files/152320868/18d085d5-03fc-4e2f-be43-130f12dfa2fd/download](https://app.zenhub.com/files/152320868/18d085d5-03fc-4e2f-be43-130f12dfa2fd/download)

**Comment by alsmith1** [comment]
[https://app.zenhub.com/files/152320868/18d085d5-03fc-4e2f-be43-130f12dfa2fd/download](https://app.zenhub.com/files/152320868/18d085d5-03fc-4e2f-be43-130f12dfa2fd/download)
