### ISSUE TITLE
Data Migration: Stricken documents

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#5506]
As a Docket Clerk, in order to manage the docket record, I need the ability to strike an item from the record. 

In the legacy system, there are some documents that are `stricken` or `stricken and not viewable`.  If a document is striken, it currently has the date and the words of the entry crossed through, "(STRICKEN)" added to the end of the docket entry, but the hyperlink is still active.  If a document is striken and not viewable, it has the date and words of the entry crossed through, "(STRICKEN)" added to the end of the docket record, *and* the hyperlink is removed. [See comment for example]

## Acceptance Criteria: ##
* Docket Clerk can "strike" [this is a term of art at the Court] an item from the docket record
* When the item has been stricken, it remains on the docket record with the date and notice of proceedings crossed out and (STRICKEN)" in parens is at the end
* Once an item is stricken, the document is still viewable to all Court personnel (hyperlink still active), but is not visable to parties or public (no hyperlink)
* Update the migration documentation as needed

Consider whether additional work is needed for migration:
As the Court, in order to capture all the necessary data points from the legacy cases, we need to allow for a stricken document indicator to be ingested into the system.
* CMS must be able to accomodate a data point on all legacy documents of Stricken: Y/N
* CMS must be able to accomodate a data point on all legacy documents of Stricken and Not Viewable: Y/N 
* This new data point should be required for all legacy documents [Update document entity?]

## Definition of Done (Updated 6-19-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by JessicaMarine** [comment]
Sample of current UI:

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/b8481777-4803-4e17-85e7-50a75e9046bd)

**Comment by alsmith1** [comment]
![Screen Shot 2020-06-24 at 11.06.12 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/29ce2d30-5cb7-4d19-ac05-d0fbae820f4c)![Screen Shot 2020-06-24 at 11.06.23 AM.png]
Internal When the item has been stricken, it remains on the docket record with the date and notice of proceedings crossed out and (STRICKEN)" in parens is at the end
Once an item is stricken, the document is still viewable to all Court personnel (hyperlink still active)

(https://images.zenhubusercontent.com/5d766a771251c6000116623d/5b180900-f2bb-464f-9b39-323c1ed9ad7f)
External/Public When the item has been stricken, it remains on the docket record with the date and notice of proceedings crossed out and (STRICKEN)" in parens is at the end
Once an item is stricken, the document is not visable to parties or public (no hyperlink)

**Comment by alsmith1** [comment]
Test Scenarios

### Scenario 1 - Once a document is Stricken A Internal User sees the document crossed out on the Docket Record
1. Log in as a Docket Clerk/ Judge/ ADC/ Petitions Clerk…
2. Navigate to case (xxx-20)
3. Navigate to the docket record
Expected result
- [ ] Docket record displays a document that has been stricken by:
	- Date  and Filings and proceedings is crossed out
	- Filings and proceeding still links to the document

### Scenario 2 - Once a document is Stricken A petitioner, practitioner, IRS attorney sees the document crossed out on the Docket Record
1. Log in as a petitioner, practitioner, or IRS attorney 
2. Navigate to case (xxx-20)
3. Navigate to the docket record
Expected result
- [ ] Docket record displays a document that has been stricken by:
	- Date  and Filings and proceedings is crossed out
	- No link for Filings and proceeding
