### ISSUE TITLE
Senior Attorney: Expanded Work Queue

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#571]
As a Sr. Attorney when I open MyWork Queue, in order to prioritize my work, I need it to default to the expanded version so I can see the message.

**Comment by uxforgood** [comment]
Design concepts for this (May need updates when we work this story)

Individual queue

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/bc7524a2-2b8e-4f60-b41d-4dcc14afdacf)

Section queue

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/3a4b708d-e665-4ed3-a3fb-8cf460df9d53)
