### ISSUE TITLE
Petitioner: Yes/No logic with respect to IRS notice

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#588]
As a Petitioner, in order to provide accurate information to the Court, I need to indicate whether I've received an IRS notice when starting a case.

In most cases, a taxpayer must receive a notice from the IRS before filing a case with the Tax Court.  However, there are some instances where the taxpayer can file a Petition without having a notice.  It is important for the Court to know whether the taxpayer has a notice or not. 

## Pre-Conditions
* Petitioner has decided to Start a New Case

## Acceptance Criteria
* Petitioner must indicate whether they have received an IRS notice or not
* Petitioner should be presented with two different sets of Case Type options based on Yes-Notice vs. No-Notice
* The Petitions Clerk  needs to understand whether a notice has been provided or not during the QC process
* Any Court user needs to understand whether a notice has been provided or not

## Notes:
* Two separate case type lists based on Yes-Notice vs. No-Notice are below in comments.

## Tasks
- [x] Modify design of "Start a Case" page [Sarah]
- [x] Modify design of "Petition QC" page [Sarah]
- [x] Modify design of "Case Detail" page [Sarah]
- [x] Add mapping list [Sarah]
- [x] Modify entity validation rules (Kris)
- [x] Develop business tests (Rachael)
- [x] Modify views of start a new case screen (Rachael)
- [x] Change case type dropdown values based on yes/no notice (in view) (Rachael) 
- [X] Modify views of QC screen (Cody)
- [x] Modify view of case info tab to include "No notice" (Cody)
- [x] Fix bug where there is no way to remove an IRS notice date once it has been added 
- [x] Fix bug in which values persist in state (and are validated against) yet are not reflected in form; (clear some state values when validation requirements change?) (Rachael)
- [x] fix FontAwesome icon color on "before you start a case" (Kris)
- [x] fix notice date required on start case validation when hasIrsNotice is false (Kris)
- [x] look into date validation on petitions clerk side (can submit form, no errors with only month filled in, but it does not save) (Cody)

## Definition of Done
- [x] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [ ] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version

**Comment by JessicaMarine** [comment]
Case Types when “YES” IRS Notice:
	Deficiency--Notice of Deficiency
	CDP (Lien/Levy)--Notice of Determination Concerning Collection Action
	Innocent Spouse--Notice of Determination Concerning Relief From Joint and Several Liability Under Section 6015
	Readjustment of Partnership Items Code Section 6226
	Adjustment of Partnership Items Code Section 6228
	Partnership Action Under BBA Section 1101
	Whistleblower--Notice of Determination Under Section 7623 Concerning Whistleblower Action
	Worker Classification--Notice of Determination of Worker Classification
	Declaratory Judgment (Retirement Plan)
	Declaratory Judgment (Exempt Organization)
	Passport --Notice of Certification of Your Seriously Delinquent Federal Tax Debt to the Department of State
	Interest Abatement--Notice of Final Determination for Full or Partial Disallowance of Interest Abatement Claim
	Other

Case Types when “NO” IRS Notice:
	Deficiency
	CDP (Lien/Levy)
	Innocent Spouse
	Whistleblower
	Worker Classification
	Declaratory Judgment (Retirement Plan)
	Declaratory Judgment (Exempt Organization)
	Interest Abatement-- Failure of IRS to Make Final Determination Within 180 Days After Claim for Abatement
	Other

**Comment by sarahridgway** [comment]
Wireframes for 588 - Start a Case Form

Default presentation
![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/469f76d3-c357-4f06-8821-6bb6aa3cc906)

Petitioner selects "Yes"
![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/3eb7f1e1-7803-41d6-a4ee-a7ea0c796c9a)

Petitioner selects "No"

**Comment by sarahridgway** [comment]
Wireframes for 588 - Petition QC

Default QC presentation for a Petitioner who selected "yes," case type and notice date are pre-populated

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/f118adb2-6820-4f4e-8364-9e370fb2ddf2)

Petition Clerk selects "Yes" to indicate a notice is attached to the PDF, year and amount fields are revealed (blank)

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/9516b2d4-5c26-409f-8f61-d683e42773f0)

Petition Clerk selects "No" to indicate a notice is not attached to the PDF, pre-populated date information is deleted

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/11887ca8-cedc-4837-a695-af8d78c53393)

**Comment by sarahridgway** [comment]
Wireframes for 588 - Petition QC Continued

Default QC presentation for a Petitioner who selected "No," case type is pre-populated

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/30c689c9-63d4-4969-b100-fa5932dfc18d)

Petition Clerk selects "Yes" to indicate a notice has been attached to the PDF, notice date, year and amount fields are revealed (blank)

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/ab2ed51c-1e07-4eac-a84c-b2e92e1b0a55)

Petition Clerk selects "No" to indicate a notice has not been attached to the PDF
![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/521e3803-6c4e-4ca3-bb9f-605c9072ee2f)

**Comment by sarahridgway** [comment]
Wireframes for 588 - Case Information

If Petition Clerk submitted a case with notice date information, display notice date
![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/bdf16bd2-ba7d-4c99-b328-124db3149b17)

If Petition Clerk submitted a case without a date, display "No notice"
![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/57397c77-7fdf-4333-9891-28484898feef)

**Comment by sarahridgway** [comment]
@JessicaMarine can you confirm if this is how the options in the lists should display?

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/52ab1b36-06f9-4483-8a30-4048a15c64f7)

**Comment by sarahridgway** [comment]
![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/a834491a-9917-4468-a5c9-f8794ba46cdb)
