### ISSUE TITLE
Petitioner: Warning of timeliness of electronic Petition

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#644]
As the Clerk of the Court, in order to assure that the Petitioner is informed about filing their petition in a timely manner, I need the system to inform the petitioner about rules regarding timeliness of filing when they use the system and their options for filing offline, if necessary.

When a Petitioner indicates that they want to Start a New Case, one of the first things that they need to see is a warning explaining to them when an electronic Petition will be considered to be timely, and their other options if they cannot submit it electronically. This is important because, if a Petitioner submits a Petition to the Court even 1 day late, the Court lacks jurisdiction to hear the case. [Note: the eProjects committee developed some language previously for this purpose; I've put it in the comments as a starting point/something to discuss]

## Pre-Conditions
* Petitioner has indicated that they want to Start a New Case

## Acceptance Criteria
* Petitioner knows what it means to submit an electronic Petition timely
* Petitioner is provided with other options (mailing or hand-delivery) if they cannot submit case electronically
* Petitioner should not be allowed to move forward with filing a petition without acknowledging they have seen the timeliness messaging (do not need to store acknowledgement)

## Notes
* (1/28) Date will be on notice and we can add tell user to refer to notice. Tina's recommended language is, "...on the last date for your filing as described in your notification from the IRS"
* (1/28) Purpose of checkbox = an extra step to make user pause and read

## Tasks
- [x] 1. Design of the timeliness messaging and warning (Sarah)
- [x] 2. Design updates to Start a Case form including messaging (Kristen) 
- [x] 3. Develop business use test cases
- [x] 4. Build and implement view changes
- [x] 5. Modify existing "Start a case" view (will)
- [x] 6. Implement interstitial view (kris)
- [x] 7. Create new route to view/page (kris)

## Definition of Done
- [x] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version

**Comment by JessicaMarine** [comment]
This is language that was previously developed by the Court's eProjects committee:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/992a44dd-686f-48d0-90b3-bc8cb8951a20)

Let's discuss and revise as needed.

**Comment by tjcurington** [comment]
The user story is written from the perspective of the Clerk of the Courts. Can it be written from the perspective of the Petitioner. "As a Petitioner, I need to be informed of the Courts definition of "timely filing of a petition" so that I can file my petition in a timely manner to ensure Tax Court jurisdiction.

**Comment by klohman** [comment]
# Updated Start a Case form page 

## Overall Changes 
1) Removed the Before You Get Started Section 
2) Created a new section "Upload Your Petition to Start Your Case" and moved the Upload Your Petition field to this section
3) Created a new section for "Who is Filing this Case" 
4) Added radio button for "who are you filing for" field 
5) Added a reminder message for the "Who are you filing for" field 
6) Updated the styling of the reminder message fro the "Who are you filing for" and "Upload your Petition" fields  (previously was a blue box- check Figma for style guidelines) 
7) Added a checklist to the Review Your Information section 
8) Updated checkbox language to "Checking this box acknowledges that you’ve verified all information is correct."

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e9962655-d627-4673-9399-f9f0fb3c7001)

## Changes for 645 Verify that I am Filing for Myself 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/93c9ce76-545f-4896-bf2a-11dd746f3f0a)

- Radio button is unselected on page load

**Comment by klohman** [comment]
# Before You Begin page 

### Revisions to the page flow from petitioner dashboard to Start a Case Form 
- when user clicks on Start a Case button from their dashboard, direct them to the Before You Begin page. 
- On click of "Got It, Let's Start My Case" - direct user to Start a Case form 
- On click of Cancel, direct user back to dashboard 

### Links 
- USTC Form 2 - new tab - https://www.ustaxcourt.gov/forms/Petition_Simplified_Form_2.pdf
- Tax Court Rules of Practice and Procedure - new tab - https://www.ustaxcourt.gov/rules.htm
- Learn more about how to merge files into one PDF - link TBD 

![Dashboard- Petitioner -Updated Language from Court.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d57d44a4-3d20-4fd6-b185-4929e3c34142)

**Comment by klohman** [comment]
Custom Icon svg

![paperclip-no-icon.svg](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d96e7ca4-a646-4088-bd03-1d3ff41740be)

**Comment by tjcurington** [comment]
Cancel buttons will take you to the Dashboard.
