### ISSUE TITLE
Petitioner: International and Other Domestic Addresses and Phone Numbers

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#655]
As a Petitioner, In order to provide international addresses and phone numbers for any address I enter into the system, I need to the system to accommodate international address.

The Court occassionally has Petitioners who do not live in the United States.  The System needs to be accomodate to international addresses.

## Pre-Conditions:
* Petitioner has decided to Start a New Case

## Acceptance Criteria:
* Petitioner must be able to enter an international/unusual address for any address they can enter into the system
* The System can save and display international addresses

## Tasks
- [x] 1. Modify the Start a Case Form (Rachael)
- [x] 2. Update pa11y tests for Start a Case Form (Rachael)
- [x] 3. Update seed data with new required fields and international addresses (Rachael - PR)
- [x] 4. Update taxpayerCreatesNewCase business test with required fields, intl addresses (Kris)
- [x] 5. Modify the Case Information page (William)
- [x] 6. Find a better way to use object composition for creating some of these contact entities (Cody / Kris)
- [x] 7. Dry up the strings we are using throughout the code base and components (Cody)
- [x] 8. Come up with validation requirements for international addresses (UX)
- [x] 9. Create validation routines for international addresses (Eric & William)
- [x] 10. Change zip to postal code throughout code (Rachael)
- [x] 11. Reminder to revisit string constants from a CA perspective as part of refactoring at the end of this story (also clean up incomponentPerson -> incompetentPerson) (Cody)
- [x] 12. Reminder to revisit default countryType in updatePartyTypeAction (William)

## Definition of Done
- [x] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version

**Comment by uxforgood** [comment]
In the Start a Case form, everywhere there is an address (so for each party type), please make the following changes/additions: [The Name field label below would stay dynamic to whatever party type it's set for - so no change there from what was implemented in 307]

## Default addresses

1. Add Country dropdown to the top with the following options
    - United States [default]
    - International
2. Change "Street Address" to "Mailing Address" 
3. Change "Suite/Apt #" to "Address Line 2 (optional)" 
4. Add another optional field below Address Line 2 labeled "Address Line 3 (optional)" 
5. Update the States dropdown to include the following changes: 
   - Add subheadings to selection groups (see the trial locations dropdown for design/example) 
   - Subheadings should be "State" following by alpha listing of 50 states, then subheading "Other" followed by this list: 
         AA
         AE
         AP
         AS
         FM
         GU
         MH
         MP
         PW
         PR
         VI


![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/eeb89abf-afbe-430c-83b7-dca9fed9189c) 


## International addresses

If user selects "International" from the country dropdown, display the following fields (all are text fields, no dropdowns): 

- Country Name
- [dynamic name label]
- Mailing Address
- Address 2 (optional)
- Address 3 (optional)
- State/Province/Region
- City
- ZIP/Postal Code

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/9b58f070-d79c-4950-88cd-031b17a152ec)

**Comment by kkoskelin** [comment]
@uxforgood I'm wondering about the International address "ZIP/Postal Code".  The "ZIP" is a distinctly United States thing, as far as I know.  Can we stick with 'Postal Code' for the label?

**Comment by uxforgood** [comment]
@kkoskelin Yes I think we can just label that Postal Code. We took that label and group of form elements from an example that didn't first distinguish between US and international addresses, so was accommodating both. 

1. Please change label to "Postal Code" 
2. Also, as discussed, please add (optional) and remove from required validation rules to state/province/region as some addresses don't include this (like the London, England example) 

@sarahridgway @klohman @JessicaMarine  for reference
