### ISSUE TITLE
Petitions Clerk: Printable Summary of QC Changes

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#667]
As a Petitions Clerk, in order to have an easy check-list to know what Orders I need to issue, I need to have a printable summary of my QC changes.

## Definition of Done
- [ ] acceptance criteria have been met
- [ ] Field level and page level validation errors (front-end and server side) integrated and functioning
- [ ] all code changes have been reviewed, approved, and merged and deployed to develop 
- [ ] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [ ] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [ ] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [ ] 0 errors reported in manual a11y testing
- [ ] all new functionality verified to work with keyboard and osx voiceover
- [ ] all code quality checks are passing - sonar, eslint, html validation, etc.
- [ ] code refactored for clarity and to remove any known technical debt 
- [ ] application can be deployed to multiple regions
- [ ]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [ ] performance tests successfully completed and no new significant performance issues found
- [ ] alerting and monitoring for new functionality in place and successfully exercised
- [ ] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [ ] usability has been validated
- [ ] npm audit for CVE’s in production library/module dependencies identified and resolved
- [ ] library/module dependencies are up-to-date and are at the latest resolvable version

**Comment by uxforgood** [comment]
[dropping here]

## Confirmation summary screen

- User can see confirmation message of the batching to IRS
- Case can be seen as changed to "Batched for IRS"
- User can see the summary of all changes made to the Petition
   - This is the delta of values between when the petitioner submitted the Petition and when it was batched to IRS (don't have to display any intermediary or temporary changes made between those two states)
- "View Petition" button would take them to the document detail view of the Petition (now in "read only" mode with ability to recall from IRS batch)
- "Back" breadcrumb returns user to Individual Work Queue
   - This Petition / work queue item is no longer in their individual queue Inbox, but now in their Sent box

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/0b10597d-a703-4c96-9d36-fa5dab0d6df5)

**Comment by JessicaMarine** [comment]
Natalie:  Something to consider – maybe only changes to the fields that would require the Court to issue an Order should show up on this summary sheet.  We could mark that field-by-field
