### ISSUE TITLE
Server Error Handling - Global Solution and Implementation

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#676]
As a development team, we need to define and document our approach for server error handling, so we can implement global error handling as needed.

## Acceptance Criteria
* Define and document approach for server error handling
* Error statements and handling implemented for 
  * 401: User isn't logged in
  * 403: User is logged in, but doesn't have permission OR 404: Not Found
  * 4XX: Unexpected request from the client
  * 5XX: Something went wrong, we made a mistake in our code or configuration

## Tasks
- [x] 1. Design error statements for each error type- see comments and FIgma https://www.figma.com/file/MOgSt8RJaYnz3oyRPpTuTBrV/Sprint-7?node-id=2%3A1035 (Kristen)
- [x] 2. Design user flow - see comments (Kristen)
- [x] 3. Develop each error flow
- [x] 4. create cerebral error classes that represent each http status code grouping (see 514-errors-update for example) (kris) (done pr coming)
- [x] 5. add error factory and decorator to application context throws new cerebral error based on generic error (kris/cody) 
- [x] 6. implement Error jsx for new /error route (see 676-error-handling) (will/eric)
- [x] 7. add special handling for bad user on login page (red alert on login) (kris)
- [x] 8. figure out how to define route so all unknown routes go to unauthorizedErrorSequence (will pr out)
- [x] 9. how to mock provider with mockRejectedPromise per https://cerebraljs.com/docs/api/test.html and write tests? (eric)
- [x] 10. redirect to login page on 401 (will/eric)
- [x] 11. fix styling of error messages and make sure errornotification is placed properly on all views  below h1 (kris)

## Definition of Done
- [x] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version

**Comment by tjcurington** [comment]
Future Story:
* 401: User isn't logged in
* 403: User is logged in, but doesn't have permission
* 404: Not found
* 4XX: Unexpected request from the client
* 5XX: Something went wrong, we made a mistake in our code or configuration

**Comment by klohman** [comment]
# Error Messages and Flows 

## 401- User not logged in 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ee223cef-64c8-4f8e-88ce-6cbb99fd9778)

### Scenarios: 
User navigates to a URL but is not logged in 
User is timed out during a session and takes an action 

### Flow 
1) Direct user to Log In page with error message displays 
2) User authenticates 
3) Forward user to their requested page **


## 500 Series - Server Error 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/97e2da6d-6492-4ed6-81ff-4343bb0f3c4f)
## Scenarios: 
User attempts to perform action and an internal issue (code or configuration error; server issue ) prevents the success 

### Flow 
1) Remain on current page and display error message in standard location 
2) Error message remains until user navigates away from the page or performs another action on the page 
**Court is notified of errors via monitoring (later story) 

## 4xx series- Unexpected Request 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9d770709-ac9a-4cab-a1d3-cc539f595775)

### Scenarios: 
User’s request contains data inputs the server cannot understand 

### Flow 
1) Remain on current page and display error message in standard location 
2) Error message remains until user navigates away from the page or performs another action on the page 

## 403 Forbidden / 404 Not Found 

### Logged In  
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1abc9724-771c-41b9-a599-1901b2eb8371)

### Not Logged In 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7ca1dafe-2d8a-47b7-a65c-a92397de5a31)

### Scenarios: 
User is enters in an unknown URL 
User is logged in but does not have access to a known URL 

### Flow 
1) Direct user to the Error Page 
2) User can use the browser back button or the links provided on the error page to navigate to an available page
   - Back to Dashboard button- directs user to their dashboard 
   - Home button - directs user to the CMS Log In page
   - Go to the U.S. Tax Court Website button- directs user to https://www.ustaxcourt.gov/

**Comment by klohman** [comment]
# Error Message Placement 

## Log In Page 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4b0c26bf-3917-42bc-bb53-5ac278423c3b)

## Document Detail Page 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/de9711e4-ea5d-4ecf-b52f-1174761377fe)

## Case Detail Page 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9c9cdbb8-4ee4-437c-bd16-555e6d700dae)

## Work Queue 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6e36a258-6320-41e2-a56e-5b7eef5acd24)

**Comment by vbey** [comment]
Notes from January 29 design meeting

- Demo for 676. 
- Chris will make edits to error message format. Message box shouldn't go all the way across.
- Make login page for 401.
