### ISSUE TITLE
Automating OWASP Testing in CI

### ISSUE THREAD

**Issue by tjcurington** [flexion/ef-cms#697]
As a user of EF-CMS I need to be confident that the web application has been consistently tested for security vulneralbilities so that I may confidently use the system to submit a petition

**Comment by mariahkannenberg** [comment]
@waldoj 

For reference, all new stories get the MVP tag, which indicates that Jessica needs to review it. Just didn't want you to worry :)

**Comment by waldoj** [comment]
Thanks for the preemptive note! :)

**Comment by waldoj** [comment]
This probably shouldn't be assigned to me — although I don't object to helping with this, AFAIK this is at least 90% done, all by Flexion.

**Comment by mariahkannenberg** [comment]
Adding to technical backlog.
