### ISSUE TITLE
Petitioner: Link to Pay.gov to pay filing fee (1.2)

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#71]
As a petitioner, in order to  pay my filing fee, I want to link to pay.gov through the system.

After the case is created and Petitioner has a Docket #, the Petitioner should be directed to Pay.gov to pay their filing fee.

## Pre-conditions:
*Petitioner has a docket #

## Acceptance Criteria (Post-conditions):
*Petitioner can link to pay.gov 
*Include instructions on how to pay (link on current USTC website)

## Notes
USTC Pay.gov webpage: https://pay.gov/public/search/agencyforms?agencyFilters=United+States+Tax+Court&searchCategory=PAYMENT&searchType=AGENCYPAYMENT&agencyId=1392

## Tasks
- [x] Create instruction content (Kristen)
- [x] Design where instructions and link will be placed (Kristen)
- [x] Implement on the front-end (will)

## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version

**Comment by klohman** [comment]
Ideas on displaying payment options to petitions.

- Display required actions list as accordion. Expanded accordion displays the payment option instructions and link to pay.gov. This is one visual option. 

 ![2.2 Case Detail_Pay Options-1.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b3bf2c47-2d59-473c-b3ae-bedac5bdaaff)

**Comment by klohman** [comment]
Another option for displaying payment info in expanded accordion. ![2.2 Case Detail_Pay Option 2.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e138259e-f66a-4b14-a5c5-92702676f47e)

**Comment by klohman** [comment]
@JessicaMarine Thoughts on this updated design for expanded payment options? 

![2.2 Case Detail_Pay Option-expanded.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/566c7e91-ee1f-4d05-8772-cc356dfe2c69)

**Comment by klohman** [comment]
@dubharmonic Design approved by @JessicaMarine 

functionality- Pay now button will open pay.gov link
Download application - download PDF for payment waiver form - https://www.ustaxcourt.gov/forms/Application_for_Waiver_of_Filing_Fee.pdf

![Case Detail - Pay Options- Final.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3dc96025-266f-4b78-ba61-5653db07738c)

**Comment by sadlerw** [comment]
@klohman if you can attach the actual html/content or whatever in text format for the design to here then we don't have to re-type it all.  Also include things like specific colors and fonts you want (like for the flag.) thanks!

**Comment by sadlerw** [comment]
Also do we have a way of finding out what the X factor is above in the number of days to indicate before vewable online @JessicaMarine ?

**Comment by JessicaMarine** [comment]
I believe that is just a place-holder right now, and the text is actually unnecessary.  If we do a full integration with Pay.gov, it should be instantaneous (I think) and then that text goes away.

**Comment by klohman** [comment]
> @klohman if you can attach the actual html/content or whatever in text format for the design to here then we don't have to re-type it all. Also include things like specific colors and fonts you want (like for the flag.) thanks!

@sadlerw Our new design tool (Figma) should be able to provide most of the info you should need. Try this link: https://www.figma.com/file/DypftctuuMe0xyijjlICnbdx/Sprint-2?node-id=0%3A1

Selecting a design element should pull up the CSS info on the right side panel. If you need more detail, let me know.

**Comment by sadlerw** [comment]
nice!  thank you!

**Comment by JessicaMarine** [comment]
@sadlerw Some initial comments on this story:
1. Pay.gov opens in the same window and you cannot navigate back to case.  Is it possible to make the pay.gov open in a new window?
