### ISSUE TITLE
Court: Remove/hide header, deploy date/time, and implement footer

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#7142]
As the Court, in order to make sure we're ready to go live, we need a few tweaks to the prod URL:

Acceptance Criteria:
* Remove/hide from the Court's production env the top banner that says "This is a testing site for the U.S. Tax Court and not intended for public use. To learn more about starting a case, visit the U.S. Tax Court website."
* Remove/hide from the front end Court's production env the deploy date/time (bottom right). Display in code for reference.
* Implement footer in all environments.

**Comment by klohman** [comment]
### Footer 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a8476ba4-51d7-43be-812c-2f31e3d37e28)

**FAQs link** 
* opens url in new tab:  https://ustaxcourt.gov/dawson.html

**Privacy** 
* routes to Privacy page 

**Contact Us**
* routes to Contact Us page

### Privacy Page 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2ffa5fff-c3c1-4988-b919-8534cc436ee9)

### Contact Us Page
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c9b05f20-5675-4c16-b742-c9e33813ac00)

**Comment by JessicaMarine** [comment]
Jessica reviewed 12.2.2020 -- moved to done
