### ISSUE TITLE
Petitions Clerk Supervisor: Modifying Case Type and Trial Location of a Petition

### ISSUE THREAD

**Issue by tjcurington** [flexion/ef-cms#718]
As a Petitions Clerk Supervisor, I need the ability to modify the case type and trial location of a submitted petition so that it is consistent with the IRS Notice and the US Tax Court can adjudicate the petition properly

**Comment by tjcurington** [comment]
This came out of a 1/24 review meeting with Jessica, Tina, Stephanie, Mariah, and Tony

**Comment by uxforgood** [comment]
@mariahkannenberg  This already exists. Anyone can modify these things - there is no role-specific permissions.
