### ISSUE TITLE
add a loading indicator/spinner whenever we are saving data so that the user doesn’t get confused. 

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#727]

**Comment by uxforgood** [comment]
@ericsorenson doesn't this also already exist? Or maybe it's only in specific places.

**Comment by mariahkannenberg** [comment]
No just saving data, displaying data. Any time the page is thinking. Display when there's a significant lag. 

Display after 2 seconds and something hasn't displayed.
