### ISSUE TITLE
Exact matches: Case Search Usability

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#7355]
As the Court, in order to make sure our users are having a good user experience, we need to make some usability tweaks to the search features.

These AC are based on Kristen's usability testing with 5 participants on 12/14/2020.

**Other exact match stories:** Orders #7369; Opinions #7370; Practitioners #7371

## Pre-Conditions

**Updated AC** 

* Exact matches need to be sorted to top of results
   We define exact matches as exact words in the exact order OR  exact words in any order
* If there are no matches, inform the user
* If user elects to perform a partial match search, display exact matches then partial matches    
* We define partial match as any words in any order 
* Inform users that no advanced syntax is supported in search 
* Strip all special characters in the petitioner name field and replace with space
* No fuzzy search
* All users are informed that sealed cases will not return in a search
* Search does not search contactprimary.secondaryname

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by klohman** [comment]
### 7355 - Display matches for case search 
Updated AC
* Exact matches need to be sorted to top of results
* We define exact matches as exact words in the exact order (first) OR exact words in any order (second) 
    - For example, if Bob Jones is entered 
      - First priority - matches Bob Jones 
     - matches Jones Bob 
     - matches Bob [another word] Jones

* If there are no exact matches, inform the user
* If there are no exact matches, user can perform a partial match search
* We define partial match as any words in any order
       - For example, if Bob Jones is entered 
      - First priority - matches Bob [Something] 
     - matches Jones [Something] 
     - matches Bob [another word] Jones

* Inform users that no advanced syntax is supported in search
* Strip all special characters in the petitioner name field and replace with space
* No fuzzy search 
   - For example: if "Rob Jones" is entered 
     - "Robert Jones" does not match

### NEW - Display matches for order search 
Updated AC
* Exact keyword matches need to be sorted to top of results
* We define exact matches as exact words in the exact order (first) OR exact words in any order (second) 
    - For example, if Bob Jones is entered 
      - First priority - matches Bob Jones 
     - matches Jones Bob 
     - matches Bob [another word] Jones

* If there are no exact matches, inform the user
* If there are no exact matches, user can perform a partial match search
* We define partial match as any words in any order
       - For example, if Bob Jones is entered 
      - First priority - matches Bob [Something] 
     - matches Jones [Something] 
     - matches Bob [another word] Jones

* Inform users that no advanced syntax is supported in search
* Strip all special characters in the keyword field and replace with space
* No fuzzy search 
   - For example: if "Rob Jones" is entered 
     - "Robert Jones" does not match

* If search keyword and petitioner name: 
  * Exact keyword match 

- NEW - Display matches for opinion search 

- NEW - Display matches for practitioner search

**Comment by codyseibert** [comment]
# Test Scenarios

7355 - Display matches for case search

- exact match on contactPrimary.name
 - add a case with the contactPrimary.name of "Bob Jones"
 - add a case with the contactPrimary.name of "Jones Bob"
 - add a case with the contactPrimary.name of "Bob Smith Jones"
 - add a case with the contactPrimary.name of "Bobby Jones"   // won't show up
 - add a case with the contactPrimary.name of "Bob Jonesy"   // won't show up
 - user searches for case by "Bob Jones"
 - expect Bob Jones is first
 - expect Bob Smith Jones is second
 - expect Jones Bob is third
 - expect Bobby Jones to NOT be returned
 - expect Bob Jonesy to NOT be returned

- exact match on contactPrimary.name
 - add a case with the contactPrimary.secondaryName of "Bob Jones"
 - add a case with the contactPrimary.secondaryName of "Jones Bob"
 - add a case with the contactPrimary.secondaryName of "Bob Smith Jones"
 - add a case with the contactPrimary.secondaryName of "Bobby Jones"  // won't show up
 - add a case with the contactPrimary.secondaryName of "Bob Jonesy" // won't show up
 - user searches for case by "Bob Jones"
 - expect Bob Jones is first
 - expect Bob Smith Jones is second
 - expect Jones Bob is third
 - expect Bobby Jones to NOT be returned
 - expect Bob Jonesy to NOT be returned

- exact match on contactPrimary.name
 - add a case with the contactSecondary.name of "Bob Jones"
 - add a case with the contactSecondary.name of "Jones Bob"
 - add a case with the contactSecondary.name of "Bob Smith Jones"
 - add a case with the contactSecondary.name of "Bobby Jones" // won't show up
 - add a case with the contactSecondary.name of "Bob Jonesy" // won't show up
 - user searches for case by "Bob Jones"
 - expect Bob Jones is first
 - expect Bob Smith Jones is second
 - expect Jones Bob is third
 - expect Bobby Jones to NOT be returned
 - expect Bob Jonesy to NOT be returned

- exact match on contactPrimary.name
 - add a case with the contactPrimary.name of "Bob Jones" // 1
 - add a case with the contactPrimary.secondaryName of "Bob Jones" // 2
 - add a case with the contactSecondary.name of "Bob Jones" // 3
 - user searches for case by "Bob Jones"
 - expect 3 results
 - expect order of results to match comments above

**Comment by JessicaMarine** [comment]
@klohman I have reviewed all the new proposed AC and agree with it.  @mariahkannenberg Were we still going to split these up?

**Comment by klohman** [comment]
## Design 

### Public Search screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/671f940e-7de6-4457-b4aa-66e94d50ad93)

* Update header on public search screen 

### Case Search Updates 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1fee34b1-6560-433d-9180-eeb40e84e35c)

* add helper instructions for "Petitioner Name" field 
- "Advanced syntax search (*, “”, - , etc. ) is not supported at this time."

* Add checkbox for "Include partial matches" 

### Exact Match Query w/ matches
if checkbox for "include partial matches" is NOT checked:
* execute only exact match (AND) queries
* Display results (sorted as defined in tests) 
* Display number of matches 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/fa9814b9-2573-47bb-9251-b1706bd8ecfb)

### Exact and partial query w/ matches
if checkbox for "include partial matches" IS checked: 
* execute only exact match (AND) queries and partial match (OR) queries
* Display results (sorted exact matches and then partial matches) 
* Display number of matches

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2d5c2f73-6d87-4702-a9d8-df15720d283b)

### Exact only or exact and partial query w/ no matches
If there are no matches:  
* Display "No Matches Found" 
* Display search tips alert 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/50406815-11b3-4e97-89a3-bc13b2bd02e4)
 

### Exact only or exact and partial query w/ max number of search results 
If there are over the max number of search results: 
* Display 100 results 
* Display max results alert 
* Display "100 matches shown" 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f579906a-32bf-45c7-9f36-8458c10b5c9e)

**Comment by klohman** [comment]
## Updated language for case search instructions

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7390bd56-8d00-4965-b87b-11b7a77bb8b5)

**Comment by JessicaMarine** [comment]
PO Review:
1) When I perform an Advanced Search when logged in as an IRS Practitioner.  I get the error message that says "More than 100" but the matches shown count is 200: https://files.slack.com/files-pri/TD3DSU09Y-F01H0NVLH9V/image.png
2) Need to remove "or excluding partial matches" from the error messages when more than 100 results.
