### ISSUE TITLE
Order Search: Exact matches (REPLACE with 8546)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#7369]
As a user (internal or external), so that I find the order I'm looking for, I need exact matches to display at the top of the search results.

These AC are based on Kristen's usability testing with 5 participants on 12/14/2020.

## Acceptance Criteria
* User (internal or external) should see an indication that my search request is “processing” after starting a search
* Ensure that links on search results don't expire
* Exact keyword matches need to be sorted to top of results 
* We define exact matches as exact words in the exact order
    * For example, if innocent spouse is entered --First priority - matches innocent spouse

* If search keyword and petitioner name, matches need to be sorted as:
    * Keyword exact match (exact words in exact order) + petitioner name [exact words in exact order]
    * Keyword exact match (exact words in any order) + petitioner name [exact words in exact order]
    * Keyword exact match (exact words in exact order) + petitioner name [exact words in any order]
    * Keyword exact match (exact words in any order) + petitioner name [exact words in any order]

* If search keyword and petitioner name, show no results
    * Keyword exact match (exact words in exact order) + petitioner name [no exact match]
    * Keyword exact match (exact words in any order) + petitioner name [no exact match]

* If search keyword and docket number / judge / start-end date combo, matches sorted as: 
    * Keyword exact match (exact words in exact order) + docket number/judge/start-end date [exact match]
    * Keyword exact match (exact words in any order) + docket number/judge/start-end date [exact match]

* If there are no matches, inform the user

* Inform users that no advanced syntax is supported in search 
* Strip all special characters in the keyword field and replace with space 
* No fuzzy search
    * For example: if "Rob Jones" is entered
        * "Robert Jones" does not match

* Consider whether to reject searches that have special characters. Perhaps we can use Joi to validate what is a valid search query.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
Consider:  https://www.elastic.co/guide/en/elasticsearch/guide/current/_finding_exact_values.html

## Tasks
 - [ ] Write integration tests for test scenarios (Jojo, Matt, Mrin, Rae, Rachael)
 - [ ] Adjust search query as needed

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by klohman** [comment]
## Design 

### Order Search Updates 
* add helper instructions for keyword field 
- "Advanced syntax search (*, “”, - , etc. ) is not supported at this time."

* Add checkbox for "Include partial matches" 

### Exact Match Query w/ matches
if checkbox for "include partial matches" is NOT checked:
* execute only exact match (AND) queries
* Display results (sorted as defined in tests) 
* Display number of matches 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3353af1b-418e-41fb-a8d7-79ce78edfc82)

### Exact and partial query w/ matches
if checkbox for "include partial matches" IS checked: 
* execute only exact match (AND) queries and partial match (OR) queries
* Display results (sorted exact matches and then partial matches) 
* Display number of matches
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4e2fd0f9-1284-45b7-bc8b-6cba5204151d)

### Exact only or exact and partial query w/ no matches
If there are no matches:  
* Display "No Matches Found" 
* Display search tips alert 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4b7014cc-49da-4fac-a38f-9566754444d8)
### Exact only or exact and partial query w/ max number of search results 
If there are over the max number of search results: 
* Display 100 results 
* Display max results alert 
* Display "100 matches shown" 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f02c365b-29a1-4f6b-b7fd-722ebd6981b5)

**Comment by mrinsin** [comment]
# Test Scenarios

7369 - Display matches for order search

- exact keyword match on document title - eg with keyword "Sunglasses"
  - Create an order whose title contains the word "Sunglasses" and document contents "pigeon"
  - Create an order whose title contains the word "Sunglassesy"
  - searching for keyword "sun" returns no results
  - searching for keyword "pigeon" returns no results
  - searching for keyword "Sunglasses" returns the first order but not the second
  - searching for keyword  "Sunglassesy" returns the second order but not the first
  - searching for keyword "Sunglasses!^&*" returns the first order but not the second
  - searching for keyword "Sunglassesy!^&*" returns the second order but not the first


- exact match on contactPrimary.name
  - add a case with the contactPrimary.name of "Bob Jones"
  - add a case with the contactPrimary.name of "Jones Bob"
  - add a case with the contactPrimary.name of "Bob Smith Jones"
  - add a case with the contactPrimary.name of "Bobby Jones"   // won't show up
  - add a case with the contactPrimary.name of "Bob Jonesy"   // won't show up
  - user searches for case by "Bob Jones"
  - expect Bob Jones is first
  - expect Bob Smith Jones is second
  - expect Jones Bob is third
  - expect Bobby Jones to NOT be returned
  - expect Bob Jonesy to NOT be returned

- exact match on contactPrimary.secondaryName
  - add a case with the contactPrimary.secondaryName of "Bob Jones"
  - add a case with the contactPrimary.secondaryName of "Jones Bob"
  - add a case with the contactPrimary.secondaryName of "Bob Smith Jones"
  - add a case with the contactPrimary.secondaryName of "Bobby Jones"  // won't show up
  - add a case with the contactPrimary.secondaryName of "Bob Jonesy" // won't show up
  - user searches for case by "Bob Jones"
  - expect Bob Jones is first
  - expect Bob Smith Jones is second
  - expect Jones Bob is third
  - expect Bobby Jones to NOT be returned
  - expect Bob Jonesy to NOT be returned

- exact match on contactSecondary.name
  - add a case with the contactSecondary.name of "Bob Jones"
  - add a case with the contactSecondary.name of "Jones Bob"
  - add a case with the contactSecondary.name of "Bob Smith Jones"
  - add a case with the contactSecondary.name of "Bobby Jones" // won't show up
  - add a case with the contactSecondary.name of "Bob Jonesy" // won't show up
  - user searches for case by "Bob Jones"
  - expect Bob Jones is first
  - expect Bob Smith Jones is second
  - expect Jones Bob is third
  - expect Bobby Jones to NOT be returned
  - expect Bob Jonesy to NOT be returned

- exact match on caseCaption
  - add a case with the caseCaption of "Bob Jones"
  - add a case with the caseCaption of "Jones Bob"
  - add a case with the caseCaption of "Bob Smith Jones"
  - add a case with the caseCaption of "Bobby Jones" // won't show up
  - add a case with the caseCaption of "Bob Jonesy" // won't show up
  - user searches for case by "Bob Jones"
  - expect Bob Jones is first
  - expect Bob Smith Jones is second
  - expect Jones Bob is third
  - expect Bobby Jones to NOT be returned
  - expect Bob Jonesy to NOT be returned

- exact match on contactPrimary.name, contactPrimary.secondaryName, contactSecondary.name, 
  - add a case with the contactPrimary.name of "Bob Jones" // 1
  - add a case with the contactPrimary.secondaryName of "Bob Jones" // 2
  - add a case with the contactSecondary.name of "Bob Jones" // 3
  - add a case with the caseCaption of "Bob Jones" // 4
  - add a case with the contactPrimary.name of "Jones Bob" // 5
  - user searches for case by "Bob Jones"
  - expect 5 results
  - expect order of results to match comments above, where "exact phrase" matches are ranked higher than entries which contain all terms out of order
 
- do a search that results in 0 records
  - user searches for case by "Unknown Petitioner Name"
  - expect 0 results
  - expect some type of alert to have a link where user can click to view more non-exact matches

- Partial match on contactPrimary.nem
  - add a case with contactPrimary.name of "Bob Evans" // 1
  - add a case with contactPrimary.name of "Jones Evans" // 2
  - add a case with contactPrimary.name of "Bob Trisha Evans" // 3
  - add a case with contactPrimary.name of "Bobby Evans" // do not expect them to be returned
  - user searches for "Bob Jones"
  - expect 3 results
  - expect order to match comments above

- Partial match on contactPrimary.secondaryName
  - add a case with contactPrimary.secondaryName of "Bob Evans" // 1
  - add a case with contactPrimary.secondaryName of "Jones Evans" // 2
  - add a case with contactPrimary.secondaryName of "Bob Trisha Evans" // 3
  - add a case with contactPrimary.secondaryName of "Bobby Evans" // do not expect them to be returned
  - user searches for "Bob Jones"
  - expect 3 results
  - expect order to match comments above

- Partial match contactSecondary.name
  - add a case with contactSecondary.name of "Bob Evans" // 1
  - add a case with contactSecondary.name of "Jones Evans" // 2
  - add a case with contactSecondary.name of "Bob Trisha Evans" // 3
  - add a case with contactSecondary.name of "Bobby Evans" // do not expect them to be returned
  - user searches for "Bob Jones"
  - expect 3 results
  - expect order to match comments above

- Partial match on caseCaption
  - add a case with caseCaption of "Bob Evans" // 1
  - add a case with caseCaption of "Jones Evans" // 2
  - add a case with caseCaption of "Bob Trisha Evans" // 3
  - add a case with caseCaption of "Bobby Evans" // do not expect them to be returned
  - user searches for "Bob Jones"
  - expect 3 results
  - expect order to match comments above

**Comment by rachaelparris** [comment]
Work has been started for this story on branch `7369-order-search-with-petitioner-name`

**Comment by kkoskelin** [comment]
For exact matches:  https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query-phrase.html

**Comment by JessicaMarine** [comment]
Replaced by #8546
