### ISSUE TITLE
BUG: Error received when serving document with extremely long title 

### ISSUE THREAD

**Issue by klohman** [flexion/ef-cms#7533]
**Describe the Bug**
When entering a docket entry for a document (court-issued or paper-filed) with an extremely long title and serving, system throws 400 error. 

When e-filing a document as a party with document title over max character count, the app throws error on submit. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
verifying support ticket 

**To Reproduce**
**Court-issued**
1. Go to case 
2. Create Order 
3. Add docket entry 
4. Enter description - enter a lot of text> 3000 characters 
5. Save and serve 

**paper-filed**
1. Go to case 
2. Add Paper filing  
3. Select Response 
4. Enter description - enter a lot of text> 3000 characters 
5. Save and serve 

**e-filed**
1. login as petitioner 
2. go to case 
3. Select "Statement" as doc type 
4. Enter description - enter a lot of text> 3000 characters 
5. Complete form and click Submit your filing 

**Expected Behavior**
If title or fields making up the title are longer than allowed, user should be advised of what the issue is.  Better error messaging. 

**Actual Behavior**
App routes to 400 error page ( for court-issued and paper filed docs) 
App throws upload error when e-filing document. 

Notes:
*Possibly break this into multiple issues if it gets really big. 

**Screenshots**
https://drive.google.com/file/d/1ob1fgbINrPQTm5ABYyDzpXLl8znB3BEW/view?usp=sharing
![Screen Shot 2021-01-11 at 8.38.02 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/755abce2-75fc-4665-a91e-434bed70cdad)

![Screen Shot 2021-01-13 at 12.23.32 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f4722070-f072-4c89-9c40-e6ed18a5940a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
Current character limit for doc title - DOCUMENT_TITLE: STRING.max(3000)

If this is related to the issue, we can re-evaluate and possibly reduce this limit (discuss with Jessica if applicable)

**Comment by klohman** [comment]
- Document title < 3000 characters 
Court-issued
    - petitionerNames
    - freeText  < 500
    - judge ~ 26
    - docketNumbers < 500
    - Date ~ 24 
    - Trial location <100
External docs
    - previousDocument.documentTitle (assume <3000)
    - freeText < 500
    - documentTitle (assume <3000)
    - serviceDate ~ 24 
    - trialLocation <100
    - ordinalValue - 6 
    - documentType (longest is 123 characters) 
    - secondaryDocument
    - freeText2 < 500

- Additional info 1 < 500 characters 
- Additional info 2 < 500 characters

**Comment by klohman** [comment]
**Here are draft test cases for this issue,]If we want to go in the direction of handling limits and validation at the field level first. If this is the end solution, i will write more**

## Draft tests

#### 1) Docket clerk enters 500 characters into free text field court-issued document and serves
* Login as docket clerk 
* Go to case 
* Create, sign and save Order 
* Add Docket entry 
* Select “O” as doc type 
* Enter 500 characters in “What is this order for?” field 
* Save and serve 
Expected results 
- [ ] Order docket entry is added to docket record with complete document title displayed 
- [ ] Order is served on parties 


#### 2) Docket clerk enters 501 characters into free text field court-issued document and serves
* Login as docket clerk 
* Go to case 
* Create, sign and save Order 
* Add Docket entry 
* Select “O” as doc type 
* Enter 501 characters in “What is this order for?” field 
* Save and serve 
Expected results 
- [ ] App displays page error message: Limit is 500 characters. Enter 500 or fewer characters. 


#### 3) Docket clerk enters 500 characters into docketNumbers field for paper-filed document and serves
* Login as docket clerk 
* Go to case 
* Add paper Filing
* Select “M067” as doc type 
* Enter 500 characters in Docket Numbers field
* Save and serve 
Expected results 
- [ ] Motion docket entry is added to docket record with complete document title displayed 
- [ ] Motion is served on parties 


#### 4) Docket clerk enters 501 characters into docketNumbers field for paper filed document and serves
* Login as docket clerk 
* Go to case 
* Add paper Filing
* Select “M067” as doc type 
* Enter 501 characters in Docket Numbers field
* Save and serve 
Expected results 
- [ ] App displays page error message: Limit is 500 characters. Enter 500 or fewer characters. 


#### 5) Docket clerk enters 500 characters into freeText field for paper-filed document and serves
* Login as docket clerk 
* Go to case 
* Add paper Filing
* Select “APPL” as doc type 
* Enter 500 characters in freeText field
* Save and serve 
Expected results 
- [ ] docket entry is added to docket record with complete document title displayed 
- [ ] document is served on parties 


#### 6) Docket clerk enters 501 characters into freeText field for paper filed document and serves
* Login as docket clerk 
* Go to case 
* Add paper Filing
* Select “APPL” as doc type 
* Enter 501 characters in Docket Numbers field
* Save and serve 
Expected results 
- [ ] App displays page error message: Limit is 500 characters. Enter 500 or fewer characters.

**Comment by klohman** [comment]
* increase freeText fields to 1000 characters and show error message when reached 
* any field that has a character limit , display error message when reached 
* if document title max limit is reached, show global error message - page level only

**Comment by rachaelparris** [comment]
Scenarios to verify:
* Create order modal

**Comment by JessicaMarine** [comment]
@klohman @mrinsin @rachaelparris We can mob to test this on Monday!  Have a great weekend.
