### ISSUE TITLE
Registration: Exploration and research Cognito registration and login [SPIKE]

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#775]
As a development team, so that we can determine which approach to take with Cognito integration, we need to perform research and exploration. 

Goal of the story: Conduct minimum amount of exploration and research to determine whether or not we'll use Cognito page for login or API approach 

## Acceptance Criteria
* Team knows what approach we're going to take with Cognito integration (registration and login)
* Parameters of registration and login stories are clear and everyone is in agreement about the parameters

## Tasks
- [x] Review Cognito interfaces (team)
- [x] Try to make Cognito page look like desired registration and login page from CSS perspective

**Comment by ericsorenson** [comment]
CSS settings and results:

![image.png](https://images.zenhubusercontent.com/583eff35b9dc3c622022bdff/d4f3ab3e-cffc-4f81-90de-c0d9777b988e)

![image-1.png](https://images.zenhubusercontent.com/583eff35b9dc3c622022bdff/b85c23b4-47af-4b63-b68f-28f957b314c3)

**Comment by uxforgood** [comment]
## Observations/limitations

Technical
- Can't change specific settings afters in production (unclear which ones are locked down thus far)
- Very limited control over UI

UI/UX
- Username vs email (which we may be able to modify, just have to create a new instance)
- Looks like a modal, doesn't work like one - no way "back" on the screen, lacks way finding
- Can't change background color
- Can't change spacing (looks very crowded/confusing placement of labels) 
- No official eyebrow/header
- No ability to message for practitioners on create account page (or have messaging at all)
- Can't remove "create an account" if we're using this for internal users (don't want them signing up that way)

**Comment by tjcurington** [comment]
2/11 - Team will move forward with just the email address as login and consider additional data later
Going with Cognito "OOTB" for this story. Team will consider the "two-door" path of API and Cognito directly later. Not for this story.
