### ISSUE TITLE
Create an AWS diagram

### ISSUE THREAD

**Issue by waldoj** [flexion/ef-cms#785]
As a part of documentation for the EF-CMS, we need to show people the AWS infrastructure. (At present, they would need to read through the Terraform config files to know what services are in use and how they interact.) Add a high-level diagram showing the basic services and how they are connected — there is no need to e.g. label individual AMIs, instance IDs, etc. This will need to be modified whenever the AWS infrastructure is modified, which has not happened often.

**Comment by mariahkannenberg** [comment]
There's a script that can auto-generate this for us.

**Comment by waldoj** [comment]
I'd be happy to QA this, but I'd need somebody to tell me how. :) Where would I look for this?

**Comment by ericsorenson** [comment]
@waldoj it's in the readme 🙂

**Comment by waldoj** [comment]
Looks good — this is just what I had in mind. Thanks!
