### ISSUE TITLE
Court: Improve PR process, which is impeding the flow of code to the court

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#8063]
As the Court in order to deploy finished code on the Court's schedule, we need to not be impeded by the current PR process.

## Pre-Conditions
* There is finished code.

## Acceptance Criteria
- Find a way that makes PR review easier for Mike without reducing code quality
- Court needs ability to deploy a specific “chunk” of finished code, while other work is in progress
- The “chunk” needs to be flexible, meaning that the court needs the ability to change what’s in that chunk while work is in progress
- Define an experiment for improvement
- Inspect the experiment 

Notes:

- Review last 5 PRs from the Court to determine if there’s a pattern of things we’re not doing a good job at the prevent him from getting to the PR in the first place (tools?)
- We need to determine where the code deployed to in the Court’s environments
- Where QA is happening
- Is there a different path for bugs vs feature work?
- Court doesn't want to have 3 production like environments - too expensive.
 - The DOD is updated with checkboxes to reflect the new flow - including checkboxes for Mike
- 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion mig env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by matthopson** [comment]
I just want to raise a note about how things are tested in this workflow. Ideally code for bug fixes would stay separate from story work - which means keeping an environment in sync with the court's, OR working from the court's env. Just something we need to consider, as I think the safest and cleanest way to approach this is to effectively base of the environment that is MOST up to date with court's production - whether that's the testing env or a clone on Flexion's side.

**Comment by sutt0n** [comment]
<img width="914" alt="image" src="https://user-images.githubusercontent.com/1116426/112529130-ef915780-8d72-11eb-9a4f-1f97083b0abc.png">


## Flow Description
- [Flexion] Feature branches are created from `court/staging`, and merged into `court/migration`.
  - [Flexion] UX Reviews done on any Flexion environment, merged into `court/migration` after UX Review passes, and then into `court/staging` after PO approval.
- [Flexion] Hotfixes / bugs are created from `court/staging`, and merged into `court/test`. [Court] After PO approval, they're merged into `court/staging`.
  - [Flexion] UX Reviews only as needed on the `court/test` environment
- Features are QA'd in the `court/migration` environment (`migration`).
- Hotfixes / bugs are QA'd in the `court/test` environment (`test`).

**Comment by matthopson** [comment]
## Story Workflow
Step | Branch / Env. | Board / Column | Labels | Note
-- | -- | -- | -- | --
Assign issue to point person |   |   |   |  
Create feature branch from Court's Staging | Court’s Staging -> Feature Branch | In Progress | + `Engineering` | You may also work off an existing feature branch if stories are intended to be coupled.
Create small PRs into feature branch | Bug Branch / Any Flexion env (dev, exp1, exp2, exp3) |   | + `Needs Migration` (as needed)<br />+ `Needs ES Reindex` (as needed) | Use Flexion envs to test if necessary. Flexion code review takes place in these PRs
Pair review with UX locally | Bug Branch / Any Flexion env (dev, exp1, exp2, exp3) |   |   | Use Flexion envs to test if necessary.
  |   |   |   | Separates Flexion / Court Envs
Merge feature branch into Court’s Migration | Court’s Migration | QA | - `Engineering`<br />+ `Needs PO Review `| Do NOT delete branch
PO Reviews on Court’s Migration | Court’s Migration |   |   | Address issues on feature branch, re-merge into Court’s Migration
Flexion makes PR from feature into Court’s Staging | Court's Staging |   | - `Needs PO Review`<br />+ `Code Review Needed` |  
Court Tech Lead merges to staging | Court’s Staging |   |   | Safe to delete feature branch
Court’s Tech Lead moves to done |   | Done | - `Code Review Needed` |  


## Bug Workflow
Step | Branch / Env. | Board / Column | Labels | Note
-- | -- | -- | -- | --
Assign issue to point person |   |   |   |  
Create bug branch from Court’s Staging | Court’s Staging -> New Branch | In Progress | + `Engineering` |  
Commit changes to bug branch. | Bug Branch / Any Flexion env (dev, exp1, exp2, exp3) |   |   | Use Flexion envs to test if necessary.
  |   |   |   | Separates Flexion / Court Envs
Flexion makes PR from bug branch into Court’s Test environment | Court’s Test | QA | - `Engineering`<br />+ `Code Review Needed` |  
Request review from Flexion engineers |   |   |   | PR can be merged with review from both Court’s Tech Lead and at least ONE Flexion engineer
Court’s Tech Lead merges to Court’s Test | Court’s Test |   | - `Code Review Needed`<br />+ `Needs PO Review` | Do NOT delete branch
PO Reviews on Court’s Test | Court’s Test |   |   | Issues found during review can be fixed on the bug branch with a new PR to
PO moves to done |   | Done | - `Needs PO Review` |  
Court Tech Lead merges to staging | Court’s Staging |   |   | Safe to delete bug branch

**Comment by mariahkannenberg** [comment]
# User Stories
- A defined unit of new work focused on the needs of the user.
- Not defined in technical or design terms.
- Can be achieved with paper and pencil if necessary. (Technology-agnostic terminology)
- Development is complete when all of the user's needs (acceptance criteria) have been met at production quality AND the steps taken to fulfill the user's needs have been demonstrated.

#### What is a user? 
Any person who uses the system to achieve their business or personal needs.

#### What does production quality mean?
All of the items in the DOD have been completed.

# Bugs
- 	A defined unit of work focused on the needs of the user.
- 	Not defined in technical or design terms.
- 	Acceptance criteria from a previously completed user story is unintentionally no longer being met.

# Refactoring
- A defined until of work that has no impact to the user.
- Doesn't give obvious business value to the user.
- The purpose is to make the system easier for engineers to maintain and expand.
- When completed, refactoring reduces the friction engineers experience during development.

**Comment by JessicaMarine** [comment]
## STORY CHECKLIST ##
[ ] Flexion Engineer: Assign issue to point person	 	 	 	
[ ] Flexion Engineer: Create feature branch from Court's Staging	
[ ] Flexion Engineer: Create small PRs into feature branch [Note: PRs should be reviewed by another Flexion engineer]	
[ ] Flexion Engineer & UX: UX Review (locally or on Flexion dev, exp1, exp2, exp3)	
[ ] Flexion Engineer: Merge feature branch into Court’s Migration	
[ ] Court PO: Review on Court's Migration
[ ] Flexion Engineer: Make PR to Court's Staging
[ ] Court Tech Lead: Code Review
[ ] Court Tech Lead: Merge to Staging
[ ] Flexion Engineer: Delete Feature Branch

## BUG CHECKLIST ##
[ ] Flexion Engineer: Assign issue to point person	 	 	 	
[ ] Flexion Engineer: Create bug branch from Court's Staging	
[ ] Flexion Engineer: Create small PRs into bug branch (if needed)	
[ ] Flexion Engineer: Make PR from bug branch to Court's test	
[ ] Flexion Engineer #2: Review PR
[ ] Court Tech lead: Review PR
[ ] Court Tech Lead: Merge PR to Court's test
[ ] Court PO: Review on Court's test
[ ] Court Tech Lead: Merge to Staging
[ ] Flexion Engineer: Delete Feature Branch

**Comment by mariahkannenberg** [comment]
Revisit DOD on Wed during grooming. Do we want the checklist that Jessica suggested above?

**Comment by mariahkannenberg** [comment]
All that's left on this one it to do the inspection. However, want to wait until some stories have been completed and gone through the flow before we inspect.
