### ISSUE TITLE
Court: Public Terminal with Access to All Unsealed Documents/Cases

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#8955]
As the Court, in order to satisfy the requirements of Rule 27(b)(2), we need to provide a public terminal at the Courthouse in Washington, DC that provides a public user access to all unsealed cases and all unsealed documents within an unsealed case.

Rule 27(b) provides:
(b) Limitations on Remote Access to Electronic Files: Except as otherwise directed by the Court, access to an electronic file is authorized as follows: 
  (1) The parties and their counsel may have remote electronic access to any part of the case file maintained by the Court in electronic form; and 
  **(2) any other person may have electronic access at the courthouse to the public record maintained by the Court in electronic form,** but may have remote electronic access only to: 
    (A) The docket record maintained by the Court; and 
    (B) any opinion, order, or decision of the Court, but not any other part of the case file.

We need to create a new user role intended to be logged in only from the physical device on premise at the Court's location, that can access all unsealed cases and unsealed documents within an unsealed case, in addition to being able to utilize case, Order, and Opinion search.

## Acceptance Criteria
* Public terminal user may access a computer (IP specific) at the Courthouse in Washington to view:
   * All unsealed cases
   * All unsealed documents in an unsealed case
* No user may access this view outside of the US Tax Courthouse in Washington, DC
* Besides the additional docket entries being hyperlinked to the documents, the public terminal user should otherwise have the public view of the case :
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/001edc0d-b023-4c0c-af2f-3381e92000b5)
* Terminal User can view search functionality and results within the confines of the existing public view
* Terminal User can view Docket Record view as seen in screenshot
* All unsealed documents in Docket Record view are clickable hyperlinks that open the clicked document in a new tab
* Documents opened can only be viewed; there is no other functionality available
* Terminal User cannot navigate elsewhere in the DAWSON application
* Terminal User cannot be logged in from anywhere other than the physical device at the Court's location
* Special Testing: As this user should be functionally locked to the on-premise court device providing access, we will need to either spoof the arranged IP address for testing or devise another method of testing this prior to live deployment.

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Questions
* How do we maintain login for this user from this location? Strong password - user w/own role - Cognito acct stores in PW manager. Like any other user.
* Should the terminal user have access to Order/Opinion search prior to general public/external user access? No.
* Are users given a login/PW? No, they're kept in PW manager. 
* What's the purpose of the login? There aren't AC for login. 
* Does it require the intervention of a court employee? No. 
* Is it a problem is someone snaps a photo of a kiosk screen. no.
* Is it browser based? Yes.
* Would we be removing print buttons? Yes, from docket record. 
* Anything else we need to disable? UI controls inside the app that don't meet AC
* Who will be responsible for deploying correctly? Folks at Court.
* What will device be? PC running edge at court. 
* Where will security be handled (outside of user role/permission)? By the court. No need to worry about security of machine and browser. 

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by cholly75** [comment]
@JessicaMarine - added a few specifics to AC, please review.

**Comment by cholly75** [comment]
Test Cases (quick):

1) Terminal User logs in, is presented with appropriate landing page
2) Terminal User can access Case Search
3) Terminal User can access Order Search (if externally available)
4) Terminal User can access Opinion Search (if externally available)
5) Terminal User cannot access Order Search (if not externally available)
6) Terminal User cannot access Opinion Search (if not externally available)
7) Terminal User searches for unsealed Case, is presented with results, can click link to Docket Record
8) Terminal User searches for sealed Case, does case does not return in results
9) Docket Record view displays all unsealed elements of Docket Record as clickable links
10) Sealed elements of Docket Record are not hyperlinked
11) Links on Docket Record view open appropriate document in new tab
12) Terminal User cannot navigate elsewhere in the application other than the Search UI, Docket Record, and Document tabs.

**Comment by klohman** [comment]
Design TBD. Will need to pair with engineering on technical solution.
