### ISSUE TITLE
Docket Clerk: Unseal an individual document

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#9206]
As a docket clerk, so that I can appropriately represent the sealed state of a particular document, I need to be able to unseal individual docket entries.

#5384 -- back-end work to allow the sealed flag at the document level

## Pre-Conditions
#4252
#9147

## Acceptance Criteria
* Docket clerk has the ability to unseal one or more individual sealed documents on a case
* Docket clerk can select a document to be unsealed, and must explicitly confirm they wish to unseal the selected document
* Unsealing a document makes that document visible to all users following normal visibility rules
* Docket record reflects unsealed status of document once the document is unsealed
* Unsealing a document does not change the sealed status of the Case
* Unsealing an Order makes that Order eligible to be returned as a search result in Order Search, following normal visibility rules
* Unsealing process is the same regardless of whether a document was initially sealed to "all" or "public" users
* Unsealing process is the same between legacy and new sealed documents.
* Both legacy and "new" sealed documents can be unsealed.

## Notes

* Is there any modification that needs to be made to existing data to enable this functionality? - _Not expected_

### Remaining tasks
- [x] Confirm that sealing and unsealing permissions are the same 
- [x] Replace red lock symbol with similar red unlock symbol as used in the Case Details section (?)
- [x] Confirm unchecked test scenarios
- [ ] Fix unseal button overflow on docket entry with edit button

## Test Cases
* Docket clerk navigates to Sealed case with one sealed document. Clerk unseals document; case remains sealed, unviewable to public; UI on Docket record updated to reflect unsealed status of document
* Docket clerk navigates to Sealed case with multiple sealed documents. Clerk unseals some of the sealed documents; case remains sealed, unviewable to public; UI on Docket record updated to reflect unsealed status of documents; documents not selected to be unsealed remain sealed
* Docket clerk navigates to Sealed case with multiple sealed documents. Clerk unseals all of the sealed documents; case remains sealed, unviewable to public; UI on Docket record updated to reflect unsealed status of documents
* Docket clerk navigates to unsealed case with one sealed document. Clerk unseals document; case remains unsealed, viewable to public; UI on Docket record updated to reflect unsealed status of document
* Docket clerk navigates to unsealed case with multiple sealed documents. Clerk unseals some of the sealed documents; case remains unsealed, viewable to public; UI on Docket record updated to reflect unsealed status of documents; documents not selected to be unsealed remain sealed
* Docket clerk navigates to unsealed case with multiple sealed documents. Clerk unseals all sealed documents; case remains unsealed, viewable to public; UI on Docket record updated to reflect unsealed status of documents
* Docket clerk selects any number of docket entries on a case to be unsealed, cancels out of explicit confirmation of unsealing. Documents remain sealed.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [x] Deployed to the Court's migration environment

**Comment by swongCO** [comment]
**See #4252 for sealing a document**
 
![USTC Docket Record Unseal modal.jpg](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/cf212036-83ff-4b68-81b2-d9aa49fd04bc)

- When the Unseal link is clicked, display modal
- When the user unseals a document, the lock icon in the status column disappears and the Unseal link changes to the Seal link

**Comment by ttlenard** [comment]
@TomElliottFlexion, @codyseibert 

I'm running into errors on Test Case #3.  When attempting to unseal a legacy sealed document, I get a 400 error.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/cc8151d8-f972-4e95-a0e3-6b2e057ae5d6)

This isn't happening when I seal, and then unseal a document on a case. Seems to only happen with the legacy sealed documents.
