### ISSUE TITLE
Court: Implement Alternative to MS-Edge PDF Renderer

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#9233]
As a DAWSON user, so that I can interact with PDF files in a safe way, I need an alternative to the Microsoft Edge PDF viewer.

The latest version of the Microsoft Edge PDF viewer introduces additional text editing and formatting capabilities. Unfortunately interacting with these causes inconsistent and incorrect behavior in DAWSON w/r/t viewing PDF files, for which there is currently no known workaround. 

To prevent this from happening in the future, we would like an alternative solution for rendering and interacting with PDF files in the DAWSON application.

This story attempts to address the issue documented in #9097 and use the framework developed in #9119

## Acceptance Criteria
* PDF interactions in DAWSON remain functionally similar to the current state (at minimum, print and save capabilities remain)
* The Microsoft Edge PDF Viewer no longer is visible or usable in the DAWSON UI
* Navigational elements present on current UI remain in place (The links that appear contextually in the rendering frame)
* Implementation of solution is coded behind a feature flag, allowing viewer switching between current version and alternate solution

## Notes
* Comprehensive solution will require a large amount of regression testing in Court environments and Court laptops.
* Is there a way to refactor the feature flag/framework to make it even more flexible (i.e., supply browser-specific strings for components should we want to introduce those in the future)?
## Test Cases
* User creates a new case, uploads petition; petition uploaded and rendered correctly, MS toolbar is not visible. User can save uploaded petition and print uploaded petition
* User creates a new case, scans in petition, creates PDF; PDF created and rendered correctly, MS toolbar is not visible. User can save and print petition. (Repeat for other documentation in Create Case workflow)
* User calendars trial session, is presented with documentation to be printed for paper service petitioners; PDFs created and rendered correctly, MS toolbar is not visible. User can save and print all documents.
* User views a Docket record in the Document view and selects a document; PDF is rendered correctly, MS toolbar is not visible. User can save and print document.
* User creates new Order or Notice and views it in the Drafts view of the Docket record; Order is rendered correctly, MS toolbar is not visible. User can save and print document.
* User creates new Paper Filing for Docket; uploads or scans in document; document is rendered correctly, MS toolbar is not visible. User can save and print document.
* User creates new PDF Upload for Docket; uploads document; document is rendered correctly, MS toolbar is not visible. User can save and print document.
* User prints document on paper; document is clear and legible with proper formatting

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
**1. User creates a new case, uploads petition; petition uploaded and rendered correctly, MS toolbar is not visible. User can save uploaded petition and print uploaded petition**


**2. User creates a new case, scans in petition, creates PDF; PDF created and rendered correctly, MS toolbar is not visible. User can save and print petition. (Repeat for other documentation in Create Case workflow)**


**3. User calendars trial session, is presented with documentation to be printed for paper service petitioners; PDFs created and rendered correctly, MS toolbar is not visible. User can save and print all documents.**


**4. User views a Docket record in the Document view and selects a document; PDF is rendered correctly, MS toolbar is not visible. User can save and print document.**


**5. User creates new Order or Notice and views it in the Drafts view of the Docket record; Order is rendered correctly, MS toolbar is not visible. User can save and print document.**


**6. User creates new Paper Filing for Docket; uploads or scans in document; document is rendered correctly, MS toolbar is not visible. User can save and print document.**


**7. User creates new PDF Upload for Docket; uploads document; document is rendered correctly, MS toolbar is not visible. User can save and print document.**


**8. User prints document on paper; document is clear and legible with proper formatting**
