### ISSUE TITLE
Send out Clinic Letters w/ Notice Setting Case for Trial

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#9356]
As a petitions clerk, so that I can send pro se petitioners needed tax clinic documentation prior to their trial, I need to be able to send these letters with the Notice Setting Case for Trial.

For pro se petitioners who may not be able to afford or locate counsel to guide them through their case, there are tax clinics available as a resource who often advise and/or represent lower income petitioners. These clinics provide the Court with letters for petitioners indicating the details on how to use these resources, and as part of the Court's commitment to taxpayer equity prior to DAWSON we sent these letters to pro se petitioners along with official Court notices at various points in the life of the case.

These letters are not official Court or IRS documentation, but we provide them as a courtesy. There are one or more letters for each place of trial where the Court conducts business.

We would like to re-establish the process of generating and sending out these letters at the same time we send the Notice Setting Case for Trial by appending them to said Notices at the time the Notices are generated.

The letters themselves are provided in toto by the clinics to the Court; no customization is needed to the letter text itself, and these are not docketed separately as entries on the official record.

## Pre-Conditions
#9429
#9430
#9355

## Acceptance Criteria
* When a Notice Setting Case for Trial is generated for any case where the Petitioner is unrepresented by counsel, the appropriate clinic letter is appended to the Notice after the final page of the Notice.
* The specific letter appended to the Notice Setting Case for Trial is determined by Location data on the session and the Case Procedure on the case. If there are multiple letters available for a particular location, the specific letter appended is determined by the Case Procedure data on the case.
* If any NTD was generated with a clinic letter appended for a case, the appended clinic letter displays along with the Notice in its entirety when viewed in DAWSON from docket record 
* When a clinic letter is replaced with a new version, all Notices Setting Case For Trial generated after that use the new version of that letter
* When multiple petitioners are attached to a case:
- If only one Notice Setting Case for Trial is generated, if any of the petitioners are represented by counsel, do not append the clinic letter to the Notice.
- If multiple Notices Setting Case for Trial are generated for the case, evaluate each petitioner individually and attach the clinic letter to each Notice where the petitioner is not represented by counsel.

## Test Cases
* Pro se petition is calendared for trial session with a Trial Location that has only one clinic letter available; notice setting case for trial is generated; notice document has appropriate clinic letter appended as final pages of document
* Pro se petition is calendared for a trial session with a Trial Location that has multiple clinic letters available; notice setting case for trial is generated; notice document has appropriate clinic letter appended as final pages of document
* Represented petition is calendared for a trial session with a Trial Location that has one or more clinic letters available; notice setting case for trial is generated; notice document has no clinic letter appended
* Clinic letter for location is updated in repository; new pro se petition is calendared for trial; notice setting case for trial is generated with appropriate clinic letter appended as final pages of document
* Notice Setting Case for Trial is generated w/ clinic letter appended; Notice is viewed from Docket Record; Notice displays in its entirety along with clinic letter; no separate entry exists on docket for clinic letter  
* Multiple Petitioners (same address) - repped, unrepped, mix
* Multiple Petitioners (different address) - repped, unrepped, mix

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
**### Test Cases**

**1. Pro se petition is calendared for trial session with a Trial Location that has only one clinic letter available; notice setting case for trial is generated; notice document has appropriate clinic letter appended as final pages of document**

**2. Pro se petition is calendared for a trial session with a Trial Location that has multiple clinic letters available; notice setting case for trial is generated; notice document has appropriate clinic letter appended as final pages of document**


**3. Represented petition is calendared for a trial session with a Trial Location that has one or more clinic letters available; notice setting case for trial is generated; notice document has no clinic letter appended**


**4. Clinic letter for location is updated in repository; new pro se petition is calendared for trial; notice setting case for trial is generated with appropriate clinic letter appended as final pages of document**


**5. Notice Setting Case for Trial is generated w/ clinic letter appended; Notice is viewed from Docket Record; Notice displays in its entirety along with clinic letter; no separate entry exists on docket for clinic letter**

**Comment by TomElliottFlexion** [comment]
Clarified logic: Each pro se, paper-service petitioner on a case gets a clinic letter appended to their NTD. If any petitioner on the case needs a clinic letter, then the copy of the NTD on the docket record should have that clinic letter appended to it.

**Comment by codyseibert** [comment]
@ttlenard test case 11 seems incorrect.  It says setup a case and keep one petitioner as paper.  This would mean we should see some type of print paper service page, but the expected results say it should show a green success message which seems incorrect to me.

**Comment by cholly75** [comment]
Spoke w/ @TomElliottFlexion - NTD is not appending clinic letters for efilers. PO feedback delivered.

**Comment by ttlenard** [comment]
FYI - I did a few load tests with over 100 cases calendared.  The biggest trial session I created had 123 cases.  It completed in 11:20.  Big trial sessions seem ok!
