### ISSUE TITLE
Clinic Letter w/ Notice of Receipt of Petition (Proceeding Type)

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#9430]
As a petitions clerk, so that I can provide appropriate clinic letter documentation, I need to be able to send out clinic letters with the Notice of Receipt of Petition based on the Proceeding Type of the case.

For pro se petitioners who may not be able to afford or locate counsel to guide them through their case, there are tax clinics available as a resource who often advise and/or represent lower income petitioners. These clinics provide the Court with letters for petitioners indicating the details on how to use these resources, and as part of the Court's commitment to taxpayer equity prior to DAWSON we sent these letters to pro se petitioners along with official Court notices at various points in the life of the case.

These letters are not official Court or IRS documentation, but we provide them as a courtesy. There are one or more letters for each place of trial where the Court conducts business. It is possible for a location to have no clinic letter associated with it.

We would like to re-establish the process of generating and sending out these letters at the same time we send the Notice of Receipt of Petition by appending them to said Notices at the time the Notices are generated. Some locations will have multiple clinic letters available, one for Regular cases and another for Small cases.

The letters themselves are provided in toto by the clinics to the Court; no customization is needed to the letter text itself, and these are not docketed separately as entries on the official record.

This story is specifically to address this for petitioners whose requested place of trial has both Regular and Small case versions of a clinic letter to support. 

## Pre-Conditions
#9429

## Acceptance Criteria
* When a Notice of Receipt of Petition is generated for any case where the Petitioner is unrepresented by counsel and the requested place of trial has both Regular and Small case versions of a clinic letter available, the appropriate clinic letter is appended to the Notice after the final page of the Notice.
* The appended clinic letter displays along with the Notice in its entirety when viewed in DAWSON from the Print Confirmation link on the Case Information/Overview panel.
* When the clinic letter for either a Regular or Small Proceeding Type is replaced with a new version, all Notices of Receipt of Petition generated after that use the new version of that letter for the corresponding Proceeding Type.
* When the clinic letter for either a Regular or Small Proceeding Type is replaced with a new version, no previously generated Notices of Receipt of Petition are updated with the new version
* When the clinic letter for a Regular or Small proceeding type is removed but not replaced, Notices of Receipt of Petition do not append anything
* Court personnel can upload a new version of either type of clinic letter without having to upload both
* Court personnel can replace either type of an existing clinic letter with new version without having to replace both
* Court personnel can remove either type of an existing clinic letter in its entirety without having to remove both
* Court personnel can view either type of an clinic letter content without having to view a Notice of Receipt of Petition
* Clinic letters are accessible to DAWSON to incorporate/append to documentation

## Notes
[https://app.zenhub.com/files/152320868/5c393f35-10f4-48ab-82c4-1f805458b931/download](https://app.zenhub.com/files/152320868/5c393f35-10f4-48ab-82c4-1f805458b931/download)

[https://app.zenhub.com/files/152320868/530ae0be-626a-4586-8617-bf2e145e9e7b/download](https://app.zenhub.com/files/152320868/530ae0be-626a-4586-8617-bf2e145e9e7b/download)

## Test Cases

* Court uploads new clinic letter, categorizes letter based on location and proceeding type.
* Court replaces existing clinic letter, categorizes letter based on location and proceeding type; views letter, updated content is displayed.
* Court removes existing clinic letter; letter is no longer available in the system.
* Pro se petition is served with a requested place of trial for which multiple clinic letters are available; notice of receipt of petition is generated; notice document has appropriate clinic letter appended as final pages of document
* Pro se petition is served with a requested place of trial for which multiple clinic letters are available but no clinic letter exists for the proceeding type of the case; notice of receipt of petition is generated; notice document has no clinic letter appended
* Represented petition is served with requested place of trial for which multiple clinic letters are available; notice of receipt of petition is generated; notice document has no clinic letter appended
* Clinic letter for one proceeding type for a location is updated in repository; new pro se petition is served with requested place of trial and the same proceeding type as the updated letter; notice of receipt of petition is generated with updated clinic letter appended as final pages of document; previously generated notices of receipt of petition remain unchanged
* Notice of Receipt of Petition is generated w/ clinic letter appended; Notice is viewed via Print Confirmation link on Case Information/Overview panel; Notice displays in its entirety along with clinic letter

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
**### Test Cases**

Court uploads new clinic letter, categorizes letter based on location and proceeding type.


Court replaces existing clinic letter, categorizes letter based on location and proceeding type; views letter, updated content is displayed.


Court removes existing clinic letter; letter is no longer available in the system.


Pro se petition is served with a requested place of trial for which multiple clinic letters are available; notice of receipt of petition is generated; notice document has appropriate clinic letter appended as final pages of document


Pro se petition is served with a requested place of trial for which multiple clinic letters are available but no clinic letter exists for the proceeding type of the case; notice of receipt of petition is generated; notice document has no clinic letter appended


Represented petition is served with requested place of trial for which multiple clinic letters are available; notice of receipt of petition is generated; notice document has no clinic letter appended


Clinic letter for one proceeding type for a location is updated in repository; new pro se petition is served with requested place of trial and the same proceeding type as the updated letter; notice of receipt of petition is generated with updated clinic letter appended as final pages of document; previously generated notices of receipt of petition remain unchanged

Notice of Receipt of Petition is generated w/ clinic letter appended; Notice is viewed via Print Confirmation link on Case Information/Overview panel; Notice displays in its entirety along with clinic letter
