### ISSUE TITLE
Add Notice of Receipt of Petition to Docket Record 

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#9470]
As a court user, in order to provide full transparency to the public on the status of a case, I would like the docket record to reflect when a petition has been received/served by the court.

Currently when a petition is served to the IRS, DAWSON generates a Notice of Receipt of Petition informing the petitioner. This Notice (NOTR) is only made available via the Print Confirmation link located on the Case Information tab.

To standardize USTC processes and provide a transparent record of a case, we would like to add the NOTR as an entry on the Docket Record for the case and serve it to the Petitioner(s).

## Acceptance Criteria
* When a Notice of Receipt of Petition is generated, it is added to the Docket Record with the event code NOTR
* The value for the text in the "Filings and Proceedings" column on the Docket Record is "Notice of Receipt of Petition"
* Upon being added to the Docket Record, the Notice of Receipt of Petition is served to all petitioners (or counsel if represented) on the case
  * If the Petitioner has electronic service, they are notified via email in the usual manner
  * If the Petitioner has paper service, the clerk is presented with the Notice of Receipt of Petition for service (this already happens today)
* When viewed from the Docket Record, the Notice of Receipt of Petition reflects the file in its entirety as shown when viewing the Print Confirmation link 
* The Notice of Receipt of Petition is still available via the Print Confirmation link in the usual manner

## Test Cases
* Paper pro se petition is served, clerk is presented with printing paper service, the Notice of Receipt of Petition is added to the Docket Record and is still available on the Print confirmation link.
* Electronic pro se petition is served, the Notice of Receipt of Petition is added to the docket record, Petitioner receives an email that a document has been served on their case, Notice of Receipt of petition is available on the Print confirmation link.
* Represented electronic petition is served, the Notice of Receipt of Petition is added to the docket record, Counsel receives an email that a document has been served on their case, Notice of Receipt of petition is available on the Print confirmation link.
* Paper pro se petition with multiple petitioners (Petitioner and Spouse) with the same address is served, clerk is presented with printing paper service (only one NOTR is generated), the one Notice of Receipt of Petition is added to the Docket Record and is still available on the Print confirmation link.
* Paper pro se petition with multiple petitioners (Petitioner and Spouse) with different addresses is served, clerk is presented with printing paper service (there will be two NOTR documents, one for each petitioner), the two Notice of Receipt of Petitions are added to the Docket Record as one Notice, and it is still available on the Print confirmation link.

* Regression test Clinic Letters  (Small and Regular proceeding type) that get sent out with NOTR with pro se Petitioner, represented petitioner, multiple pro se petitioners with different addresses, multiple pro se petitioners with the same address, mixed representation, ensuring that clinic letters appear with the NOTR on the docket record. 

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
@codyseibert This story looks great on exp4, but I don't think that the changes that were implemented in 9464 were available yet.  Can we please push this code to TEST so that we can do some testing with the multiple NOTR clinic letter scenario? Thank you!
cc: @cholly75 @jimlerza

**Comment by ttlenard** [comment]
@codyseibert This story looks great on exp4, but I don't think that the changes that were implemented in 9464 were available yet.  Can we please push this code to TEST so that we can do some testing with the multiple NOTR clinic letter scenario? Thank you!
cc: @cholly75 @jimlerza
