### ISSUE TITLE
Chief Judge Transition

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#9483]
As a court, so that there is a smooth transition between Chief Judge officeholders, I need to make sure DAWSON is prepared to transition to the new Chief Judge on 6/1/2022.

On June 1 2022, Judge Kerrigan assumes the office of Chief Judge, an office held in its entirety during DAWSON's lifespan by Judge Foley.  Spike #9462 was completed to determine what needs to be addressed in DAWSON. This story is to implement those changes behind a feature flag so that we may activate them at the appropriate time in the future.

## Acceptance Criteria
* Changes needed as per #9462:
 * Add feature flag to enable switchover without deploy
 * Change value of chiefJudgeNameForSigning (conditionally w/ feature flag) in sharedAppContext and fix resulting broken hardcoded tests.
 * Refactor tests to use constant for Chief Judge instead (optionally do this step first to avoid broken tests)
 * Change Kerrigan's Title to Chief Judge and Foley's to Judge in judge_users.csv 
* Changes are implemented but deployed behind feature flag so as to not impact live environment until the Court is ready

## Test Cases
* Chief Judge signature is applied, reflects Judge Kerrigan as the officeholder
* Judge Foley's signature is applied, does not reflect Chief Judge title
* Judge Kerrigan's signature is applied, reflects Chief Judge title
* Chief Judge-filtered views/reports retain cases/sessions currently assigned to CJ
* Individual Kerrigan/Foley-filtered views/reports retain cases/sessions currently assigned to the respective judge

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Chief Judge signature is applied, reflects Judge Kerrigan as the officeholder

#### 2) Judge Foley's signature is applied, does not reflect Chief Judge title

#### 3) Judge Kerrigan's signature is applied, reflects Chief Judge title

#### 4) Chief Judge-filtered views/reports retain cases/sessions currently assigned to CJ

#### 5) Individual Kerrigan/Foley-filtered views/reports retain cases/sessions currently assigned to the respective judge

**Comment by ttlenard** [comment]
Here is what the Chief Judge Signature should look like:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/2ee5af21-d03d-4e10-be68-06341a905d87)

**Comment by ttlenard** [comment]
Some Testing Feedback:

1. Test Case 7 - Still seeing Chief Judge Foley, and "regular" Judge Kerrigan when sending messages
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/673b324a-fa03-439b-9865-06fa54d9c829)
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/0337d80d-02e8-4df8-9e48-d1a10bc6dbec)

2. Test Case 9 - Decision type of Orders - Docket entry Preview still says Chief Judge Foley and "Regular" Judge Kerrigan
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/0d41a7f0-08f3-4d62-a02e-bb2711f71f21)
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/5dd704fd-8f32-4d92-a282-42cdf9270b1c)
