### ISSUE TITLE
Add Filtering to ADC Section Messages

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#9488]
As a ADC user, so that I can prioritize and understand the work that needs to be done by our section, I need to be able to filter the Section displayed messages.

The ADC section is facing a large backlog of work that needs to be addressed. Operationally so that a more targeted view of messages that need responding to can be addressed, we want to be able to filter the Section Messages for specific values.

We expect to extend this functionality to other Section messages in the near future.

## Pre-Conditions
#9490

## Acceptance Criteria
* ADC Section messages Inbox and Sent display can be filtered for a specific value present in the Case Status field
* ADC Section messages Inbox and Sent display can be filtered for a specific value present in the To field
* ADC Section messages Inbox and Sent display can be filtered for a specific value present in the From field
* ADC Section messages Inbox and Sent display can be filtered for a specific value present in the Section field
* ADC Section messages Completed display can be filtered for a specific value present in the Completed By field
* ADC Section messages Completed display can be filtered for a specific value present in the Section field
* Filter selections refresh the list of displayed messages according to the selected filters immediately upon selection
* Multiple filters can be selected concurrently
* Filters can be cleared
* Filters are available on each view (Inbox, Sent, Completed)
* Filters can be applied in conjunction with sorting criteria

## Test Cases
* Section displays all messages; filter selection is made for To field; displays only messages with the corresponding value in the To field
* Section displays all messages; filter selection is made for From field; displays only messages with the corresponding value in the From field
* Section displays all messages; filter selection is made for Case Status field; displays only messages with the corresponding value in the Case Status field
* Section displays all messages; filter selection is made for Section field; displays only messages with the corresponding value in the Section field
* Filter is applied; display updates appropriately; filter value is changed to a different value; display updates again appropriately
* Filter is applied; display updates appropriately; filter value is cleared; display updates again to display all messages
* Filter is applied; display updates appropriately; additional filter(s) applied; display updates appropriately with each filter selection

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to the Court's `test` environment for PO Review

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Section displays all messages; filter selection is made for To field; displays only messages with the corresponding value in the To field
- Log in as an ADC
- Click on "Switch to Section Messages" URL
- Be sure that you are on the Inbox tab
- Click on the "To" filter and make a selection
Expected Results

- [ ] The Inbox is now filtered and only displays messages with the corresponding value in the "To" field.
- [ ] The message count has updated to reflect the number of messages that are in the inbox associated with the "To" value.


#### 2) Section displays all messages; filter selection is made for From field; displays only messages with the corresponding value in the From field


#### 3) Section displays all messages; filter selection is made for Case Status field; displays only messages with the corresponding value in the Case Status field


#### 4) Section displays all messages; filter selection is made for Section field; displays only messages with the corresponding value in the Section field


#### 5) Filter is applied; display updates appropriately; filter value is changed to a different value; display updates again appropriately


#### 6) Filter is applied; display updates appropriately; filter value is cleared; display updates again to display all messages


#### 7) Filter is applied; display updates appropriately; additional filter(s) applied; display updates appropriately with each filter selection

**Comment by swongCO** [comment]
![Section Messages - Inbox.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/225aa6d9-e9e8-45a3-8fc5-c95454bc91aa)
![Section Messages - Sent.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/1b072cca-7a23-4b34-a4f2-ceedcd8f4aa8)
![Section Messages - Completed.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/6c2cab2a-aae2-4c9e-be91-66fc11169e12)

- Use existing design and interaction for filter components
- Inbox and Sent have the same four filters; Completed has "Completed By" and "Section"

**Comment by cholly75** [comment]
Removed AC: "* Message count is updated when filters are applied" - will address message count across application filtered pages together in a separate story

**Comment by codyseibert** [comment]
@cholly75 also made a comment to not display the section on the completed queue since everything in the completed queue will always be the same section
