### ISSUE TITLE
Add Filtering to ADC User Messages

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#9489]
As a ADC user, so that I can prioritize and understand my work, I need to be able to filter my displayed messages.

The ADC section is facing a large backlog of work that needs to be addressed. Operationally so that a more targeted view of messages that need responding to can be addressed, we want each ADC user to be able to filter their Messages for specific values.

We expect to extend this functionality to other user messages in the near future.

## Pre-Conditions
#9491

## Acceptance Criteria
* ADC user messages Inbox display can be filtered for a specific value present in the Case Status field
* ADC user messages Inbox display can be filtered for a specific value present in the From field
* ADC user messages Inbox display can be filtered for a specific value present in the Section field
* ADC user messages Sent display can be filtered for a specific value present in the Case Status field
* ADC user messages Sent display can be filtered for a specific value present in the To field
* ADC user messages Sent display can be filtered for a specific value present in the Section field
* Filter selections refresh the list of displayed messages according to the selected filters immediately upon selection
* Multiple filters can be selected concurrently
* Filters can be cleared
* Filters are available on views (Inbox, Sent)
* No filters required on user messages Completed messages view
* Filters can be applied in conjunction with sorting criteria

## Test Cases
* User messages display all messages; filter selection is made for From field; displays only messages with the corresponding value in the From field
* User messages display all messages; filter selection is made for Case Status field; displays only messages with the corresponding value in the Case Status field
* User messages display all messages; filter selection is made for Section field; displays only messages with the corresponding value in the Section field
* Filter is applied; display updates appropriately; filter value is changed to a different value; display updates again appropriately
* Filter is applied; display updates appropriately; filter value is cleared; display updates again to display all messages
* Filter is applied; display updates appropriately; additional filter(s) applied; display updates appropriately with each filter selection

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to the Court's `test` environment for PO Review

**Comment by ttlenard** [comment]
##  Test Cases

#### 1) User messages display all messages; filter selection is made for From field; displays only messages with the corresponding value in the From field


#### 2) User messages display all messages; filter selection is made for Case Status field; displays only messages with the corresponding value in the Case Status field


#### 3) User messages display all messages; filter selection is made for Section field; displays only messages with the corresponding value in the Section field


#### 4) Filter is applied; display updates appropriately; filter value is changed to a different value; display updates again appropriately


#### 5) Filter is applied; display updates appropriately; filter value is cleared; display updates again to display all messages


#### 6) Filter is applied; display updates appropriately; additional filter(s) applied; display updates appropriately with each filter selection

**Comment by swongCO** [comment]
![My Messages - Inbox.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/9d4ace95-618a-4d23-a408-c77649381413)
![My Messages - Sent.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/11f827c7-2d77-462c-a8cb-c491d912ff89)
![My Messages - Completed.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/9c1d5775-b7d3-4fac-9794-b7bb1a772cdd)

- Use existing design and interaction for filter components
- Inbox filters: Case Status, From, Section
- Sent filters: Case Status, To, Section
- Completed filter: Case Title
