### ISSUE TITLE
Add Sorting to ADC User Messages

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#9491]
As a ADC user, so that I can prioritize and understand work assigned to me, I need to be able to sort the user messages by docket number, received date, or subject.

The ADC section is facing a large backlog of work that needs to be addressed. Operationally so that a more targeted view of messages that need responding to can be addressed, we want to be able to sort the user messages display by specific criteria.

We expect to extend this functionality to other user messages in the near future.

## Acceptance Criteria
* ADC user messages display can be sorted numerically by Docket Number (ascending or descending)
* ADC user messages display can be sorted chronologically by Received Date (ascending or descending)
-This is the Received date, Sent date, or Completed date depending on the view.
* ADC user messages display can be sorted alphabetically by Message Subject (ascending or descending)
-This is the Message or Last Message column depending on the view.
* Sorting refreshes the list of displayed messages according to the chosen sort criteria
* After a sorting option is chosen, the user messages display can be reverted to its default sort organization
* Sorting is available on each view (Inbox, Sent, Completed)

## Test Cases
* User messages display all messages by default sort criteria; user sorts by Docket Number (ascending); displays all messages sorted by Docket Number (ascending)
* User messages display all messages by default sort criteria; user sorts by Docket Number (descending); displays all messages sorted by Docket Number (descending)
* User messages display all messages by default sort criteria; user sorts by Received Date (ascending); displays all messages sorted by Received Date (ascending)
* User messages display all messages by default sort criteria; user sorts by Received Date (descending); displays all messages sorted by Received Date (descending)
* User messages display all messages by default sort criteria; user sorts by Message Subject (ascending); displays all messages sorted by Message Subject (ascending)
* User messages display all messages by default sort criteria; user sorts by Message Subject (descending); displays all messages sorted by Docket Number (descending)
* Sort criteria other than the default criteria is applied; message display is updated according to new criteria; sort is reverted to default criteria; message display is updated again

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to the Court's `test` environment for PO Review

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Section displays all messages by default sort criteria; user sorts by Docket Number (ascending); displays all messages sorted by Docket Number (ascending)


#### 2) Section displays all messages by default sort criteria; user sorts by Docket Number (descending); displays all messages sorted by Docket Number (descending)


#### 3) Section displays all messages by default sort criteria; user sorts by Received Date (ascending); displays all messages sorted by Received Date (ascending)


#### 4) Section displays all messages by default sort criteria; user sorts by Received Date (descending); displays all messages sorted by Received Date (descending)


#### 5) Section displays all messages by default sort criteria; user sorts by Message Subject (ascending); displays all messages sorted by Message Subject (ascending)


#### 6) Section displays all messages by default sort criteria; user sorts by Message Subject (descending); displays all messages sorted by Docket Number (descending)


#### 7) Sort criteria other than the default criteria is applied; message display is updated according to new criteria; sort is reverted to default criteria; message display is updated again

**Comment by swongCO** [comment]
IGNORE FILTERS FOR THIS STORY
![My Messages - Inbox.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/02bbdd3d-1d9b-4f01-9ec5-70ae6a66ddd8)
![My Messages - Sent.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/0d7a13dd-7835-4aa8-adfb-dbcfece5cf97)
![My Messages - Completed.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/907da721-89c1-40ae-bc2c-fd76f2d6bbb9)

- Use existing design and interaction for sorting components
- Sorted column label is underlined
