### ISSUE TITLE
Online Cited Sources

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#9515]
As a court, so that online-only sources cited in opinions can be persisted in the official record, I need to be able to add these sources to the docket record.

Sometimes in the course of writing an opinion, a judge will cite a source that is only available on the internet. In these cases, it's important to provide these sources as they are at the time of citation. Currently the Court process for handling this is to provide scans of the source to our webmaster, who posts these on the Court website at https://ustaxcourt.gov/sources_cited.html 

As these become more common, the Court has decided to make these sources available on the docket record of the case(s) associated to the opinion in which they are cited. To that end, we need a new document event code for these types of documents.
 
## Acceptance Criteria
* Online Cited Sources are always entered initially into DAWSON via the PDF Upload functionality
* A new document type is available for selection when adding a draft PDF as a docket entry: "Online Cited Source"
* Docket clerks are able to add a Description for these documents that will display in the "Filings and Proceedings" column on the docket record
* Docket clerks are able to add a Filed Date for the docket entry
* Documents created with this document type are visible on the docket record with event code: "OCS"
* OCS entries do not receive cover sheets.
* OCS entries are *never* served to any parties when added to the docket record.
* OCS entries *cannot* be served after being added to the docket record.
* OCS documents are visible and hyperlinked for all court users, parties on the case, counsel, and the general public when viewing the docket record.
* OCS documents obey all other visibility rules (i.e., sealing at the case/document level)

## Notes
* Cannot go live prior to 6/22/22
Not searchable

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Test cases reviewed by an engineer on a deployed environment for Engineering Review.
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by TomElliottFlexion** [comment]
Questions:

- Should description on docket record be truncated? Separated from the title? 
- Should the doc really open in a new tab instead of the document preview?

**Comment by rgoshen** [comment]
added "the" before "docket record"

**Comment by swongCO** [comment]
@TomElliottFlexion To answer your second question... I believe the new tab opens for parties and the public only. They don't have a document view. It looks like standard behavior for all documents for these users. 
cc @liadmccabe @ttlenard @cholly75
