### ISSUE TITLE
Bug: 401 errors not sending users back to login screen

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#966]
Found by: Eric on 2/27/19

![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/15323ce7-b236-4a8d-9011-ccfdc880060a)

**Comment by waldoj** [comment]
@ericsorenson, I'm trying to figure out how to QA this. It looks like the initial bug was that, when logged into the dev site as a petitions clerk and viewing the home page, the request for `https://efcms-dev.ustc-case-mgmt.flexion.us/v1/sections/petitions/users` was returning a 401. Was anything else required to trigger that behavior?

FWIW, I can confirm that, logged into the dev site as a petitions clerk and viewing the home page, the request for `https://efcms-dev.ustc-case-mgmt.flexion.us/v1/sections/petitions/users` correctly returns a 200.
