### ISSUE TITLE
Redaction Acknowledgment for E-Filed Documents

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#9864]
As a Court, so that I can increase awareness of the need to redact documents, I need e-filers to acknowledge their redactions prior to e-filing documents in an existing case.

Despite Court policy and repeated admonitions to petitioners and counsel to redact personal information from filed documents, we still see a large number of documents filed with unredacted PII. As we do not currently have a way of vetting the contents of a given e-filed document, in order to reduce or remove liability to the USTC for any personal information that may end up on the public record unintentionally, we want to implement a step in the e-filing workflow for all petitioners and practitioners that requires them to acknowledge that they have redacted the documents they are filing. 

This will be an affirmative acknowledgement required on the part of the e-filer before finalizing their document submission to DAWSON. This will affect all e-filers, regardless of role.

## Acceptance Criteria
* Prior to being able to click the "Submit Your Filing" button on the last page of the e-filing workflow, the user is presented with a redaction text snippet (to be provided) set apart from other text on the page 
  - No modal/pop-up windows used in implementation
* User cannot click the "Submit Your Filing" button until they affirmatively acknowledge the redaction text
* Upon acknowledging the text, the user can click the "Submit Your Filing" button and proceed with e-filing as usual
* This applies to all e-filers regardless of role and document type
* This does **not** apply to the petition submission/start a case workflow

## Notes
* Must work on mobile UI as well

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitioner starts to efile a document on their case; Yellow colored alert banner has reminder to remove personally identifiable information.

- Log in as a Petitioner
- Click on the docket number of a case from the My Cases Page
- Click on File a Document Button
- Click Ok, I'm Ready to File button
- Select a document from the Document Type dropdown
- Click Continue

Expected Results
- [ ] **NEW FUNCTIONALITY** - New yellow banner is on the File a Document page between the name of the document type and the upload section.
- [ ] **NEW FUNCTIONALITY** - Banner is not dismissible
- [ ] **NEW FUNCTIONALITY** - Text in the banner matches the Mockup above
- [ ] **NEW FUNCTIONALITY** - Width of the banner is responsive to the screen size and adjusts accordingly if you minimize your screen.



#### 2) Petitioner continues the workflow to efile a document on their case; Yellow banner is displayed and a new confirmation checkbox is required before Petitioner can submit the document.

- Continuing from the previous test
- Upload a document
- Click Review Filing button

Expected Results:
- [ ] **NEW FUNCTIONALITY** - Yellow banner is displayed below the text under the Review Your Filing page
- [ ] **NEW FUNCTIONALITY** - Banner is not dismissible
- [ ] **NEW FUNCTIONALITY** - Text in the banner matches the Mockup above
- [ ] **NEW FUNCTIONALITY** - Width of the banner is responsive to the screen size and adjusts accordingly if you minimize your screen.
- [ ] **NEW FUNCTIONALITY** - Checkbox and confirmation text is added at the bottom of the page, above the Submit your Filing button.
- [ ] **NEW FUNCTIONALITY** - The Submit your Filing button is greyed out and cannot be selected if the confirmation checkbox is not checked.
- [ ] **NEW FUNCTIONALITY** - Once the checkbox is selected, the Submit Your Filing button becomes active and can be clicked.



#### 3) Repeat tests 1 and 2 with IRS Practitioner and Private Practitioner.

- [ ] Tests 1 and 2 Pass with IRS Practitioner
- [ ] Tests 1 and 2 Pass with Private Practitioner



#### 4) Regression test to ensure that the this new checkbox functionality and the yellow alert message is displayed is incorporated into IRS filing a document in a consolidated Case story.

- [ ] Test cases 1 and 2 Pass with the IRS filing across a Consolidated case group


#### 5) Repeat tests 1 and 2 using a Mobile device

- [ ] Test case 1 and 2 pass on mobile device.
- [ ] **NEW FUNCTIONALITY** - Look and feel on mobile device is consistent with the mockups



#### 6) Regression test this with the Feature Flag Off

**Comment by cholly75** [comment]
Redaction text: "All documents I am filing have been redacted in accordance with the Rule 27."

**Comment by TomElliottFlexion** [comment]
"Rule 27" will hyperlink to https://ustaxcourt.gov/resources/ropp/Rule-27_Amended_03202023.pdf and will open in a new tab

**Comment by ttlenard** [comment]
feature flag name: redaction-acknowledgement-enabled

**Comment by ttlenard** [comment]
@TomElliottFlexion the updates you made look great. Thank you!

**Comment by ttlenard** [comment]
@jimlerza  Please deploy with the FF off. Plan is to turn the FF back on Monday.
