### ISSUE TITLE
Judge/CA: WIP Case Worksheet

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#9995]
As a judge or judge's CA, so that I can provide appropriate context for the cases I have in progress, I need a way to add metatextual information to my cases awaiting a decision.

With #9980 we added WIP cases to the Judge Activity Report to provide a better picture of the workload for any given judge. To better communicate the specific issues at hand in these cases, categorize them contextually, and be transparent about the expected next steps, we would like a way for each judge and/or their chambers to provide information on these WIP cases for eventual consumption by the judge activity report; the desire is to have a UI that persists data, is available from the judge/CA Dashboard, and automatically updates according to specific criteria. 

As this information is (for now) volatile, it need only exist in this UI, until we get around to #10049 (pulling the data entered here on to the Activity report). 

A follow-on story will leverage the information provided on the Case Worksheet for use in the Activity Report.

## Acceptance Criteria
* "Case Worksheet" is visible to judge/CA users
  - If the user is a judge, CW is filtered to display cases assigned to that judge
  - If the user is a CA, CW is filtered to display cases assigned to the judge for whom the CA works
* "Case Worksheet" displays all cases assigned to a judge that would normally appear in the Submitted/CAV section of the Activity Report, with the same information displayed in the Activity Report
* Cases are ordered by Days in Status, descending (most -> least)
* The "Case Worksheet" also displays the following information for each case:
  - Primary Issue
  - Date Transitioned (?)
  - Due Date of Final Briefs
  - Status of Matter
* PRIMARY ISSUE: the user can enter text explaining the issue at hand in the case
* DATE TRANSITIONED: this reflects the most recent date the case was transitioned to its Submitted/CAV status as per the Case History
* DUE DATE OF FINAL BRIEFS: the user can enter a date
* STATUS OF MATTER: the user can select a value from the following list:
  - LOV for Status of Matter:
    - Awaiting Consideration
    - Awaiting Briefs
    - Drafting
    - Reviewing Draft
    - Submitted to Chief Judge
    - Revising Draft
    - Submitted to Reporter
    - Stayed
* Information entered in interactive fields persists on the "Case Worksheet" regardless of the individual user

## Notes
* Would modeling this on the Session Copy UI used for Trial Sessions be helpful?
* Can we have this accessible either on or as a link from the judge/CA dashboard?

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [x] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
**UX Notes**

![Activity report - case worksheet.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/7915e56d-cbfc-4809-a935-371d50870dd3)

Copy Submitted/CAV Cases table from Activity report with the following additions:
- Add these columns after Days in Status: Status Date; Final Brief Due Date; Status of Matter
- Status Date is when the case changed status to Submitted or CAV
- Status of Matter dropdown will include list from AC in the order it's listed
- Add a row below the case row for Primary Issue
- Refer to Session Copy page/Notes for styling and functionality of Primary Issue row
- No pagination component is required at this time
___

![Activity report - case worksheet - modal.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/e16b1f60-df54-4299-bd4c-a25ccdef3b12)
- Modal displays when add or edit link is clicked
- Display docket no. and petitioner above the text field 
- Refer to Session Copy/Notes for styling and functionality

**Comment by jhansen-flexion** [comment]
Put a blocker on this until 9998 is complete.

**Comment by swongCO** [comment]
UX Review feedback:
The text container of the Primary issue should extend to the right, before the links. See mockup above in UX notes for reference. Right now this is what a long paragraph looks like:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHQ3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9f776db430453f5923b95e7a6053a79b756d7ecb/Screenshot%202023-09-07%20at%202.10.25%20PM.png)

Also looks like when there is a primary issue, the column widths are shifting to the right. Compare the above image to the one below and notice that from Case Status on, the columns are in different positions.   

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclI3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--63320c2aa16ca3832d61166e9c1adeb6accfb1e2/Screenshot%202023-09-07%20at%202.22.24%20PM.png)

**Comment by cholly75** [comment]
@swongCO @katiecissell to make a mockup of a modal for editing the values for a given docket so we can move to a read-only table

Additional issues noted: 

1) Would prefer docket link to open case in a new tab to preserve view of dashboard
2) Don't need a comma in 4 digit numbers

**Comment by swongCO** [comment]
**UX Notes**

Due to how USWDS handles tables (as read only) we will pivot to another data input method to ensure that all inputs are displayed in whole.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakNKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9e65c2d56ee7b884471b8976a343e6e4dc8a94b7/Activity%20report%20-%20case%20worksheet.png)
- add Edit icon link at the end of the case row
- display Primary issue row even when it's blank
- keep left alignment of Primary issue with Petitioner column and allow Primary issue to span to the end of the row
___

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHFKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1ee4e2990e3096050f834b7b62921a33eeab9691/Activity%20report%20-%20case%20worksheet%20modal.png)
- display modal when Edit link is clicked
- modal title will include docket number that is being edited
- include standard validation for date picker component
- Primary issue text field is expandable/collapsible vertically by dragging on the lower right corner

**Comment by swongCO** [comment]
UX feedback on exp3:
- can you make the primary issue row span all the way to the end of the table? rn it looks like it stops at the Status of Matter column
- Make Primary Issue font weight the same as in the header (semibold I believe)
- Modal: Change the title to "Edit Details"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdE9uIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--31a2e22fd5b88e51ecbdd6285d6d5a244cf0ba30/Screenshot%202023-09-15%20at%202.30.21%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFNuIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--28c980c5c7e7480ffd838306f0cf2103937dee33/Screenshot%202023-09-15%20at%202.29.40%20PM.png)
